<?php
/**
*
* @package Icy Phoenix
* @version $Id: lang_faq.php 97 2009-05-01 17:18:07Z Mighty Gorgon $
* @copyright (c) 2008 Icy Phoenix
* @license http://opensource.org/licenses/gpl-license.php GNU Public License
*
*/

/**
*
* @Icy Phoenix is based on phpBB
* @copyright (c) 2008 phpBB Group
*
*/

/**
*
* @Extra credits for this file
* Lopalong
*
*/

if (!defined('IN_ICYPHOENIX'))
{
	exit;
}

//
// To add an entry to your FAQ simply add a line to this file in this format:
// $faq[] = array("question", "answer");
// If you want to separate a section enter $faq[] = array("--","Block heading goes here if wanted");
// Links will be created automatically
//
// DO NOT forget the ; at the end of the line.
// Do NOT put double quotes (") in your FAQ entries, if you absolutely must then escape them ie. \"something\"
// The FAQ items will appear on the FAQ page in the same order they are listed in this file


$faq[] = array("--","Inloggning och Registreringsfrågor");
$faq[] = array("Varför kan jag inte logga in?", "Har du registrerat dig? Allvarligt, du måste registrera dig för att logga in. Har du blivit bannlyst från forumet? (Ett meddelande kommer att visas om du har.) Om så är fallet, bör du kontakta den webbansvariga eller forumets administratör och ta reda på varför. Om du har registrerat dig och inte är bannlyst och du fortfarande inte kan logga in kontrollera och dubbelkontrollera ditt användarnamn och lösenord. Oftast är det problemet, om inte, kontakta forumets administratör - du kan ha fel inställningar för forumet.");
$faq[] = array("Varför måste jag registrera mig överhuvud taget?", "Du kanske inte behöver det - det är upp till administratören i forumet om du måste registrera dig för att skicka meddelanden. Men registrering ger dig tillgång till ytterligare funktioner som du inte har tillgång till som gäst-användare så som definierbara avatar bilder, privata meddelanden, e-post till andra användare, användargrupp abonnemang etc. Det tar bara ett par minuter att registrera sig så det rekommenderas att du gör det.");
$faq[] = array("Varför blir jag automatiskt utloggad?", "Om du inte kontrollerar <i>Logga in mig automatiskt</i> rutan när du loggar in kommer forumet att bara hålla dig inloggad på en förinställd tid. Detta förhindrar missbruk av ditt konto av någon annan. Att stanna inloggad, markera rutan vid inloggningen. Detta rekommenderas inte om du går till forumet från en delad dator, t.ex. bibliotek, internet cafe, universitet kluster etc.");
$faq[] = array("Hur förhindrar jag att mitt användarnamn visas i Online användar listor?", "I din profil kan du hitta ett alternativ  <i>Dölj din online status</i>; Om du slår detta till <i>på</i> visas detta bara för forumets administratör eller dig själv. Du kommer att räknas som en dold användare.");
$faq[] = array("Jag har tappat bort mitt lösenord!", "Ingen panik! även om ditt lösenord kan inte hämtas det kan återställas. För att göra detta gå till inloggningssidan och klicka på <u>Jag har glömt mitt lösenord</u>. Följ instruktionerna och du bör vara tillbaka online på nolltid.");
$faq[] = array("Jag registrerade men kan inte logga in!", "Kontrollera först att du anget rätt användarnamn och lösenord. Om de är okej kan en av två saker ha hänt: Om COPPA stödet är aktiverat och du klickat på <u>Jag är under 13 år</u> länken samtidigt som du registrerar måste du sedan följa instruktionerna du fått. Om så inte är fallet så kanske ditt konto behöver aktiveras. Vissa skivor kommer att kräva att alla nya registreringar aktiveras, antingen av dig själv eller av administratören innan du kan logga in. När du registrerat skulle de ha berättat för dig om aktivering krävdes eller ej. Om du har skickats ett e-postmeddelande till dig följ instruktionerna; Om du inte fick någon e-post kontrollera att din e-postadress är giltig. En orsak till att aktivering anvönds är för att minska risken för <i>skurkar</i> användare som missbrukar forumet anonymt. Om du är säker på att e-postadressen du använde är giltig försök kontakta forumets administratör.");
$faq[] = array("Jag registrerade tidigare, men kan inte logga in längre!", "De mest sannolika orsakerna till detta är: du har angett ett felaktigt anvöndarnamn eller lösenord (kontrollera e-post meddelandet som du fick när du först registrerade) eller har administratören raderat ditt konto av någon anledning. Om det är det senare fallet kanske du inte skickade in något inlägg? Det är vanligt för forum att regelbundet ta bort användare som inte har postat något för att minska storleken på databasen. Försök att registrera igen och få delta i diskussionerna.");


$faq[] = array("--","Användar Företräde och inställningar");
$faq[] = array("Hur ändrar jag mina inställningar?", "Alla dina inställningar (om du har registrerat dig) lagras i databasen. För att ändra dem klickar du på <u>Profil</u> länkar (vanligtvis visas de längst upp på sidorna, men detta kanske inte är fallet). Detta gör att du kan ändra alla dina inställningar.");
$faq[] = array("Tiderna är inte korrekta!", "Tiderna är nästan säkert korrekta; men vad du ser är tid som visas i en tidszon annan än den du befinner dig i. Om så är fallet, bör du ändra din profil inställning för tidszon att matcha dina särskilda område, t.ex. London, Paris, New York, Sydney, osv. Observera att byte av tidszon, i likhet med de flesta inställningar kan endast göras av registrerade användare. Så om du inte är registrerad, är detta ett bra tillfälle att göra det, om du ursäktar!");
$faq[] = array("Jag har ändrat tidszonen men tiden är fortfarande fel!", "Om du är säker på att du har satt tidszonen korrekt och tiden fortfarande är olika, det mest troliga svaret är SOMMARTID (som det kallas i Storbritannien och andra ställen). Forumet är inte konstruerat för att hantera övergången mellan standard-och sommartid så under sommarmånaderna kan tiden skilja sig en timme från den verkliga lokala tiden.");
$faq[] = array("Mitt språk är inte i listan!", "De mest sannolika orsakerna till detta är antingen att administratören inte har installerat ditt språk eller någon inte har översatt detta forumet till ditt språk. Prova att fråga forum administratören om de kan installera språkpaketet du behöver, eller om det inte finns får du gärna skapa en ny översättning. Mer information finns på Icy Phoenix Gruppens hemsida (se länken längst ner på sidorna)");
$faq[] = array("Hur kan jag visa en bild under mitt användarnamn?", "Det kan finnas två bilder under ett användarnamn när du tittar på inlägg. Den första är en bild som förknippas med din rank; i allmänhet ges dessa i form av stjärnor eller block som visar hur många inlägg du har gjort eller din status på forumet. Nedanför detta kan det vara en större bild som kallas för avatar; denna är i allmänhet unik eller personlig för varje användare. Det är upp till forumets administratör att aktivera avatarer och de har ett val över det sätt till vilka avatarer kan göras tillgängliga. Om du inte kan använda avatarer sä är det ett beslut som fattats av forumets admin och du bör fråga han om deras skäl (vi är säkra på att de ska vara bra!)");
$faq[] = array("Hur ändrar jag min rank?", "I allmänhet kan du inte direkt ändra formuleringen i någon rang (rangen visas under ditt användarnamn i ämnen och i din profil beroende på vilken stil som används). De flesta forum använder rangen till att ange hur många inlägg som du har gjort och för att identifiera vissa användare. Till exempel, moderatorer och administratörer kan ha en speciell rank. Jag ber er att inte missbruka forumet genom att posta i onödan bara för att öka din rank - du kommer förmodligen hitta moderator eller administratör som helt enkelt kommer att sänka din inläggs räkning.");
$faq[] = array("När jag klickar på e-post länken för en användare ber de mig att logga in.", "Tyvärr, men endast registrerade användare kan skicka e-post till människor via det inbyggda e-post formuläret (om admin har aktiverat funktionen). Detta för att förhindra skadlig användning av e-post systemet av anonyma användare.");

$faq[] = array("--","Posting Issues");
$faq[] = array("Hur lägger jag upp ett ämne i ett forum?", "Enkelt -- klicka på den relevanta knappen på antingen forum eller ämnes skärmen. Du kan behöva registrera dig innan du kan skicka ett meddelande. De inrättningar som finns tillgängliga för att du är listad finns längst ner på forum och ämnes skärmen (den <i>Du kan skicka nya ämnen, du kan rösta i omröstningar, etc.</i> listan)");
$faq[] = array("Hur kan jag redigera eller ta bort en post?", "Om du inte är forum admin eller forum moderator kan du bara ändra eller radera dina egna inlägg. Du kan redigera ett inlägg (ibland bara för en begränsad tid efter att den var gjord) genom att klicka på <i>redigera</i> knappen för det relevanta inlägget. Om någon redan har svarat på inlägget, hittar du en liten bit av text produktionen under inlägget när du återvänder till det ämne som anger hur många gånger du redigerat det. Detta kommer bara att visas om ingen har svarat; Dessutom kommer det inte att visas om moderatorer eller administratörer redigerat inlägget (de ska lämna ett meddelande som säger vad de ändrat och varför). Observera att vanliga användare inte kan radera en post när någon har svarat.");
$faq[] = array("Hur lägger jag till en signatur i mina inlägg?", "Om du vill lägga till en signatur till ett meddelande måste du först skapa en; detta görs via din profil. När du väl har skapat en kan du kontrollera <i>Lägg till Signatur</i> rutan i inläggs formuläret för att lägga till din signatur. Du kan också lägga till en signatur automatiskt till alla dina inlägg genom att kryssa i lämpligt fält i din profil. Du kan fortfarande förhindra att en signatur läggs till enskilda inlägg genom att av-kontrollera lägg till signatur rutan i inläggs formuläret.");
$faq[] = array("Hur skapar jag en omröstning?", "Skapa en omröstning är lätt -- när du lägger upp ett nytt ämne (eller redigerar det första inlägget i ett ämne, om du har behörighet) bör du se en <i>Lägg till Omröstning</i> formuläret nedanför huvud inläggs rutan. Om du inte kan se detta då har du förmodligen inte rättigheter att skapa en omröstning. Du bör ange en titel för omröstningen och sedan minst två alternativ -- att ställa in ett alternativ skriv in omröstningsfrågan och klicka på <i>Lägg till alternativ</i> knappen. Du kan också ställa in en tidsgräns för omröstningen, 0 är en oändlig mängd. Det kommer att finnas en gräns för hur många alternativ du kan lista, som fastställs av forumets administratör");
$faq[] = array("Hur kan jag redigera eller ta bort en omröstningen?", " Som med inlägg, kan omröstningen endast redigeras av den ursprungliga skaparen, en moderator eller forumets administratör . Om du vill redigera en omröstning klicka på första inlägget i det ämne, som alltid har omröstningen förknippad med det. Om ingen har röstat kan användaren kan ta bort omröstningen eller redigera ett omröstnings alternativ. Men, om folk redan har placerat röster kan bara moderatorer eller administratörer redigera eller ta bort det; detta för att förhindra att människor riggar omröstning genom att ändra alternativ halvvägs genom en omröstning");
$faq[] = array("Varför har jag inte tillgång till ett forum?", "Vissa forum kan vara begränsade till vissa användare eller grupper. För att visa, läsa, posta, etc. Du kan behöva särskilt tillstånd som endast forumets moderator och forumets administratör kan ge, så du bör kontakta dem.");
$faq[] = array("Varför kan jag inte rösta i omröstningar?", "Endast registrerade användare kan rösta i omröstningar för att förhindra kapning av resultatet. Om du har registrerat dig och ändå inte kan rösta så har du förmodligen inte lämpliga åtkomsträttigheter.");

$faq[] = array("--","Formatering och Ämnes Typer");
$faq[] = array("Vad är BBKod?", "BBKod är en särskild tillämpning av HTML. Oavsett om du kan använda BBKod bestäms det av administratören. Du kan också stänga av den för varje post från inläggs formuläret. BBKod själv är av liknande typ som HTML: taggar omges av kvadratiska hängslen [och] i stället för &lt; och &gt; och det ger större kontroll över vad och hur någonting visas. För mer information om BBKod se guiden som kan nås från inläggs sidan (eller klicka på denna länk: <a href=\"faq.php?mode=bbcode\">BBKod Hjälp</a>).");
$faq[] = array("Kan jag använda HTML?", "Det beror på om administratören tillåter dig det; de har fullständig kontroll över det. Om du får använda den, kommer du förmodligen bara att hitta vissa tagg arbeten. Detta är en <i>säkerhets</i> funktion för att hindra personer från att missbruka forumet genom att använda taggar som kan förstöra layouten eller orsaka andra problem. Om HTML är aktiverad kan du stänga av den för varje post från inläggs formuläret.");
$faq[] = array("Vad är Smileys?", "Smileys, eller Emotikoner, är små grafiska bilder som kan användas för att uttrycka en viss känsla med hjälp av en kort kod, EXEMPEL. :) betyder lycklig, :( innebär sorgligt. Den kompletta listan av emotikoner kan ses via inläggs formuläret. Försök att inte överanvända smileys, eftersom de snabbt kan göra en post oläslig och en moderator kan besluta att ändra dem eller ta bort tjänsten helt och hållet.");
$faq[] = array("Kan jag posta bilder?", "Bilder kan även visas i dina inlägg. Administratörer kan ha aktiverat specialfunktioner för att ladda upp bilder direkt på denna webbplats och detta kan ske på tre sätt: Bilagor, Album och Ladda Upp Bilder. Album är bäst när du vill att dina bilder är tillgänglig även i gallerier och du har en bättre kontroll på hur miniatyrbilder genereras (även vattenstämpeln kan ingå). Bilagor och Ladda Upp Bilder funktionerna kan användas direkt när du skriver ett brev, och har olika ändamål. Ladda upp en bild i stället för \"bifoga\" den är lämplig när man vill kontrollera insättningspunkten i den ... gör dina inlägg trevligare. Om admins har stängt av alla hjälpmedel för att ladda upp bilder direkt till denna webbplats måste du länka till en bild som lagras på en allmän webbserver, t.ex. http://www.some-unknown-place.net/my-picture.gif. Du kan inte länka till bilder som lagras på din egen dator (om det inte är en allmänt tillgänglig server) eller till bilder som lagras bakom verifieringssystem t.ex. Hotmail eller Yahoo brevlådor, lösenordsskyddade webbplatser etc.. För att visa bilden kan du antingen använda BBKoden [img] tagg eller lämplig HTML (om möjligt). Kontrollera BBKods FAQ för att lära dig hur.");
$faq[] = array("Vad är Tillkännagivelser?", "Tillkännagivelser innehäller ofta viktig information och du bör läsa dem så fort som möjligt. Meddelanden visas överst på varje sida i det forum som de är inlagt. Huruvida du kan skicka ett meddelande eller ej beror på det tillstånd som krävs, och som bestäms av administratören. Globala  Tillkännagivanden är särskilda meddelanden som visas på alla forum, inte bara var de är inlagda.");
$faq[] = array("Vad är Sticky ämnen?", "Sticky ämnen visas under några tillkännagivanden i vissa forum och endast på första sidan. De är ofta ganska viktiga så du bör läsa dem så fort det är möjligt. Som med tillkännagivanden avgör forumets administratör vilka behörigheter som krävs för att skriva Sticky ämnen i varje forum.");
$faq[] = array("Vad är Lästa ämnen?", "Lästa ämnen har fastställts på detta sätt av antingen forum moderator eller forum administratör. Du kan inte svara på lästa ämnen och om ämnet innehåller någon undersökning kommer den automatiskt att upphöra. Ämnen kan läsas av många anledningar.");

$faq[] = array("--","Användar Nivåer och Grupper");
$faq[] = array("Vad är Administratörer?", "Administratörer är personer som har den högsta nivån av kontroll över hela forumet. Dessa personer kan styra alla aspekter av forum operationer som kan inbegripa tillstånd, förbud mot användare, skapa användargrupper eller moderatorer, etc.. De har också full moderator kapacitet i alla forum.");
$faq[] = array("Vad Är Moderatorer?", "Moderatorer är individer (eller grupper av individer) vars jobb är att sköta driften av forumet från dag till dag. De har rätt till att redigera eller ta bort inlägg och läsa, låsa upp, flytta, radera och dela inlägg i forumet de modererar. Generellt är moderatorer till för att förhindra att människor hamnar <i>utanför-ämnet</i> eller gör inlägg som är kränkande eller stötande material.");
$faq[] = array("Vad Är Användargrupper?", "Användargrupper är ett sätt på vilket forumets administratörer kan gruppera användare. Varje användare kan tillhöra flera grupper (detta skiljer sig från de flesta andra forum) och varje grupp kan tilldelas individuella åtkomsträttigheter. Det gör det enkelt för administratörer att skapa flera användare som moderatorer för ett forum, eller att ge dem tillgång till ett privat forum, etc.");
$faq[] = array("Hur går jag med i en Användargrupp?", "För att ansluta sig till en användargrupp klicka på användargrupps länken i sidhuvudet (beroende på mall design) och du kan då se alla användargrupper. Inte alla grupper är <i>öppen tillgång</i> -- vissa är stängda och vissa kan ha dolda medlemskap. Om forumet är öppet kan du begära att få delta genom att klicka på knappen. Användargruppens moderator måste godkänna din ansökan; de kan fråga varför du vill gå med i gruppen. Vänligen besvära inte en grupp moderator om de vänder er begäran nedåt - de kommer att ha sina skäl.");
$faq[] = array("Hur blir jag en Användargrupps Moderator?", "Användargrupper är ursprungligen skapade av en forum administratör som också tilldelar forum moderatorer. Om du är intresserad av att skapa en användargrupp bör din första kontakt vara administratören, så försök att skicka dem ett privat meddelande.");

$faq[] = array("--","Privata Meddelanden");
$faq[] = array("Jag kan inte skicka privata meddelanden!", "Det finns tre skäl till detta; du är inte registrerad och/eller inte inloggad, forumet har avaktiverat privata meddelandesystemet för hela forumet, eller har forum administratören hindrat dig personligen från att skicka meddelanden. Om det är det senare fallet bör du fråga administratören varför.");
$faq[] = array("Jag får fortfarande oönskade privata meddelanden!", "I framtiden kommer vi att lägga en ignoreringslista till det privata meddelandesystemet. Tills vidare, om du fortfarande får oönskade privata meddelanden från någon, informera forumets administratör - de har makten att förhindra en användare från att skicka privata meddelanden till alla.");
$faq[] = array("Jag har fått ett spam eller kränkande mail från någon i detta forum!", "Vi beklagar att så är fallet. E-post formuläret i detta forum innehåller garantier för att försöka spåra användare som skickar sådana inlägg. Du bör e-posta forum administratören en fullständig kopia av e-postmeddelandet du fick och det är mycket viktigt att ta med rubrikerna (detta listar detaljer om användaren som skickat e-post meddelandet). De kan då vidta åtgärder.");

$faq[] = array("--","Avatar Generator");
$faq[] = array("Vad är det?", "<strong>Avatar Generator</strong> används för att skapa avatarer som användare sedan kan använda som sin avatar");
$faq[] = array("Var kan jag hitta den?", "Du kan behöva logga in för att använda avatar generator. Den ligger i din profil i avatar avsnittet.");
$faq[] = array("Hur sparar jag den avatar jag har gjort?", "Det bör finnas en länk under avataren som har genererats, och länken säger <strong>Klicka här för att lägga till denna i din profil avatar</strong> När du väl klickar här kommer du att få ett meddelande som informerar dig om förändringen.");

$faq[] = array("--","Foto Album");
$faq[] = array("Hur får jag tillgång till Foto Album?", "Enkelt, använd länken 'Foto Album' i navigerings menyn. Detta tar dig till huvud Foto Album katalogen där alla offentliga Foto Album visas. Du kan också öppna ett individuellt Personligt Foto Galleri genom att klicka på länken 'Användares Personliga Gallerier' nedanför Public Kategorier.");
$faq[] = array("Hur laddar jag upp en bild till ett Foto Album?", "När du väl är på huvud Foto Albumets index sida, välj något av de 'Offentliga Kategorierna' eller 'Användares Personliga Gallerier'. Du bör nu se en knapp där det står 'Ladda upp Bild' högst upp och längst ner på sidan. Klicka på knappen och följ instruktionerna på följande sida.");
$faq[] = array("Vad är den maximala filstorleken, maximala bildbredden och högsta bildhöjd som är tillåten?", "Dessa inställningar visas på Ladda upp Bild sidan.  Forumets administratör sätter en övre gräns för filstorlek, definierar filtillägg och andra saker för uppladdade bilder i Album .");
$faq[] = array("Vilket format måste min bild vara i?", "Dessa inställningar visas på 'Ladda upp Bild' sidan. Forumets administratör sätter en övre gräns för filstorlek, definierar filtillägg och andra saker för uppladdade bilder i Album.");
$faq[] = array("Jag kan fortfarande inte få min bild att ladda upp; Jag får hela tiden ett felmeddelande!", "Gå tillbaka till 'Ladda upp Bild' sidan och se till att du följer alla de instruktioner där. Filen du försöker ladda upp kan vara större än den maximala filstorleken som är tillåten, du kanske försöker att lägga upp en bild som inte passar de mått som anges, du kanske försöker att lägga upp en bild i ett format som inte finns, eller har du helt enkelt glömt att fylla i de nödvändiga fälten för bilder så att de kan laddas upp korrekt.");
$faq[] = array("Jag gjorde ett misstag i titeln och/eller beskrivning av min bild. Vad kan jag göra?", "När du tittar i ett album, finns det flera alternativ för en användare. Om Forumets administratör har tillåtit det, så hittar du länken 'Redigera' under varje miniatyrbild och som tillåter dig att ändra informationen när som helst.");
$faq[] = array("Hur tar jag bort en bild?", "När du tittar i ett album, finns det flera alternativ för användaren. Om Forumets administratör har tillåtit det, så hittar du länken 'Radera' under varje miniatyrbild och som tillåter dig att flytta vilket bild som helst av dina egna.");
$faq[] = array("Jag skulle vilja låta någon veta hur mycket jag gillar eller ogillar deras bild. Hur gör jag det?", "När du tittar på ett album eller en bild, finns det flera alternativ tillgängliga för en användare. Om Forumets administratör har tillåtit det, så hittar du länken 'Värdera' och 'Kommentera' under varje miniatyrbild eller bild som gör att du kan göra detta på ett par olika sätt när som helst.");

$faq[] = array("--","Bilagor");
$faq[] = array("Hur lägger jag till en bilaga?", "Du kan lägga till bilagor när du lägger upp en ny post. Du bör se en <i>Lägg till Bilaga</i> formuläret nedan nedanför huvud meddelande rutan. När du klickar på <i>Bläddra...</i> knappen öppnas standard dialog fönstret för din dator att öppna. Bläddra till den fil du vill bifoga, markera den och klicka på OK, öppna eller dubbelklicka enligt din smak och/eller det korrekta förfarandet för din datorn. Om du väljer att lägga till en kommentar i <i>Fil Kommentar</i> fältet kommer den här kommentaren att användas som en länk till den bifogade filen. Om du inte har lagt en kommentar kommer filnamnet i sig själv att användas för att länka till bilagan. Om forumets administratör har tillåtit det kommer du att kunna ladda upp flera bilagor genom att följa samma förfarande som beskrivits ovan tills du når max tillåtna antal bilagor för varje post.<br/><br/>Forumets administratör sätter en övre gräns för filstorlek, definierar filtillägg och andra saker för bilagor i forumet. Var medveten om att det är ditt ansvar att dina bilagor följer forumets acceptans för användning, och att de kan tas bort utan förvarning.<br/><br/>Observera att forumets ägare, webmaster, administratör eller moderatorer inte kan och kommer inte att ta ansvar för förlust av data.");
$faq[] = array("Hur lägger jag till en bilaga efter den inledande postningen?", "Om du vill lägga till en bilaga efter det inledande meddelandet behöver du redigera ditt inlägg och sedan följa beskrivningen ovan. Den nya bilagan kommer att läggas till när du klickar på <i>Skicka</i> och läggs då till det redigerade inlägget.");
$faq[] = array("Hur tar jag bort en bilaga?", "Om du vill ta bort bifogade filer behöver du redigera ditt inlägg och sedan klicka på <i>Radera Bilagor</i> bredvid den bilaga som du vill ta bort i <i>Postade Bilagor</i> boxen. Bilagan kommer att tas bort när du klickar på <i>Skicka</i> att lägga till det redigerade inlägget.");
$faq[] = array("Hur uppdaterar jag en fil kommentar?", "För att uppdatera en fil kommentar måste du ändra ditt inlägg, redigera texten i <i>Fil Kommentar</i> fältet och klicka på <i>Uppdatera Kommentar</i> knappen bredvid fil kommentaren du vill uppdatera i <i>Postade Bilagor</i> boxen. Fil kommentaen kommer att uppdateras när du klickar på <i>Skicka</i> att lägga till det redigerade inlägget.");
$faq[] = array("Varför är inte min bilaga synlig i inlägget?", "Mest sannolikt är att filen eller tillägget inte längre är tillåtna på forumet, eller har en moderator eller administratör strukit den för att inte komma i konflikt med forumets användningsvillkor.");
$faq[] = array("Varför kan jag inte bifoga filer?", "På vissa forum är tillläggning av bilagor begränsat till vissa användare eller grupper. För att bifoga filer kan du behöva särskilt tillstånd, bara forum moderator och forum admins kan bevilja denna tillgång, du bör kontakta dem.");
$faq[] = array("Jag har nödvändiga tillstånd, varför kan jag inte bifoga filer?", "Forumets administratör sätter en övre gräns för filstorlek, filtillägg och andra saker för bilagor i forumet. En moderator eller administratör kan ha förändrat ditt tillstånd, eller avbrytet bilagor i särskilda forum. Du bör få en förklaring på felmeddelande när du försöker lägga till en bilaga, om inte kan du kontakta moderator eller administratör.");
$faq[] = array("Varför kan jag inte radera bifogningar?", "På vissa forum, kan radering av bilagor vara begränsade till vissa användare eller grupper.Om du vill ta bort bifogade filer kan du behöva särskilt tillstånd, bara forum moderator och forum admins kan bevilja denna tillgång, du bör kontakta dem.");
$faq[] = array("Varför kan jag inte visa/ladda ner bilagor?", "På vissa forum är visning/nerladdning av bilagor begränsat till vissa användare eller grupper. För att visa/ladda ner bilagor kan du behöva särskilt tillstånd, bara forum moderator och forum admins kan bevilja denna tillgång, du bör kontakta dem.");
$faq[] = array("Vem kontaktar jag om olagliga eller möjligen olagliga bilagor?", "Du bör kontakta administratören för detta forum. Om du inte kan hitta vem detta är bör du först kontakta en av forumets moderatorer och fråga dem vem du ska i sin tur kontakta. Om du fortfarande inte får något svar bör du kontakta ägaren av domänen (gör en whois lookup) eller, om detta körs på en gratistjänst (t.ex. yahoo, free.fr, f2s.com, osv.), förvaltningen eller missbruks avdelningen av den servicen. Vänligen notera att phpBB Gruppen inte har någon som helst kontroll och kan inte på något sätt hållas ansvariga över hur, var eller av vem detta forum används. Det är helt meningslöst att kontakta phpBB Gruppen i förhållande till något juridiskt (upphöra och avstå, ansvarig kränkande kommentarer, osv.) om frågan inte är direkt relaterade till phpbb.com webbsida eller diskret programvara av phpBB själv. Om du e-postar phpBB Gruppen om en tredje part som använder sig av denna mjukvara så kan du vänta ett kort och koncist svar eller inga svar alls.");

$faq[] = array("--","Nerladdnings ADV");
$faq[] = array("Var hittar jag Nedladdningar?", "Länkar till Nerladdningar finns i forumets navigering och portalens navigering. Direktlänk: [<a href=\"downloads.php\">Nerladdningar</a>]");
$faq[] = array("Vad betyder <img border=\"0\" src=\"" . $images['Dl_blue'] . "\" alt=\"\" title=\"\" />?", "Ingen nerladdning möjlig. Den totala trafficen som fastställts av administrationen för varje nedladdning eller den visade kategorin som används för denna månad.");
$faq[] = array("Vad betyder <img border=\"0\" src=\"" . $images['Dl_red'] . "\" alt=\"\" title=\"\" />?", "Ingen nerladdning möjlig. Detta kan vara:<br />- Nedladdningen är blockerad av en administratör.<br />- Användaren är inte inloggad men nerladdning är endast tillåtet för registrerade användare.<br />- Användaren har inte tillräckligt med traffic för att ladda ner denna fil.<br />- Administratören har angivet ett minsta antal inlägg, användaren har inte det.<br />- Den traffic gräns som är satt för denna fil är komplett använd.");
$faq[] = array("Vad betyder <img border=\"0\" src=\"" . $images['Dl_grey'] . "\" alt=\"\" title=\"\" />?", "Extern Källa. Nedladdningen kommer att startas av en extern server. Detta kommer att hanteras som <img border=\"0\" src=\"" . $images['Dl_green'] . "\" alt=\"\" title=\"\" />. Den usertraffic och den totala trafficen kommer inte att minska.");
$faq[] = array("Vad betyder <img border=\"0\" src=\"" . $images['Dl_white'] . "\" alt=\"\" title=\"\" />?", "Likt <img border=\"0\" src=\"" . $images['Dl_green'] . "\" alt=\"\" title=\"\" /> användar traffic kommer inte att minska. Men bara inloggade användare kan ladda ner gratis. Den totala trafficen kommer att gå ner.");
$faq[] = array("Vad betyder <img border=\"0\" src=\"" . $images['Dl_yellow'] . "\" alt=\"\" title=\"\" />?", "Nerladdning möjlig med restriktioner. Nedladdningen är bara möjligt för registrerade användare. Användaren måste vara inloggad. Filstorleken kommer att dras från din traffic och subtraheras från den totala trafficen.");
$faq[] = array("Vad betyder <img border=\"0\" src=\"" . $images['Dl_green'] . "\" alt=\"\" title=\"\" />?", "Gratis Nerladdning. Nedladdningen kommer inte att begränsas. Denna fil kan också laddas ner av gäster. Du behöver inte vara inloggad. Din traffic kommer inte att minskas, men den totala trafficen kommer att gå ner.");
$faq[] = array("Varför kan jag inte ladda ner någon fil?", "Detta kan ha många orsaker. Titta under <img border=\"0\" src=\"" . $images['Dl_blue'] . "\" alt=\"\" title=\"\" /> och <img border=\"0\" src=\"" . $images['Dl_red'] . "\" alt=\"\" title=\"\" />.");
$faq[] = array("Hur och när får jag ny traffic till mitt konto?", "Efter den första inloggningen kommer användaren att få en tidsstämpel. Varje första dag i en månad kommer användaren att ange nerladdningar, trafficen kommer då att uppdateras. Fråga din administratör hur mycket du kommer att få.");
$faq[] = array("Jag vill hämta ännu en fil, men jag har inte någon traffic kvar?", "I detta fall fråga administratören. Endast han kan besluta att öka användar traffic före kontot får automatiskt ny trafik nästa månad.");
$faq[] = array("Hur kan jag värdera Nedladdningar?", "Bakom varje nedladdning i en kategori eller detalj visning hittar du ett avsnitt för värdering.<br />Genom att klicka på \"Värdera\" kan en registrerad användare betygsätta nerladdningar från 1 poäng (mycket dåligt) till 10 poäng (mycket bra). Du kan värdera en nedladdning endast en gång.");

$faq[] = array("--","Sammandrag ");
$faq[] = array("Vad Är Sammandrag?", "Sammandrag är e-postmeddelanden som skickas till dig regelbundet med sammanfattning av inlägg som görs här. Veckovis eller daglig sammandrag finns tillgängliga.");
$faq[] = array("Varför skulle jag vilja ha ett sammandrag?", "Det gör livet lättare. Du behöver inte uttryckligen besöka webbplatsen för att se vilka samtal som pågår här. Bara läs ditt sammandrag och om det finns någon fråga som verkar intressant, klicka på den i ditt e-postprogram och börja deltaga! Avsluta prenumerationen när som helst.");
$faq[] = array("Hur ofta skickas sammandrag?", "De kan skickas varje dag eller varje vecka. Veckans sammandrag sänds på Söndagar.");
$faq[] = array("När skickas sammandrag?", "Du bestämmer den timme du vill få sammandraget. Oavsett vilken tid du väljer kommer du alltid att få de senaste nyheterna så välj en tid som passar din livsstil.");
$faq[] = array("Vilken tidsperiod omfattas sammandraget av?", "Antingen 24 timmar eller 7 dagar, beroende på om du valde ett dags-eller veckovis sammandrag. Meddelanden som är äldre än detta kommer inte att skickas. Dessutom om du vill kan du välja att inte se meddelanden sedan du senast loggade in, om du nyligen besökte. Du kan även filtrera bort dina egna meddelanden.");
$faq[] = array("Anta att jag inte vill ha sammanfattningar av varje meddelande här. Kan jag vara selektiv?", "Ja. Du kan välja forumet eller forum som intresserar dig. Som standard kommer du att få meddelanden från alla forum som du har tillgång till.");
$faq[] = array("Vilka e-postmeddelande format finns tillgängliga?", "Vi kan skicka dig HTML eller text. Om ditt e-postprogram inte kan hantera HTML (mycket ovanligt i dessa dagar) föreslår vi HTML. Öppen text sammandrag ser ganska vanliga ut och är svårare att använda. Det är typ av oformaterad text.");
$faq[] = array("Får jag hela texten i sammandrag?", "Som standard får du de första 150 tecknen i texten, eller så kan du välja att inte se något av meddelandetexten och bara se rubriken på ämnet i stället. Du kan välja meddelande inslag inklusive de första 50, 100, 150, 300 eller 600 tecken, eller hela texten i meddelandet (upp till 32000 tecken). Allt utöver det du anger kommer att trunkeras. Vi rekommenderar att behålla standardmeddelandets längd annars kommer ditt sammandrag att bli så stort att det blir oanvändbart. Vi har också hört att mycket stora sammandrag kan avvisas av din ISP eller sätta dig över din servers lagringsutrymme. Ett utdrag reducerar bandbredd och brukar allt som behövs. Varför? Eftersom varje meddelande har en lämplig länk som tar dig till ämnet eller meddelandet av intresse.");
$faq[] = array("Hur kommer jag igång?", "Klicka på Sammandrags länken i nav länk blocket eller om du föredrar det kan du klicka här: <a href=\"./digests.php\">Sammandrag</a>.");
$faq[] = array("Kan jag ta bort Prenumeration?", "Självklart! Bara gå till samma sida och välj \"Ingen\" för \"Typ av Sammandrag Wanted\". Sedan skicka formuläret. Din prenumeration kommer att upphöra omedelbart.");
$faq[] = array("Är sammandrag kommersiellt gratis?", "Självklart. Det finns inga störande annonser och det kommer inte att vara någon på vår webbplats.");
$faq[] = array("Är min personliga integritet skyddad?", "Ja, ditt sammandrag skickas till dig och ingen annan till den e-postadress du angav i din profil. Tänk på sammandraget som en specialutgåva av en tidning anpassade just för dig. Någon annan kommer sannolikt att få ett helt annat sammandrag.");


$faq[] = array("--","Oläst Post Information 2 Databas (OPI2DB)");
$faq[] = array("Vad är skillnaden mellan standard cookie systemet och OPI2DB System?", "Cookien system är standard i phpBB2 forums. När du läser ett meddelande, lagras information i en cookie på din dator som innehåller information att du har läst inlägget. Den så snarare största nackdelen med detta system är att du tappar den markerade lästa/olästa information när du stänger din webbläsare. OPI2DB systemet lagrar inte den informationen som cookie på
 datorn, men separat i databasen.");
$faq[] = array("Vad är pro och contras för cookie system?", "<strong>Fördel:</strong> Med större forum har det normala cookie systemeten snabbare sido laddning än OPI2DB systemet, eftersom detta system måste ladda information om läs meddelanden från databasen. En ytterligare fördel är att uppgifterna kommer att lagras under många månader, när du inte raderar data från din maskin. Detta är intressant för användare som endast läser forum var 2 månad.<br /><strong>Nackdel:</strong> Den största nackdelen hittills med detta system är att du automatiskt markerar alla inlägg som lästa genom att stänga webbläsaren. En annan nackdel är att redigerade inlägg inte blir markerade som olästa igen och därför får de ingen uppmärksamhet mer.");
$faq[] = array("Vad är pro och contras för OPI2DB system?", "<strong>Fördel:</strong> Olästa inlägg förblir fortfarande olästa, om någon stänger webbläsaren behöver du  inte läsa alla nya inlägg på en gång. Inlägg kan också märkas som lästa för en tid av " . (!empty($unread_days) ? $unread_days : 0) . " med OPI2DB systemet. Forum som inte är intressanta för dig, kan markeras som \"märkes permanent lästa\", tills du ändrar alternativet. Redigerad bidrag har markerats som olästa med noteringen \"Redigerade\" och dessutom har en annan färg för att skilja dem från normala olästa meddelanden. En ny sökfunktion gör det möjligt att endast söka olästa och redigerade bidrag. När administratören har aktiverat för att visa redigerade bidrag i början av ämnen, kommer redigerade bidrag att visas på första raden av ämnet.<br /><strong>Nackdel:</strong> Vid större forum med många inlägg och användare kan det ta längre tid att ladda sidan. Informationen om ett bidrag som fortfarande lästes, lagras endast under en viss tidsperiod, och efteråt kommer inlägg att automatiskt markeras som lästa. Standard tidsperioden är satt till 30 dagar. Men detta kan variera beroende på inställningarna från din Admin.");
$faq[] = array("Jag kan inte se någon stans i min profil, där jag kan välja att välja mellan cookie eller UPI2DB system", "Om du inte kan se alternativen för OPI2DB systemet har admin permanent aktiverat eller inaktiverat systemet. I detta fall har du inte möjlighet att byta det här alternativet.");
$faq[] = array("Vilka villkor kan administratören ställa?", "Som standard tillåter OPI2DB systemet Admin att välja hur mycket inlägg som en användare måste ha för att använda systemet och/eller hur länge användaren måste vara registrerad innan systemet kommer att aktiveras.");
$faq[] = array("Hur jag än försöker, kan jag inte markera sticky inlägg eller meddelanden som lästa!", "Sticky inlägg och meddelanden måste läsas! De kan inte markeras som lästa inom funktionerna \"Markera alla forum/bidrag som läst\" eller \"Visa olästa inlägg\"!");
$faq[] = array("Jag måste återmarkera alla " . (!empty($unread_days) ? $unread_days : 0) . " dagar ett ämne som \"permanent läst\"!", "Det är hur det måste vara och du kan inte ändra detta. Vi var tvungna att göras en kompromiss för att säkerställa att systemet inte skulle vara för långsamt.");
$faq[] = array("Hur ställer jag in ett forum till \"permanent läst\"?", "Klicka bara på bilden framför forumets namn. När detta är gjort, ska bilden ändras.");
$faq[] = array("Hur ställer jag in ett ämne till \"permanent läst\"?", "Klicka bara på bilden framför ämnets namn. När detta är gjort, ska bilden ändras och ämnet kommer att flytta till den sista positionen i ämneslistan. Alternativt kan du klicka på \"ämne permanent markerat som läst\" längst ner på sidan.");
$faq[] = array("Jag kan inte markera sticky inlägg och meddelanden som \"permanent läst\"!", "Sticky inlägg och meddelanden får inte vara satta till \"permanent läst\", eftersom du kanske missar mycket viktig information!");
$faq[] = array("Jag markerade ett forum som \"permanent läst\", men nu dyker en ny post upp!", "När någon skickar en sticky post eller ett meddelande, forumet som är märkt som \"permanent läst\" kommer att återställas till standard. Detta är viktigt, för att undvika missade och saknade viktiga sticky inlägg eller meddelanden.!");
$faq[] = array("Hur kan jag markera ett bidrag för att hitta det igen senare och lättare?", "Inom varje bidrag hittar du en knapp i bidrags titeln som du kan använda för att markera ett bidrag. Inlägg äldre än " . (!empty($unread_days) ? $unread_days : 0) . " dagar eller bidrag, som skrevs innan du registrerade dig på det här forumet, kan inte märkas.");
$faq[] = array("Hur ställer jag in ett redan läst bidrag till \"oläst\" igen?", "På varje post finns en länk nedanför titeln på bidraget. Med denna länk kan du markera alla inlägg som postas eller redigeras efter det här inlägget, som ny eller redigerad.");
$faq[] = array("Varför kan jag inte märka några bidrag?", "Bidrag, som är märkta som \"permanent läst\" i ett forum eller bidrag eller som skrevs innan du registrerade dig på det här forumet, kan inte märkas. Inlägg äldre än " . (!empty($unread_days) ? $unread_days : 0) . " dagar, kan inte märkas.");
$faq[] = array("Blir märkta bidrag märkta för evigt?", "Nej, alla märkningar du anger, kommer att tas bort automatiskt efter " . (!empty($del_mark) ? $del_mark : 0) . " dagar, där du anger märket.");
$faq[] = array("Vad betyder MAR?", "Detta är en förkortning för \"Markera alla lästa\"");


$faq[] = array("--","phpBB 2 Frågor");
$faq[] = array("Vem skrev denna diskussionstjänst?", "Denna programvara (i dess omodifierade form) är producerad, släppt och är upphovsrättsskyddat <a href=\"http://www.phpbb.com/\" target=\"_blank\">phpBB Group</a>. Den finns tillgänglig under GNU General Public License och för fritt distribueras, se länk för mer information");
$faq[] = array("Varför är inte X funktion tillgänglig?", "Denna programvara har skrivits av och licensierat av phpBB Gruppen. Om du anser att en funktion bör läggas till besök då phpbb.com hemsida och se vad phpBB Gruppen har att säga. Vänligen posta inte funktions förfrågningar till forumet på phpbb.com, eftersom Gruppen använder SourceForge för att hantera uppdrag av nya funktioner. Vänligen läs genom forumen och se om eventuella funktioner redan har tagits upp där och om följ det förfarande som ges där.");
$faq[] = array("Vem ska jag kontakta om missbruk och/eller juridiska frågor relaterade till detta forum?", "Du bör kontakta administratören för detta forum. Om du inte kan hitta vem det är, bör du först kontakta en av forumets moderatorer och fråga dem vem du ska i sin tur kontakta. Om du fortfarande inte fått något svar bör du kontakta ägaren av domänen (gör en whois lookup) eller, om detta körs på en gratistjänst (t.ex. yahoo, free.fr, f2s.com, osv.), förvaltningen eller missbruks avdelningen av denna service. Vänligen notera att phpBB Gruppen inte har någon som helst kontroll och kan inte på något sätt hållas ansvariga över hur, var eller av vem detta forum används. Det är helt meningslöst att kontakta phpBB Gruppen i förhållande till en juridisk (upphöra och avstå, ansvarig, kränkande kommentarer, osv.) om frågan inte är direkt relaterade till phpbb.com webbplats eller diskret programvara av phpBB själv. Om du e-postar phpBB Gruppen om en tredje part som använder sig av denna mjukvara då kan du vänta ett kort och koncist svar eller inga svar alls.");


$faq[] = array("--", "Om Icy Phoenix");
$faq[] = array("Vad är Icy Phoenix?", "Icy Phoenix är ett CMS (Content Management System) som tillåter användaren att enkelt skapa dynamisk webbplats med flera inbyggda funktioner: Forum, Portal, anpassningsbara sidor och block, nedladdningar, fotogalleri och mycket mer.");
$faq[] = array("Vem skrev denna mjukvara?", "Mjukvaran är baserat på phpBB som är utgivna under GNU General Public License, så Icy Phoenix måste släppas under samma licens, och detta innebär att man fritt kan modifiera och distribuera phpBB käll filer från varandra, de flesta av de filer är direkt kodade eller modifierade av Mighty Gorgon och <a href=\"http://www.icyphoenix.com/\" target=\"_blank\">Icy Phoenix Personal</a>. En inte uttömmande förteckning över de som bidragit till det här projektet kan hittas här: <a href=\"http://www.icyphoenix.com/credits.php\" target=\"_blank\">Icy Phoenix Krediter</a>.");
$faq[] = array("Vem ska jag kontakta om missbruk och/eller juridiska frågor relaterade till detta forum?", "Du bör kontakta administratören för detta forum. Om du inte kan hitta vem det är, bör du först kontakta en av forumets moderatorer och fråga dem vem du ska i sin tur kontakta. Om du fortfarande inte fått något svar bör du kontakta ägaren av domänen (gör en whois lookup) eller, om detta körs på en gratistjänst (t.ex. yahoo, free.fr, f2s.com, osv.), förvaltningen eller missbruks avdelningen av denna service. Vänligen notera att phpBB Gruppen inte har någon som helst kontroll och kan inte på något sätt hållas ansvariga över hur, var eller av vem detta forum används. Det är helt meningslöst att kontakta phpBB Gruppen i förhållande till en juridisk (upphöra och avstå, ansvarig, kränkande kommentarer, osv.) om frågan inte är direkt relaterade till phpbb.com webbplats eller diskret programvara av phpBB själv. Om du e-postar phpBB Gruppen om en tredje part som använder sig av denna mjukvara då kan du vänta ett kort och koncist svar eller inga svar alls.");


?>