<?php
/**
*
* @package Icy Phoenix
* @version $Id: lang_blocks.php 49 2008-09-15 20:00:00Z TheSteffen $
* @copyright (c) 2008 Icy Phoenix
* @license http://opensource.org/licenses/gpl-license.php GNU Public License
*
*/

/**
*
* @Extra credits for this file
* TheSteffen, KugeLSichA, Tom
*
*/

$lang['Title_ads'] = 'Ads';
$lang['Title_album'] = 'Galerie';
$lang['Title_birthdays'] = 'Geburtstage';
$lang['Title_center_downloads'] = 'Downloads';
$lang['Title_donate'] = 'Spenden';
$lang['Title_dyn_menu'] = 'Quick Links';
$lang['Title_forum'] = 'News';
$lang['Title_forum_attach'] = 'News';
$lang['Title_forum_list'] = 'Forum Liste';
$lang['Title_global_header'] = 'Global Header';
$lang['Title_global_header_simple'] = 'Global Header Simple';
$lang['Title_gsearch'] = 'Google Suche';
$lang['Title_gsearch_hor'] = 'Google Suche';
$lang['Title_kb'] = 'Wissensdatenbank';
$lang['Title_links'] = 'Links';
$lang['Title_menu'] = 'Forum Navigation';
$lang['Title_nav_header'] = 'Header';
$lang['Title_nav_links'] = 'Site Map';
$lang['Title_nav_logo'] = 'Logo';
$lang['Title_news'] = 'News';
$lang['Title_news_archive'] = 'News Archiv';
$lang['Title_news_posters'] = 'News Posters';
$lang['Title_online_users'] = 'Wer ist Online';
$lang['Title_online_users2'] = 'Wer ist Online';
$lang['Title_paypal'] = 'PayPal';
$lang['Title_poll'] = 'Umfrage';
$lang['Title_random_attach'] = 'Zufällige Anhänge';
$lang['Title_random_topics'] = 'Zufällige Themen';
$lang['Title_random_topics_ver'] = 'Zufällige Themen';
$lang['Title_recent_articles'] = 'Neuste Artikel';
$lang['Title_recent_topics'] = 'Neueste Themen';
$lang['Title_recent_topics_wide'] = 'Neueste Themen';
$lang['Title_referers'] = 'Referrers';
$lang['Title_rss'] = 'RSS';
$lang['Title_search'] = 'Suche';
$lang['Title_sec_menu'] = 'Extra-Menue';
$lang['Title_shoutbox'] = '<a href="shoutbox_max.' . $phpEx . '?sid=' . $userdata['session_id'] . '">Shoutbox</a>';
$lang['Title_staff'] = 'Team';
$lang['Title_statistics'] = 'Statistik';
$lang['Title_style'] = 'Style';
$lang['Title_top_downloads'] = 'Top Downloads';
$lang['Title_top_posters'] = 'Top Poster';
$lang['Title_user_block'] = 'Benutzerblock';
$lang['Title_users_visited'] = 'Aktive Benutzer';
$lang['Title_visit_counter'] = 'Besuchszähler';
$lang['Title_welcome'] = 'Willkommen';
$lang['Title_wordgraph'] = 'Tags';

$lang['Advanced_GSearch'] = 'Erweiterte Google Suche';
$lang['Advanced_search'] = 'Erweiterte Suche';
$lang['Album'] = 'Galerie';
$lang['All_News_Archives'] = 'Alle News Archive';
$lang['All_News_Categories'] = 'Alle News Kategorien';
$lang['Articles'] = 'Artikel';
$lang['Articles_time'] = 'Geschrieben in';
$lang['Articles_options'] = 'Optionen';
$lang['Article_Reply'] = 'Schreibe einen Kommentar';
$lang['Article_Print'] = 'Drucke diesen Artikel';
$lang['Article_Email'] = 'An einen Freund weiterleiten';
$lang['Censor'] = 'Zensieren';
$lang['Click_to_join_chat'] = 'Klicke hier um zum Chat zu gelangen';
$lang['Comments'] = 'Kommentare';
$lang['Credits'] = 'Mods und Credits';
$lang['Day_users'] = '%d registrierte Benutzer haben das Forum in den letzten %d Stunden besucht.';
$lang['Disable_BBCode_post'] = 'BBCode in diesem Beitrag deaktivieren';
$lang['Disable_HTML_post'] = 'HTML in diesem Beitrag deaktivieren';
$lang['Dls'] = 'Downloads';
$lang['Donate_Funds'] = 'Spenden';
$lang['GSearch'] = 'Suche';
$lang['GSearch2'] = 'Google Suche:';
$lang['GSearch_At'] = 'Suche bei';
$lang['Guest'] = 'Gast';
$lang['Guest_user_total'] = '%d Gast';
$lang['Guest_users_total'] = '%d Gäste';
$lang['Guest_users_zero_total'] = 'keine Gäste';
$lang['Hidden_user_total'] = '%d verstecker und ';
$lang['Hidden_users_total'] = '%d versteckte und ';
$lang['Hidden_users_zero_total'] = 'kein versteckter und ';
$lang['How_Many_Chatters'] = 'Es sind zur Zeit <b>%d</b> Benutzer im Chat.';
$lang['Kb_name'] = 'Wissensdatenbank';
$lang['IP_info'] = 'IP Information';
$lang['Login_to_join_chat'] = 'Bitte melde dich an, um zum Chat zu gelangen.';
$lang['Login_to_vote'] = 'Du musst dich anmelden, um Abstimmen zu können.';
$lang['Lookup_IP'] = 'IP-Adresse nachschlagen';
$lang['New_donations'] = 'Neue Spenden';
$lang['New_downloads'] = 'Neue Downloads';
$lang['News_And'] = 'und hat';
$lang['News_Archives'] = 'News Archive';
$lang['News_Categories'] = 'News Kategorien';
$lang['News_Cats'] = 'News Kategorien';
$lang['News_Comments'] = 'Kommentare';
$lang['News_Email'] = 'Thema per E-Mail versenden';
$lang['News_Print'] = 'Thema ausdrucken';
$lang['News_Reply'] = 'Auf diesen News Beitrag antworten';
$lang['News_Summary'] = 'Dieser News Artikel wurde';
$lang['News_Views'] = 'mal gelesen';
$lang['No_News_Cats'] = 'Es sind leider keine News Kategorien verfügbar!';
$lang['No_Pics'] = 'Keine Bilder';
$lang['No_poll'] = 'Momentan keine Umfragen';
$lang['No_topics_found'] = 'Es wurden keine Themen gefunden.';
$lang['None'] = 'Keiner';
$lang['Not_day_users'] = '%d registrierte Benutzer haben das Forum in den letzten %d Stunden <span style="color:red">NICHT</span> besucht.';
$lang['Not_found'] = 'Keine Anhänge gefunden.';
$lang['Not_rated'] = 'Nicht bewertet';
$lang['ON'] = 'am';
$lang['Online_user_total'] = 'Insgesamt ist <b>%d</b> Benutzer online: ';
$lang['Online_users_total'] = 'Insgesamt sind <b>%d</b> Benutzer online: ';
$lang['Online_users_zero_total'] = 'Insgesamt sind <b>0</b> Benutzer online:';
$lang['Other_IP_this_user'] = 'Andere IP Adressen, von denen der Benutzer geschrieben hat';
$lang['Pic_Title'] = 'Bildtitel';
$lang['Poll'] = 'Umfrage';
$lang['Post_your_comment'] = 'Kommentar schreiben';
$lang['Posted'] = 'Geschrieben';
$lang['Poster'] = 'Poster';
$lang['Posts'] = 'Beiträge';
$lang['Rating'] = ' Bewertung';
$lang['Read_Full'] = 'Alles lesen';
$lang['Record_online_users'] = 'Der Rekord liegt bei <b>%s</b> Benutzern am %s.';
$lang['Reg_user_total'] = '%d registrierter, ';
$lang['Reg_users_total'] = '%d registrierte, ';
$lang['Reg_users_zero_total'] = 'keine registrierten, ';
$lang['Register_new_account'] = 'Du hast noch kein Benutzer-Konto?<br />Jetzt kostenlos %sregistrieren%s!';
$lang['Registered_users'] = 'Registrierte Benutzer:';
$lang['Remember_me'] = 'Automatisch einloggen';
$lang['Save_Topic'] = 'Das Thema als Datei speichern';
$lang['Shout_censor'] = 'Shout entfernt!';
$lang['Shout_refresh'] = 'Aktualisieren';
$lang['Shout_text'] = 'Dein Text';
$lang['Shoutbox_date'] = 'D G:i \\s\c\h\r\i\e\b ';
$lang['SH_Visit_counter_statement'] = 'This site had <b>%d</b> visitors in total since %s';
$lang['Tell_Friend'] = 'Als E-Mail an einen Freund senden';
$lang['This_posts_IP'] = 'IP Adresse für diesen Eintrag';
$lang['Top_downloads'] = 'Top Downloads';
$lang['Total_votes'] = 'Stimmen insgesamt';
$lang['Users_this_IP'] = 'Benutzer, die von dieser IP Adresse geschrieben haben';
$lang['View'] = 'Ansehen';
$lang['View_comments'] = 'Zeige Kommentare';
$lang['View_complete_list'] = 'Zeige komplette Liste';
$lang['Visit_counter'] = 'Besuchszähler';
$lang['Visit_counter_statement'] = 'Diese Seite wurde <b>%d</b> mal aufgerufen seit %s';
$lang['Vote'] = 'Abstimmen';

$lang['donated_by'] = 'gespendet von';
$lang['search'] = 'Suche';
$lang['search2'] = 'Suche:';
$lang['search_at'] = 'Suche bei';
$lang['total_topics'] = ' Insgesamt <b>%s</b> Themen';


// Blocks Config
/*
$lang['cms_var_'] = '';
$lang['cms_option_'] = '';
$lang['cms_value_'] = '';
*/

$lang['cms_var_kb_cat_id'] = 'Kategorie ID';
$lang['cms_var_kb_cat_id_explain'] = 'Wähle die Kategorie ID der Wissensdatenbank (Dynamisches Menü ID)';
$lang['cms_var_md_ads_type'] = 'Ads type';
$lang['cms_var_md_ads_type_explain'] = 'Select the ad type (H = Horizontal, V = Vertical, B = Box, 1 = Small, 2 = Medium, 3 = Large)';
$lang['cms_var_md_cat_id'] = 'Kategorie um Bilder zu empfangen von';
$lang['cms_var_md_cat_id_explain'] = '0 für alle Kategorien oder Eintragungen mit Komma abgegrenzt eingeben';
$lang['cms_var_md_col'] = 'Number of Columns';
$lang['cms_var_md_col_explain'] = 'Select the number of index columns';
$lang['cms_var_md_news_cat_id'] = 'Kategorien von der die News abgerufen werden sollen';
$lang['cms_var_md_news_cat_id_explain'] = '0 für alle Kategorien oder Eintragungen mit Komma abgegrenzt eingeben';
$lang['cms_var_md_list_forum_id'] = 'Kategorie aufgelistet werden';
$lang['cms_var_md_list_forum_id_explain'] = '0 für alle Kategorien oder Eintragungen mit Komma abgegrenzt eingeben';
$lang['cms_var_md_display_not_visit'] = 'Zeige Benutzer die noch nicht besucht haben';
$lang['cms_var_md_display_not_visit_explain'] = 'Setze Häckchen bei den Benutzer die die Seite noch nicht besucht haben';
$lang['cms_var_md_full_search_option_text'] = 'Voller Suchwahl Text';
$lang['cms_var_md_full_search_option_text_explain'] = 'Text als Standardauswahl anzeigen';
$lang['cms_var_md_gsearch_text'] = 'Search option text';
$lang['cms_var_md_gsearch_text_explain'] = 'Text displayed as the default option';
$lang['cms_var_md_gsearch_site'] = 'Search site';
$lang['cms_var_md_gsearch_site_explain'] = 'Site where the search should be performed (the url without http://)';
$lang['cms_var_md_gsearch_banner'] = 'Search site banner';
$lang['cms_var_md_gsearch_banner_explain'] = 'Banner of the site (the url without http://)';
$lang['cms_var_md_gsearch_hor_text'] = 'Search option text';
$lang['cms_var_md_gsearch_hor_text_explain'] = 'Text displayed as the default option';
$lang['cms_var_md_gsearch_hor_site'] = 'Search site';
$lang['cms_var_md_gsearch_hor_site_explain'] = 'Site where the search should be performed (the url without http://)';
$lang['cms_var_md_gsearch_hor_banner'] = 'Search site banner';
$lang['cms_var_md_gsearch_hor_banner_explain'] = 'Banner of the site (the url without http://)';
$lang['cms_var_md_hours_track_users'] = 'Anzahl der Stunden in denen die Benutzer beobachtet werden';
$lang['cms_var_md_hours_track_users_explain'] = '';
$lang['cms_var_md_ignore_auth_view'] = 'Ignore auth view permission?';
$lang['cms_var_md_ignore_auth_view_explain'] = 'Enabling this forums view permissions will be ignored (this is important if you want to use hidden forums with NONE as view permission)';
$lang['cms_var_md_links_code'] = 'Links -> Code';
$lang['cms_var_md_links_code_explain'] = 'zeige HTML code für deinen eigenen Link Button';
$lang['cms_var_md_links_own1'] = 'Links -> Eigener (Oben)';
$lang['cms_var_md_links_own1_explain'] = 'zeige deinen Link Button über den anderen Buttons';
$lang['cms_var_md_links_own2'] = 'Links -> Eigener (Unten)';
$lang['cms_var_md_links_own2_explain'] = 'zeige deinen Link Button unter den anderen Buttons';
$lang['cms_var_md_links_style'] = 'Links -> Style';
$lang['cms_var_md_links_style_explain'] = 'wähle Feste- oder Scroll-Anzeige';
$lang['cms_var_md_jumpbox_align'] = 'Alignment';
$lang['cms_var_md_jumpbox_align_explain'] = 'Select jumpbox alignment';
$lang['cms_var_md_menu_id'] = 'Menue-Block-ID';
$lang['cms_var_md_menu_id_explain'] = 'Gib die ID des Menue-Blocks ein, den du zeigen möchtest (0 = standard).';
$lang['cms_var_md_menu_show_hide'] = 'Zeige/Verberge Schalter';
$lang['cms_var_md_menu_show_hide_explain'] = 'Aktiviere Zeige/Verberge Schalter um das Menu zu verbergen (es funktioniert nur auf der linken Seite beim GLOBALEN Block!!!).';
$lang['cms_var_md_news_number'] = 'Anzahl der anzuzeigenden News';
$lang['cms_var_md_news_number_explain'] = '';
$lang['cms_var_md_news_sort'] = 'Zufällige oder neueste News?';
$lang['cms_var_md_news_sort_explain'] = '';
$lang['cms_var_md_news_length'] = 'Länge der News';
$lang['cms_var_md_news_length_explain'] = 'Anzahl der anzuzeigenden Buchstaben';
$lang['cms_var_md_news_archive_type'] = 'Zeige Archiv oder Kategorien?';
$lang['cms_var_md_news_archive_type_explain'] = 'Wähle ob Archive oder Kategorien angezeigt werden sollen';
$lang['cms_var_md_news_images_width'] = 'News Bild Breite';
$lang['cms_var_md_news_images_width_explain'] = 'Wähle Bild Breite in Pixel oder Prozent';
$lang['cms_var_md_news_forum_id'] = 'News Forum-ID(s)';
$lang['cms_var_md_news_forum_id_explain'] = 'mit Komma abgegrenzt';
$lang['cms_var_md_news_length'] = 'Länge der News';
$lang['cms_var_md_news_length_explain'] = 'Anzahl der angezeigten Zeichen (gib 0 ein für alle)';
$lang['cms_var_md_news_posters_page_link'] = 'Page Link';
$lang['cms_var_md_news_posters_page_link_explain'] = 'The link to the page which contains news archive (i.e. <b>index.php</b>)';
$lang['cms_var_md_news_posters_sort'] = 'Sort';
$lang['cms_var_md_news_posters_sort_explain'] = 'Select the sort method';
$lang['cms_var_md_news_posters_avatar'] = 'Show Avatars';
$lang['cms_var_md_news_posters_avatar_explain'] = '';
$lang['cms_var_md_num_new_downloads'] = 'Neue Downloads';
$lang['cms_var_md_num_new_downloads_explain'] = 'Anzahl der anzuzeigenden Neuen Downloads';
$lang['cms_var_md_num_news'] = 'Anzahl der News im Portal';
$lang['cms_var_md_num_news_explain'] = '';
$lang['cms_var_md_num_posts'] = 'Anzahl der Beiträge im Portal';
$lang['cms_var_md_num_posts_explain'] = 'Anzahl der Beiträge, die angezeigt werden';
$lang['cms_var_md_num_random_topics'] = 'Anzahl der zufälligen Themen';
$lang['cms_var_md_num_random_topics_explain'] = 'Anzahl der anzuzeigenden Themen';
$lang['cms_var_md_num_random_topics_ver'] = 'Anzahl der zufälligen Themen';
$lang['cms_var_md_num_random_topics_ver_explain'] = 'Anzahl der Themen, die angezeigt werden';
$lang['cms_var_md_num_recent_topics'] = 'Anzahl der Neuen Themen';
$lang['cms_var_md_num_recent_topics_explain'] = 'Anzahl der anzuzeigenden Themen';
$lang['cms_var_md_num_recent_topics_wide'] = 'Anzahl der Neuen Themen';
$lang['cms_var_md_num_recent_topics_wide_explain'] = 'Anzahl der anzuzeigenden Themen';
$lang['cms_var_md_num_top_downloads'] = 'Top Downloads';
$lang['cms_var_md_num_top_downloads_explain'] = 'Anzahl der anzuzeigenden Top Downloads';
$lang['cms_var_md_pics_all'] = 'Anzeige von welchen Galerien?';
$lang['cms_var_md_pics_all_explain'] = '';
$lang['cms_var_md_pics_cols_number'] = 'Spaltenanzahl';
$lang['cms_var_md_pics_cols_number_explain'] = '';
$lang['cms_var_md_pics_number'] = 'Anzahl der anzuzeigenden Bilder';
$lang['cms_var_md_pics_number_explain'] = '';
$lang['cms_var_md_pics_rows_number'] = 'Reihenanzahl';
$lang['cms_var_md_pics_rows_number_explain'] = '';
$lang['cms_var_md_pics_sort'] = 'Zufällige oder neueste Bilder?';
$lang['cms_var_md_pics_sort_explain'] = '';
$lang['cms_var_md_poll_bar_length'] = 'Umfrage Balken LängePoll Bar Length';
$lang['cms_var_md_poll_bar_length_explain'] = 'verringern/vergrößern des Wertes der Umfrage Balken Länge';
$lang['cms_var_md_poll_forum_id'] = 'Umfrage Forum-ID(s)';
$lang['cms_var_md_poll_forum_id_explain'] = 'mit Komma getrennt';
$lang['cms_var_md_poll_type'] = 'Zufällige oder neueste Umfrage?';
$lang['cms_var_md_poll_type_explain'] = 'wähle hier aus, ob du die neuesten oder zufällige Umfragen anzeigen möchtest';
$lang['cms_var_md_posts_forum_id'] = 'Beitrags Forum-ID(s)';
$lang['cms_var_md_posts_forum_id_explain'] = 'mit Komma getrennt';
$lang['cms_var_md_posts_length'] = 'Länge der Beiträge';
$lang['cms_var_md_posts_length_explain'] = 'Anzahl der anzuzeigenden Buchstaben';
$lang['cms_var_md_posts_random'] = 'Neueste oder Zufällige?';
$lang['cms_var_md_posts_random_explain'] = 'Wähle neueste oder zufällige Themen';
$lang['cms_var_md_posts_show_portal'] = 'Alle Themen oder nur ausgewählte?';
$lang['cms_var_md_posts_show_portal_explain'] = 'Wähle alle Themen oder nur die mit "Im Portal anzeigen" aus';
$lang['cms_var_md_ran_att_forums_excl'] = 'Zufällige Anhänge ausschließende Forum-ID(s)';
$lang['cms_var_md_ran_att_forums_excl_explain'] = 'mit Komma getrennt; lasse dies frei für keine Ausschlüsse';
$lang['cms_var_md_ran_att_forums_incl'] = 'Zufällige Anhänge einschließende Forum-ID(s)';
$lang['cms_var_md_ran_att_forums_incl_explain'] = 'mit Komma getrennt; lasse dies frei für alle Foren';
$lang['cms_var_md_ran_att_height'] = 'Zufällige Anhänge Max Höhe';
$lang['cms_var_md_ran_att_height_explain'] = 'Wenn die Höhe > die Breite, wird dies als Höhe bei der Verwendung des BBCode IMG Tags benutzt';
$lang['cms_var_md_ran_att_max'] = 'Zufällige Anhänge Max Dateien';
$lang['cms_var_md_ran_att_max_explain'] = 'Maximale Anzahl der Dateien';
$lang['cms_var_md_ran_att_width'] = 'Zufällige Anhänge Max Breite';
$lang['cms_var_md_ran_att_width_explain'] = 'Wenn die Breite > die Höhe, wird dies als Breite bei der Verwendung des BBCode IMG Tags benutzt';
$lang['cms_var_md_random_topics_style'] = 'Zufällige Themen Style';
$lang['cms_var_md_random_topics_style_explain'] = 'wähle Feste oder Scroll Anzeige';
$lang['cms_var_md_random_topics_forums'] = 'Forum-ID(s)';
$lang['cms_var_md_random_topics_forums_explain'] = 'Forum-ID(s) die verwendet werden sollen (0 = alle)';
$lang['cms_var_md_random_topics_ver_forums'] = 'Forum-ID(s)';
$lang['cms_var_md_random_topics_ver_forums_explain'] = 'Forum-ID(s) die verwendet werden sollen (0 = alle)';
$lang['cms_var_md_recent_topics_style'] = 'Neue Themen Style';
$lang['cms_var_md_recent_topics_style_explain'] = 'wähle Feste oder Scroll Anzeige';
$lang['cms_var_md_recent_topics_wide_style'] = 'Neue Themen Style';
$lang['cms_var_md_recent_topics_wide_style_explain'] = 'wähle Feste- oder Scroll-Anzeige';
$lang['cms_var_md_rss_feeder'] = 'RSS Feed Adresse';
$lang['cms_var_md_rss_feeder_explain'] = 'Gib die Adresse des RSS Feeds ein. (z.B. http://www.icyphoenix.com/rss.php)';
$lang['cms_var_md_rss_title'] = 'RSS Feed Titel';
$lang['cms_var_md_rss_title_explain'] = 'Gib den Titel des RSS Feeds ein (z.B. Icy Phoenix)';
$lang['cms_var_md_rss_style'] = 'RSS Block Style';
$lang['cms_var_md_rss_style_explain'] = 'Wähle zwischen horizontal oder vertikal aus.';
$lang['cms_var_md_rss_scroll'] = 'RSS Block Scroll';
$lang['cms_var_md_rss_scroll_explain'] = 'Wähle zwischen feststehend oder scrollend aus.';
$lang['cms_var_md_show_background'] = 'Show Cats Background?';
$lang['cms_var_md_show_background_explain'] = 'Select YES if you want to show cats background';
$lang['cms_var_md_show_cats_icon'] = 'Show Cats Icons?';
$lang['cms_var_md_show_cats_icon_explain'] = 'Select YES if you want to show cats icons';
$lang['cms_var_md_show_desc'] = 'Show Links Descriptions?';
$lang['cms_var_md_show_desc_explain'] = 'Select YES if you want to show links descriptions with mouse-hover effect';
$lang['cms_var_md_show_links_icon'] = 'Show Links Icons?';
$lang['cms_var_md_show_links_icon_explain'] = 'Select YES if you want to show links icons';
$lang['cms_var_md_show_sep_icon'] = 'Show Separator Icons?';
$lang['cms_var_md_show_sep_icon_explain'] = 'Select YES if you want to show separator icons';
$lang['cms_var_md_show_title'] = 'Show Cats Title?';
$lang['cms_var_md_show_title_explain'] = 'Select YES if you want to show cats title';
$lang['cms_var_md_single_post_auto_id'] = 'Erhalte ID von Adresse';
$lang['cms_var_md_single_post_auto_id_explain'] = 'Bei Aktivierung wird die ID direkt von der Adresse bezogen (post_id=XXX)';
$lang['cms_var_md_single_post_id'] = 'Beitrags ID';
$lang['cms_var_md_single_post_id_explain'] = 'Gib die Beitrags ID ein';
$lang['cms_var_md_single_post_retrieve'] = 'Einzel Beitrag abrufen';
$lang['cms_var_md_single_post_retrieve_explain'] = 'Bei Aktivierung wird nur ein Beitrag angezeigt, der weiter unten bestimmt wurde, alle anderen Einstellungen werden ignoriert';
$lang['cms_var_md_scroll_delay'] = 'Scroll Verzögerung';
$lang['cms_var_md_scroll_delay_explain'] = 'Größere Einträge bedeuten langsameres scrollen';
$lang['cms_var_md_search_option_text'] = 'Suchfeld Beschreibung';
$lang['cms_var_md_search_option_text_explain'] = 'Suchfeld Beschreibung';
$lang['cms_var_md_total_poster'] = 'Anzahl der Top Poster';
$lang['cms_var_md_total_poster_explain'] = '';
$lang['cms_var_md_wordgraph_count'] = 'Aktiviere Wort Zählungen';
$lang['cms_var_md_wordgraph_count_explain'] = 'Zeige die Gesamtanzahl der Wörter neben jedem Wort';
$lang['cms_var_md_wordgraph_words'] = 'Maximale Wörter';
$lang['cms_var_md_wordgraph_words_explain'] = 'Wähle die Anzahl der maximal anzuzeigenden Wörter';

$lang['cms_option_All_Topics'] = 'Alle Themen';
$lang['cms_option_Alphabetical'] = 'Alphabetisch';
$lang['cms_option_Archive'] = 'Archiv';
$lang['cms_option_Categories'] = 'Kategorien';
$lang['cms_option_Newest'] = 'Neueste';
$lang['cms_option_Public'] = 'Öffentlich';
$lang['cms_option_Public_and_Personal'] = 'Öffentlich und Persönlich';
$lang['cms_option_Random'] = 'Zufällige';
$lang['cms_option_Recent'] = 'Neuesten';
$lang['cms_option_Scroll'] = 'Scrollend';
$lang['cms_option_Static'] = 'Feststehend';
$lang['cms_option_Horizontal'] = 'Horizontal';
$lang['cms_option_Vertical'] = 'Vertikal';
$lang['cms_option_Show_In_Portal'] = 'Im Portal anzeigen';
$lang['cms_option_Yes'] = 'Ja';
$lang['cms_option_No'] = 'Nein';
$lang['cms_option_Left'] = 'Links';
$lang['cms_option_Center'] = 'Center';
$lang['cms_option_Right'] = 'Rechts';

$lang['cms_value_All_Topics'] = '0';
$lang['cms_value_Archive'] = '0';
$lang['cms_value_Categories'] = '1';
$lang['cms_value_Newest'] = '0';
$lang['cms_value_Public'] = '0';
$lang['cms_value_Public_and_Personal'] = '1';
$lang['cms_value_Random'] = '1';
$lang['cms_value_Recent'] = '0';
$lang['cms_value_Show_In_Portal'] = '1';

?>