<?php
/**
*
* @package Icy Phoenix
* @version $Id$
* @copyright (c) 2008 Icy Phoenix
* @license http://opensource.org/licenses/gpl-license.php GNU Public License
*
*/

/**
*
* @Icy Phoenix is based on phpBB
* @copyright (c) 2008 phpBB Group
*
*/

/**
*
* @Extra credits for this file
* TheSteffen, KugeLSichA, Tom
*
*/

if (!defined('IN_ICYPHOENIX'))
{
	exit;
}

//
// Um einen neuen Eintrag zu deinen FAQs hinzuzufügen, trage hier einfach einen neue Zeile in folgendem Format ein:
// $faq[] = array("Frage", "Antwort");
// Wenn du eine Sektion abgrenzen willst füge folgendes hinzu: $faq[] = array("--", "Wenn gewünscht, hier Überschrift eintragen");
// Links werden automatisch erstellt.
//
// Vergesse NICHT das ; am Ende jeder Zeile.
// Füge KEINE doppelten Anführungsstriche (") in deinen Regel-Einträgen hinzu, wenn du es unbedingt brauchst dann trenne sie mit \"irgendetwas\" ab
// Die FAQ-Einträge werden in der Reihenfolge wie sie hier angegeben sind angezeigt


$faq[] = array("--", "Registrieren und Einloggen");
$faq[] = array("Warum kann ich mich nicht einloggen?", "Hast du dich registriert? Du musst dich erst registrieren, bevor du dich einloggen kannst. Wurdest du vom Board gebannt (in dem Fall erhältst du eine Nachricht)? Wenn dem so ist, solltest du den Webmaster oder den Forumsadministrator kontaktieren, um herauszufinden, warum. Falls du registriert und nicht gebannt bist und dich immer noch nicht einloggen kannst, dann überprüfe deinen Benutzernamen und das Passwort. Normalerweise liegt hier der Fehler, falls nicht, kontaktiere den Forumsadministrator, es könnte eine fehlerhafte Forumskonfiguration vorliegen.");
$faq[] = array("Warum muss ich mich überhaupt registrieren?", "Es kann auch sein, dass du das gar nicht musst. Das ist die Entscheidung des Administrators. Auf jeden Fall erhältst du nach der Registrierung zusätzliche Funktionen, die Gäste nicht haben, z.B. Avatare, Private Nachrichten, Eintritt in Benutzergruppen, usw. Es dauert nur wenige Augenblicke, um sich zu registrieren. Du solltest es also gleich tun.");
$faq[] = array("Warum werde ich automatisch abgemeldet?", "Solltest du die Funktion <i>Automatisch einloggen</i> beim Einloggen nicht aktiviert haben, bleibst du nur für eine gewisse Zeit eingeloggt. Dadurch wird ein Missbrauch deines Accounts verhindert. Um eingeloggt zu bleiben, wähle die entsprechende Option beim Einloggen. Dies ist nicht empfehlenswert, wenn du an einem fremden Rechner sitzt, z.B. in einer Bücherei, Universität oder im Internetcafé usw.");
$faq[] = array("Wie kann ich verhindern, dass mein Name in der &quot;Wer ist online?&quot;-Liste auftaucht?", "In deinem Profil findest du die Option <i>Online-Status verstecken</i>. Wenn du diese aktivierst, können dich nur noch Administratoren in der Liste sehen. Du zählst dann als versteckter Benutzer.");
$faq[] = array("Ich habe mein Passwort verloren!", "Kein Problem! Du kannst ein neues Passwort anfordern. Klicke dazu innerhalb der Loginseite auf <u>Ich habe mein Passwort vergessen</u>. Folge den Anweisungen und du solltest dich bald wieder einloggen können.");
$faq[] = array("Ich habe mich registriert, kann mich aber nicht einloggen!", "Überprüfe erst, ob du den richtigen Benutzernamen und/oder Passwort angegeben hast. Falls sie stimmen, gibt es zwei Möglichkeiten, was passiert ist: Wenn die COPPA-Bestimmungen aktiviert sind und du die Option <u>Ich bin unter 12 Jahre alt</u> beim Registrieren gewählt hast, musst du den erhaltenen Anweisungen folgen. Falls dies nicht der Fall ist, braucht dein Account eine Aktivierung. Auf einigen Boards muss eine Registrierung immer erst aktiviert werden, bevor du dich einloggen kannst - entweder von dir selbst oder vom Administrator. Beim Registrieren wird dir gesagt, ob eine Aktivierung benötigt wird. Falls dir eine E-Mail zugesandt wurde, folge den enthaltenen Anweisungen. Falls du diese E-Mail nicht erhalten hast, vergewissere dich, dass die E-Mail-Adresse korrekt war. Ein Grund für den Gebrauch der Benutzerkonto-Aktivierungen ist die Verhinderung eines Missbrauchs des Forums. Wenn du dir sicher bist, dass die angegebene E-Mail-Adresse richtig ist, kontaktiere den Administrator.");
$faq[] = array("Ich habe mich vor einiger Zeit registriert, kann mich aber nicht mehr einloggen!", "Die Gründe dafür sind meistens, dass du entweder einen falschen Benutzernamen oder ein falsches Passwort eingegeben hast (überprüfe die E-Mail, die du vom Board bekommen hast) oder der Administrator hat deinen Account gelöscht. Falls Letzteres der Fall ist, hast du vielleicht mit dem Account noch nichts gepostet? Es ist durchaus üblich, dass Foren regelmäßig Benutzer löschen, die nichts gepostet haben, um die Größe der Datenbank zu verringern. Versuche dich erneut zu registrieren und tauche wieder ein in die Welt der Diskussionen.");


$faq[] = array("--", "Benutzerangaben und Einstellungen");
$faq[] = array("Wie ändere ich meine Einstellungen?", "Deine Einstellungen (sofern du registriert bist) werden in der Datenbank gespeichert. Klicke auf den <u>Profil</u>-Link, um sie zu ändern. (wird normalerweise am oberen Bildschirmrand angezeigt, hängt aber vom Style ab) Damit kannst du deine Einstellungen ändern.");
$faq[] = array("Die Zeiten stimmen nicht!", "Die Zeiten stimmen höchstwahrscheinlich schon. Vermutlich hast du einfach die Zeitzone nicht richtig eingestellt. Falls dem so ist, solltest du die Einstellungen deines Profils überprüfen, um die Zeitzone die für dich zutreffend ist, zu wählen. Bitte beachte, dass du die Zeitzone nur wechseln kannst, wenn du ein registriertes Mitglied bist. Falls du also noch nicht registriert bist, wäre das vielleicht ein guter Grund dazu.");
$faq[] = array("Ich habe die Zeitzone gewechselt und die Zeit ist immer noch falsch!", "Wenn du dir sicher bist, die richtige Zeitzone gewählt zu haben und die Zeiten immer noch nicht stimmen, kann es daran liegen, dass das System auf Sommerzeit steht. Das Board ist nicht dazu geschaffen worden, zwischen Winter- und Sommerzeit zu wechseln. Daher kann es im Sommer zu einer Stunde Differenz zwischen deiner gewählten und der Boardzeit kommen.");
$faq[] = array("Meine Sprache ist nicht verfügbar!", "Der wahrscheinlichste Grund dafür ist, dass der Administrator die Sprache nicht installiert hat oder das Board wurde noch nicht in deine Sprache übersetzt. Versuche den Administrator davon zu überzeugen, dein Sprachpaket zu installieren oder, falls es nicht existiert, kannst du auch gerne selber eine Übersetzung schreiben. Weitere Informationen erhältst du auf der Icy Phoenix Group Website (Der Link ist am Ende jeder Seite)");
$faq[] = array("Wie kann ich ein Bild unter meinem Benutzernamen anzeigen?", "Es können sich zwei Bilder unter dem Benutzernamen befinden. Das erste gehört zu deinem Rang, z.B. Punkte oder Sterne, die anzeigen, wie viele Beiträge du geschrieben hast oder welchen Status du im Forum hast. Darunter befindet sich meist ein größeres Bild, auch Avatar genannt. Dies ist normalerweise ein Einzelstück und an den Benutzer gebunden. Es liegt am Administrator, ob er Avatare erlaubt und ob die Benutzer wählen dürfen, wie sie ihren Avatar zugänglich machen. Wenn du keine Avatare benutzen kannst, ist das eine Entscheidung des Administrators. Du solltest ihn nach dem Grund fragen (Er wird bestimmt einen guten haben).");
$faq[] = array("Wie kann ich meinen Rang ändern?", "Normalerweise kannst du nicht direkt den Wortlaut des Ranges ändern (Ränge erscheinen unter deinem Benutzernamen in Themen und in deinem Profil, abhängig davon, welchen Style du benutzt). Die meisten Boards benutzen Ränge, um anzuzeigen, wie viele Beiträge geschrieben wurden und bestimmte Benutzer, z.B. Moderatoren oder Administratoren, könnten einen speziellen Rang haben. Bitte belästige das Forum nicht mit unnötigen Beiträgen, nur um deinen Rang bzw. Beitragsanzahl zu erhöhen. Sonst wird ein Moderator oder Administrator deinen Rang bzw. Beitragsanzahl einfach wieder senkt.");
$faq[] = array("Wenn ich auf den E-Mail-Link eines Benutzers klicke, werde ich aufgefordert, mich einzuloggen!", "Nur registrierte Benutzer können über das Forum E-Mails verschicken (falls der Administrator diese Funktion zulässt). Damit sollen obszöne Mails von unbekannten Benutzern unterbunden werden.");

$faq[] = array("--", "Beiträge schreiben");
$faq[] = array("Wie schreibe ich ein Thema in ein Forum?", "Klicke einfach auf den Button &quot;Neues Thema&quot; auf der Forums- oder Beitragsseite. Es kann sein, dass du dich erst registrieren musst, bevor du eine Nachricht schreiben kannst. Deine verfügbaren Aktionen werden am Ende der Seite aufgelistet. (die Liste: <i>Du kannst neue Themen erstellen, du kannst an Umfragen teilnehmen, usw.</i>)");
$faq[] = array("Wie bearbeite oder lösche ich einen Beitrag?", "Sofern du nicht ein Administrator oder Moderator bist, kannst du nur deine eigenen Beiträge löschen oder bearbeiten. Du kannst einen Beitrag bearbeiten (eventuell nur für eine gewisse Zeit) indem du auf den <i>bearbeiten</i>-Button des jeweiligen Beitrages klickst. Sollte jemand bereits auf den Beitrag geantwortet haben, wirst du einen kleinen Text unterhalb des Beitrags lesen können, der anzeigt, wie oft der Text bearbeitet wurde. Er wird nur erscheinen, wenn jemand geantwortet hat. Ferner wird er nicht erscheinen, wenn ein Moderator oder Administrator den Beitrag bearbeitet hat. (Sie sollten eine Nachricht hinterlassen, warum sie den Beitrag änderten) Beachte, dass normale Benutzer keine Beiträge löschen können, wenn bereits jemand eine Antwort hinterlassen hat.");
$faq[] = array("Wie kann ich eine Signatur anhängen?", "Um eine Signatur an einen Beitrag anzuhängen, musst du erst eine im Profil erstellen. Wenn du eine erstellt hast, aktiviere die <i>Signatur anhängen</i>-Funktion während der Beitragserstellung. Du kannst auch standardmäßig eine Signatur an alle Beiträge anhängen, indem du im Profil die entsprechende Option auswählst (du kannst das Anfügen einer Signatur immer noch verhindern, indem du die Signaturoption beim Beitragsschreiben abschaltest).");
$faq[] = array("Wie erstelle ich eine Umfrage?", "Eine Umfrage zu erstellen ist recht einfach: Wenn du ein neues Thema erstellst (oder den ersten Beitrag eines Themas bearbeitest, sofern du die Erlaubnis dazu hast), solltest du die <i>Umfrage hinzufügen</i>-Option unterhalb der Textbox sehen (falls du sie nicht sehen kannst, hast du möglicherweise nicht die erforderlichen Rechte). Du solltest einen Titel für deine Umfrage angeben und mindestens zwei Antwortmöglichkeiten (um eine Antwort anzugeben, klicke auf die <i>Antwort hinzufügen</i>-Schaltfläche. Du kannst auch ein Zeitlimit für die Umfrage setzen, 0 ist eine unbegrenzt dauernde Umfrage. Es gibt eine Grenze bei der Anzahl an Antwortoptionen. Diese legt der Administrator fest.");
$faq[] = array("Wie bearbeite oder lösche ich eine Umfrage?", "Genau wie bei den Beiträgen, können Umfragen nur vom Verfasser, Forummoderator oder Administrator bearbeitet oder gelöscht werden. Um eine Umfrage zu ändern, bearbeite den ersten Beitrag im Thema (die Umfrage ist immer damit verbunden). Wenn noch niemand bei der Umfrage teilgenommen hat, können Benutzer die Umfrage bearbeiten oder löschen. Falls jedoch bereits jemand mit abgestimmt hat, können sie nur Moderatoren oder Administratoren löschen oder bearbeiten. Damit soll verhindert werden, dass Personen ihre Umfragen beeinflussen, indem sie die Antworten verändern.");
$faq[] = array("Warum kann ich ein Forum nicht betreten?", "Manche Foren können nur von bestimmten Benutzern oder Gruppen betreten werden. Um dort hineinzugelangen, Beiträge zu lesen oder zu schreiben usw., könntest du eine spezielle Erlaubnis brauchen. Nur der Forummoderator und der Boardadministrator können dir die Zugangsrechte dafür geben, du solltest sie um Zugang bitten, sofern du einen berechtigten Grund dafür hast.");
$faq[] = array("Warum kann ich bei Abstimmungen nicht mitmachen?", "Nur registrierte Benutzer können an Umfragen teilnehmen. Dadurch wird eine Beeinflussung des Ergebnisses verhindert. Falls du dich registriert hast und immer noch nicht mitstimmen kannst, hast du vermutlich nicht die erforderlichen Rechte dazu.");

$faq[] = array("--", "Was man in und mit Beiträgen tun kann");
$faq[] = array("Was ist BBCode?", "BBCode ist eine spezielle Art von HTML. Ob du BBCode benutzen kannst, wird vom Administrator festgelegt. Du kannst es auch in einzelnen Beiträgen deaktivieren. BBCode selbst ist dem HTML-Code sehr ähnlich. Die Tags sind von den Klammern [ und ] umschlossen und bieten dir große Kontrolle darüber, was und wie etwas angezeigt wird. Für weitere Informationen über den BBCode solltest du dir die Anleitung anschauen, die du von der Beitrag schreiben-Seite aus erreichen kannst.");
$faq[] = array("Darf ich HTML benutzen?", "Das hängt davon ab, ob es vom Administrator erlaubt wurde. Falls du es nicht darfst, wirst du nachher nur ein Klammer-Wirrwarr wieder finden. Dies ist eine <i>Sicherung</i>, um Leute davon abzuhalten, das Forum mit unnötigen Tags zu überschwemmen, die das Layout zerstören oder andere Störungen hervorrufen können. Falls HTML aktiviert wurde, kannst du es immer noch manuell für jeden Beitrag deaktivieren, indem du beim Schreiben die entsprechende Option aktivierst.");
$faq[] = array("Was sind Smilies?", "Smilies sind kleine Bilder, die benutzt werden können, um Gefühle auszudrücken. Es werden nur kurze Codes benötigt, z.B. zeigt :) Freude und :( Traurigkeit an. Die komplette Liste der Smilies kann auf der Beitrag schreiben-Seite gesehen werden. Übertreibe es nicht mit Smilies. Es kann schnell passieren, dass ein Beitrag dadurch völlig unübersichtlich wird. Ein Moderator könnte sich entschließen, den Beitrag zu bearbeiten oder sogar komplett zu löschen.");
$faq[] = array("Darf ich Bilder einfügen?", "Bilder können in dieses Forum hochgeladen und im Beitrag angezeigt werden. Wenn diese Funktion durch die Administration deaktiviert ist, musst du zu einem bestehenden Bild verlinken, welches sich auf einem für die Öffentlichkeit zugänglichen Server befindet. Zum Beispiel &quot;http://www.example.org/meinbild.jpg&quot;. Du kannst jedoch weder zu Bildern verlinken, die sich auf deiner Festplatte befinden (außer es handelt sich um einen öffentlich verfügbaren Server) noch zu Bildern, die einen speziellen Zugang brauchen, um sie anzuzeigen (z.B. E-Mail-Konten, Passwort-geschützte Seiten usw.). Um das Bild anzuzeigen, benutze entweder den BB-Code [img][/img] oder nutze HMTL (sofern erlaubt).");
$faq[] = array("Was sind Ankündigungen?", "Ankündigungen beinhalten meistens wichtige Informationen und du solltest sie so früh wie möglich lesen. Ankündigungen erscheinen immer am Anfang des jeweiligen Forums. Ob du eine Ankündigung machen kannst oder nicht hängt davon ab, was für Befugnisse dazu eingerichtet wurden. Diese legt der Board-Administrator fest.");
$faq[] = array("Was sind Wichtige Themen?", "Wichtige Themen erscheinen unterhalb der Ankündigungen in der Forumsansicht. Sie enthalten auch meistens wichtige Informationen, die du gelesen haben solltest. Genau wie mit den Ankündigungen entscheidet auch bei den Wichtigen Themen der Administrator, wer sie erstellen darf.");
$faq[] = array("Was sind geschlossene Themen?", "Themen werden entweder vom Forummoderator oder dem Board-Administrator geschlossen. Man kann auf geschlossene Beiträge nicht antworten. Falls eine Umfrage angefügt wurde, wird diese damit auch beendet. Es gibt verschiedene Gründe, warum ein Thema geschlossen wird.");

$faq[] = array("--", "Benutzerebenen und Gruppen");
$faq[] = array("Was sind Administratoren?", "Administratoren haben die höchste Kontrollebene im gesamten Forum. Sie haben das Recht, jede Forumsaktion zu unterbinden und spezielle Aktionen durchzuführen, wie die Vergabe von Befugnissen, das Bannen von Benutzern, Benutzergruppen erstellen, Moderatoren ernennen usw. Sie haben außerdem in jedem Forum die vollen Moderatorenrechte.");
$faq[] = array("Was sind Moderatoren?", "Moderatoren sind Personen (oder Gruppen), die auf das tägliche Geschehen in dem jeweiligen Forum achten. Sie haben die Möglichkeit, Beiträge zu bearbeiten und zu löschen, Themen zu schließen, öffnen, verschieben oder löschen. Moderatoren haben die Aufgabe, Benutzer davon abzuhalten, unpassende Themen in einen Beitrag zu schreiben oder sonstigen Blödsinn in das Forum zu setzen.");
$faq[] = array("Was sind Benutzergruppen?", "In Benutzergruppen werden einige Benutzer vom Administrator zusammengefasst. Jeder Benutzer kann zu mehreren Gruppen gehören und jeder Gruppe können spezielle Zugangsrechte erteilt werden. So ist es für den Administrator einfacher, mehrere Benutzer zu Moderatoren eines bestimmten Forums zu machen, ihnen Rechte für ein privates Forum zu geben und so weiter.");
$faq[] = array("Wie kann ich einer Benutzergruppe beitreten?", "Um einer Benutzergruppe beizutreten, klicke auf den Benutzergruppen-Link im Menü. Du erhältst dann einen Überblick über alle Benutzergruppen. Nicht alle Gruppen haben <i>offenen Zugang</i>, manche sind geschlossen und andere könnten versteckt sein. Falls die Gruppe neue Mitglieder zulässt, kannst du um Einlass in die Gruppe bitten, indem du auf den Beitreten-Button klickst. Der Gruppenmoderator muss noch seine Zustimmung geben; eventuell gibt es Rückfragen, warum du der Gruppe beitreten möchtest. Bitte nerve die Gruppenmoderatoren nicht, wenn sie dich nicht in die Gruppe aufnehmen wollen. Sie werden ihre Gründe haben.");
$faq[] = array("Wie werde ich ein Gruppenmoderator?", "Benutzergruppen werden vom Administrator erstellt. Er bestimmt ebenfalls den Moderator. Falls du daran interessiert bist selbst eine Benutzergruppe zu erstellen, solltest du zuerst den Administrator kontaktieren. Zum Beispiel mit einer PN (privaten Nachricht).");

$faq[] = array("--", "Private Nachrichten");
$faq[] = array("Ich kann keine Privaten Nachrichten verschicken!", "Es gibt drei mögliche Gründe dafür: Du bist nicht registriert bzw. eingeloggt, der Board-Administrator hat das Private Nachrichten-System für das gesamte Board abgeschaltet oder der Administrator hat dir das Schreiben von Privaten Nachrichten untersagt. Falls das letzte zutreffen sollte, solltest du ihn fragen, warum.");
$faq[] = array("Ich erhalte dauernd ungewollte Private Nachrichten!", "In späteren Versionen wird es ein Ignorieren-System für Private Nachrichten geben. Im Moment musst du, falls du ununterbrochen unerwünschte Nachrichten von einer Person erhältst, den Administrator informieren. Er kann das Versenden von Privaten Nachrichten durch den jeweiligen Benutzer unterbinden.");
$faq[] = array("Ich habe eine Spam- oder perverse E-Mail von jemandem auf diesem Board erhalten!", "Das E-Mail-System dieses Boards enthält Sicherheitsvorkehrungen, um solche Aktionen eines Benutzers zu verhindern. Du solltest dem Board-Administrator eine Kopie der erhaltenen E-Mail schicken; wichtig dabei ist, dass die Kopfzeilen angefügt bleiben (die Details über den Benutzer, der die E-Mail schickte). Erst dann kann er handeln.");

$faq[] = array("--", "Avatar Generator");
$faq[] = array("Was ist das?", "Der <strong>Avatar Generator</strong> kann von den Benutzern des Forums verwendet werden, um eigene Avatare zu erstellen.");
$faq[] = array("Wo kann ich es finden?", "Möglicherweise musst du dich im Forum anmelden, um den Avatar-Generator verwenden zu können. Du kannst ihn in deinem Profil im Abschnitt Avatar finden.");
$faq[] = array("Wie speichere ich einen erstellten Avatar?", "Unter dem erstellten Avatar sollte ein Link mit der Aufschrift <strong>Klicke hier um diesen Avatar zum Profil hinzuzufügen</strong> sein. Wenn du auf diesen Link klickst, kommt eine Nachricht, die dich über die erfolgte Änderung informiert.");

$faq[] = array("--", "Foto-Galerie");
$faq[] = array("Wie gelange ich zur Foto-Galerie?", "Einfach den Link &quot;Foto-Galerie&quot; im Navigations-Menü benutzen. Dadurch gelangst du zum Haupt-Albumverzeichnis, in dem alle öffentlichen Foto-Alben angezeigt werden. Du kannst Dir auch persönliche Foto-Galerien der Benutzer anschauen. Klicke dazu auf den Link &quot;persönliche Galerien der Benutzer&quot; gleich unter den öffentlichen Kategorien.");
$faq[] = array("Wie lade ich ein Foto in die Foto-Galerie?", "Wenn du im Haupt-Albumverzeichnis bist, wähle entweder eine &quot;öffentliche Foto-Galerie&quot; oder &quot;Deine persönliche Foto-Galerie&quot; aus. Nun solltest du auf der Seite oben und unten den Button &quot;Bild hochladen&quot; sehen, wenn die Funktion durch die Administration aktiviert ist. Klicke diesen Button und folge den weiteren Anweisungen.");
$faq[] = array("Was ist die maximale erlaubte Dateigröße, Breite und Höhe des Bildes?", "Diese Daten kannst du dir auf der Seite &quot;Bild hochladen&quot; anzeigen lassen. Der Administrator legt die maximale Dateigröße, mögliche Datei-Erweiterungen und andere Dinge für hochzuladene Bilder fest.");
$faq[] = array("In welchem Format müssen meine Bilder sein?", "Diese Daten kannst du dir auf der Seite &quot;Bild hochladen&quot; anzeigen lassen. Der Administrator legt die maximale Dateigröße, mögliche Datei-Erweiterungen und andere Dinge für hochzuladene Bilder fest.");
$faq[] = array("Ich kann mein Bild immer noch nicht hochladen und bekomme dauernd eine Fehlermeldung!", "Gehe zurück in das Upload-Formular und vergewissere dich, dass du alle Anweisungen befolgt hast. Die Datei könnte größer sein als die tatsächlich erlaubte Maximalgröße. Vielleicht hast du versucht ein Bild mit zu großer Höhe oder Breite hochzuladen, oder du hast es mit einem Bildformat versucht, das nicht erlaubt ist, oder du hast einfach vergessen alle notwendigen Felder auszufüllen.");
$faq[] = array("Ich habe einen Fehler beim Titel und/oder in der Beschreibung gemacht. Was kann ich tun?", "Wenn du ein Bild betrachtest, hast du mehrere Optionen zur Auswahl. Wenn es der Administrator erlaubt hat, wirst du den Link &quot;Ändern&quot; unter jedem Thumbnail finden. Dieser gestattet dir die oben genannten Informationen jederzeit zu ändern.");
$faq[] = array("Wie kann ich ein Bild löschen?", "Wenn du dir ein Bild anschaust, sind dort verschiedene Optionen verfügbar. Wenn es der Administrator erlaubt hat, wirst du den Link &quot;Löschen&quot; unter jedem Thumbnail finden. Dieser erlaubt dir eines deiner eigenen Bilder zu löschen.");
$faq[] = array("Ich möchte jemandem mitteilen, wie sehr ich das Bild mag oder nicht mag. Wie kann ich das machen?", "Wenn du ein Bild betrachtest, hast du mehrere Optionen zur Auswahl. Wenn es der Administrator erlaubt hat, wirst du den Link &quot;Bewertung&quot; und &quot;Kommentare&quot; unter jedem Thumbnail bzw. Bild finden.");

$faq[] = array("--", "Dateianhänge");
$faq[] = array("Wie füge ich Dateianhänge hinzu?", "Du kannst Dateianhänge hinzufügen, wenn du eine neue Nachricht schreibst. Du solltest ein <i>Dateianhang hinzufügen</i> Formular unter dem eigentlichen Nachrichten Formular sehen. Wenn du den <i>Durchsuchen&hellip;</i> Button anklickst öffnet sich das Standard &quot;Datei auswählen&hellip;&quot; Dialogfenster für deinen Rechner. Suche nach der Datei, die du gerne hinzufügen möchtest. Wähle Sie aus und klicke OK oder führe die Schritte für das auswählen von Dateien (öffnen, doppelklicken) für deinen entsprechenden Rechner aus. Wenn du einen Kommentar zu deinem Dateianhang in dem Feld <i>Kommentar</i> hinzufügst, dann wird dieser Kommentar als Link zur hinzugefügten Datei verwendet. Andernfalls wird der Dateiname als Link verwendet. Wenn es der Administrator erlaubt hat, mehrere Dateianhänge in einer Nachricht hinzuzufügen, dann kannst du die obigen Schritte so lange ausführen bis die maximale Anzahl von erlaubten Dateianhängen pro Nachricht erreicht ist.<br /><br />Der Foren Administrator kann eine maximal erlaubte Dateigröße angeben, verbotene Dateierweiterungen definieren und Dateiendungen für Dateianhänge im Board festlegen. Es wird darauf hingewiesen, dass es deiner Verantwortung unterliegt, dass die Dateianhänge mit den definierten Regeln konform sind und dass Dateianhänge ohne vorherige Warnung gelöscht werden könnten.<br /><br />Bitte bedenke das der Forenbesitzer, Webmaster, Administrator oder die Moderatoren keinesfalls Verantwortung für jegliche Form von Datenverlust übernehmen werden und können.");
$faq[] = array("Wie füge ich einen Dateianhang nach meinem eigentlichen Beitrag hinzu?", "Um einen Dateianhang nachträglich einer Nachricht hinzuzufügen, musst du deine Nachricht editieren und die oben beschriebenen Schritte durchführen. Nach dem Absenden deiner editierten Nachricht, wird der neue Dateianhang (oder die Dateianhänge) angezeigt/hinzugefügt.");
$faq[] = array("Wie kann ich einen Dateianhang löschen?", "Um Dateianhänge zu löschen, musst du deine Nachricht editieren und auf den Button <i>Anhang löschen</i> unter dem zu löschendem Dateianhang in dem Formular <i>Bereits angehängte Dateien</i> klicken. Der Dateianhang wird dann nach dem Absenden der editierten Nachricht gelöscht.");
$faq[] = array("Wie kann ich meinen Dateikommentar editieren?", "Um einen Dateikommentar zu ändern, musst du deine Nachricht editieren. Passe den Text im <i>Datei-Kommentar</i> Feld für den entsprechenden Dateianhang an und klicke den <i>Kommentar aktualisieren</i> Button unter dem Feld an. Der Dateikommentar wird nach dem Absenden der editierten Nachricht aktualisiert.");
$faq[] = array("Warum kann ich meinen Dateianhang in meiner Nachricht nicht mehr sehen?", "Wahrscheinlich ist die Datei oder die Dateiendung in dem Forum nicht länger gültig oder ein Moderator/Administrator hat den Dateianhang aufgrund von Konflikten mit den Regeln des Boards gelöscht.");
$faq[] = array("Warum kann ich keine Dateianhänge hinzufügen?", "In einigen Foren kann das Hinzufügen von Dateianhänge nur für einige Benutzergruppen oder Benutzer erlaubt sein. Um Dateianhänge hinzufügen zu können, muss man Rechte besitzen, welche nur vom Foren Administrator vergeben werden können. Du solltest die entsprechenden Moderatoren oder den Foren Administrator kontaktieren, wenn du das ungerecht findest.");
$faq[] = array("Ich habe die erforderliche Berechtigung. Warum kann ich trotzdem keine Dateianhänge hinzufügen?", "Der Foren Administrator kann eine maximal erlaubte Dateigröße angeben, verbotene Dateierweiterungen definieren und Dateiendungen für Dateianhänge im Board festlegen. Der Administrator könnte deine Berechtigungen oder die Berechtigungen für Dateianhänge in dem speziellen Forum geändert haben. Du solltest auch eine entsprechende Erklärung in der Fehlernachricht beim Hinzufügen von Dateianhängen bekommen. Wenn nicht, dann solltest du den oder die entsprechenden Moderatoren oder den Administrator kontaktieren.");
$faq[] = array("Warum kann ich meine Dateianhänge nicht löschen?", "In einigen Foren kann das Löschen von Dateianhängen für bestimmte Benutzer oder Gruppen limitiert sein. Um Dateianhänge löschen zu können, muss man Rechte besitzen, welche nur vom Foren Administrator vergeben werden können. Du solltest die entsprechenden Moderatoren oder den Foren Administrator kontaktieren, wenn du das ungerecht findest.");
$faq[] = array("Warum kann ich keine Dateianhänge ansehen oder herunterladen?", "In einigen Foren kann das Ansehen/Herunterladen von Dateianhängen für bestimmte Benutzer oder Gruppen limitiert sein. Um Dateianhänge ansehen/herunterladen zu können, muss man Rechte besitzen, welche nur vom Foren Administrator vergeben werden können. Du solltest die entsprechenden Moderatoren oder den Foren Administrator kontaktieren, wenn du das ungerecht findest.");
$faq[] = array("Wen sollte ich über illegale oder vermeintlich illegale Dateianhänge unterrichten?", "Du solltest zunächst einen Moderator darüber informieren. Wenn du keinen Moderator benachrichtigen kannst oder es noch keinen Moderator gibt, solltest du den Administrator kontaktieren. Wenn du keine Nachricht verschicken kannst oder du keine Antwort erhältst, kontaktiere den Domaininhaber, welchen du mit einer &quot;whois&quot; Abfrage herausfinden kannst. Wenn das Forum auf einem kostenlosen Webhoster laufen sollte (z.B.: 000webhost.com, kilu.de, funpic.de, godaddy.com usw.), dann benutze den dortigen &quot;Abuse&quot; Service.<br />Bitte beachte, dass die phpBB Gruppe bzw. IcyPhoenix Gruppe absolut keinen Einfluss auf diese Dateianhänge hat und in keiner Weise haftbar gemacht werden kann, wie, wo oder von wem das Board eingesetzt wird. Es ist absolut sinnlos, die phpBB Gruppe / IcyPhoenix Gruppe in Zusammenhang mit jeglichen juristischen Fragen (wie Unterlassungserklärungen, Haftungsfragen, diffamierenden Kommentar, usw.) zu kontaktieren, welche sich nicht direkt auf die Website icyphoenix.de oder die IcyPhoenix/phpBB-Software selbst beziehen. Wenn du per E-Mail der IcyPhoenix Gruppe über die Nutzung Dritter meldest, welche diese Software nutzen, dann solltest du erwarten, dass du höchstens eine knappe oder überhaupt keine Antwort erhälst.");

$faq[] = array("--", "Downloads");
$faq[] = array("Wo finde ich den Downloadbereich?", "Verweise zum Downloadbereich befinden sich in der Navigationsleiste und der Portalnavigation. Direktlink: [<a href=\"dload.php\">Downloads</a>]");
$faq[] = array("Was bedeutet <img border=\"0\" src=\"" . $images['Dl_blue'] . "\" alt=\"\" title=\"\" />?", "Kein Download möglich. Der festgelegte Gesamttraffic des Downloadbereiches oder der angezeigten Kategorie ist für den laufenden Monat verbraucht.");
$faq[] = array("Was bedeutet <img border=\"0\" src=\"" . $images['Dl_red'] . "\" alt=\"\" title=\"\" />?", "Kein Download möglich. Dieses kann mehrere Ursachen haben:<br />- Der Download ist vom Administrator gesperrt.<br />- Der Benutzer ist nicht eingeloggt, der Download aber nur registrierten Benutzern gestattet.<br />- Das Traffickonto des Benutzers weist kein/nicht mehr ausreichenden Traffic auf.<br />- Der Administrator hat eine min. Beitragsgrenze (Forenbeiträge) festgelegt, welche der Benutzer noch nicht erreicht hat.<br />- Das vom Administrator festgelegte max. Trafficlimit für eine Datei ist verbraucht.");
$faq[] = array("Was bedeutet <img border=\"0\" src=\"" . $images['Dl_grey'] . "\" alt=\"\" title=\"\" />?", "Externe Quelle. Der Download erfolgt von einem externen Server. Ansonsten ähnliche Regeln wie bei <img border=\"0\" src=\"" . $images['Dl_green'] . "\" alt=\"\" title=\"\" />. Es erfolgt kein Abzug von Gesamttraffic des Downloadbereiches.");
$faq[] = array("Was bedeutet <img border=\"0\" src=\"" . $images['Dl_white'] . "\" alt=\"\" title=\"\" />?", "Wie auch <img border=\"0\" src=\"" . $images['Dl_green'] . "\" alt=\"\" title=\"\" /> erfolgt hier kein Abzug vom Benutzerkonto. Jedoch können diese Downloads nur registrierte Benutzer frei herunterladen. Es erfolgt dazu auch ein Abzug von Gesamttraffic des Downloadbereiches.");
$faq[] = array("Was bedeutet <img border=\"0\" src=\"" . $images['Dl_yellow'] . "\" alt=\"\" title=\"\" />?", "Download mit Einschränkungen möglich. Der Download ist nur registierten Benutzern gestattet. Der Benutzer muss eingeloggt sein. Es erfolgt ein Trafficabzug vom Benutzerkonto und vom Gesamttraffic des Downloadbereiches.");
$faq[] = array("Was bedeutet <img border=\"0\" src=\"" . $images['Dl_green'] . "\" alt=\"\" title=\"\" />?", "Download frei verfügbar. Der Download unterliegt keinen Restriktionen. Die Datei kann von Gästen heruntergeladen werden. Ein Login ist nicht erforderlich. Es erfolgt kein Trafficabzug vom Benutzerkonto, jedoch vom Gesamttraffic des Downloadbereiches.");
$faq[] = array("Warum kann ich keine Dateien herunterladen?", "Dieses kann mehrere Gründe haben. Siehe unter <img border=\"0\" src=\"" . $images['Dl_blue'] . "\" alt=\"\" title=\"\" /> und <img border=\"0\" src=\"" . $images['Dl_red'] . "\" alt=\"\" title=\"\" />.");
$faq[] = array("Wann und wie wird meinem Konto wieder Traffic gutgeschrieben?", "Nach dem allerersten Login des Benutzers wird ein Zeitstempel gesetzt. Jeweils am ersten Tag eines Monats, an dem ein Benutzer den Downloadbereich betritt, wird automatisch das Traffickonto wieder aufgefüllt. Frage den Administrator, wieviel du erhältst.");
$faq[] = array("Ich möchte noch eine weitere Datei herunterladen, habe aber keinen Traffic mehr?", "In diesem Fall frage den Administrator. Nur er kann entscheiden, ob einem Benutzer vor Ablauf des Monats zusätzlicher Traffic zugewiesen wird.");
$faq[] = array("Wie kann ich einen Download bewerten?", "Bei jedem Download innerhalb einer Kategorie oder in der Detailbeschreibung befindet sich ein Block für Bewertungen.<br />Mit einem Klick auf &quot;Bewerten&quot; kann der registrierte Benutzer nach einem Punktesystem den Download mit 1 Punkt (sehr schlecht) bis 10 Punkte (sehr gut) bewerten. Du kannst einen Download nur einmal bewerten.");

$faq[] = array("--", "Digests");
$faq[] = array("Was sind Digests?", "Digests sind E-Mail Nachrichten, die Dir regelmäßig als Zusammenfassung der hier geschrieben neuen Beiträge zugeschickt werden. Möglich sind wöchentliche oder tägliche Zusammenfassungen.");
$faq[] = array("Warum sollte ich einen Digest wollen?", "Es macht dein Leben einfacher. Man muss nicht dauernd diese Site besuchen, um zu sehen, was für Diskussionen hier geführt werden. einfach den Digest lesen und sehen, ob ein Thema dabei ist, dass interessant zu sein scheint, darauf klicken im E-Mail-Programm und mit diskutieren! Der Digest kann jederzeit abbestellt werden.");
$faq[] = array("Wie oft werden Digests versendet?", "Das entscheidet man selbst. Jeder Benutzer wählt beim Einrichten seines Digests selbst, ob er sie täglich oder wöchentlich erhalten möchte. Wöchentliche Digests werden jeweils sonntags versendet.");
$faq[] = array("Wann werden Digests versendet?", "Du legst selbst fest, zu welcher Uhrzeit du Digests empfangen möchtest. Zu der Zeit die du wählst erhältst du immer die neuesten Nachrichtenzusammenfassung.");
$faq[] = array("Zu welchen Uhrzeiten werden Digest versendet?", "Entweder alle 24 Stunden oder alle 7 Tage, abhängig davon, ob du tägliche oder wöchentliche Digests gewählt hast. Die Beiträge, die älter als dieses sind, werden nicht gesendet. Zusätzlich kannst du auswählen, dass nur Beiträge seit deinem letzten Forumbesuch gesendet werden. Du kannst auch deine eigenen Beiträge heraus filtern.");
$faq[] = array("Falls ich nicht eine Übersicht aller Nachrichten haben möchte, kann ich selektieren?", "Ja. Man kann wählen, an welchen Foren man interessiert ist. Standardmäßig bekommt man Nachrichten für alle Foren, auf die man zugreifen darf.");
$faq[] = array("Welches E-Mail-Nachrichten-Format ist verfügbar?", "Wir können Dir HTML- oder Textnachrichten schicken. Wir empfehlen HTML. Nur, falls dein E-Mail-Programm nicht mit HTML umgehen kann, (heutzutage recht ungewöhnlich) empfehlen wir Textnachrichten. Sie sehen allerdings nicht so gut aus (einfacher Text) und sind daher schwerer zu lesen.");
$faq[] = array("Bekomme ich den vollständigen Beitragstext im Digest?", "Standardmäßig werden die ersten 150 Zeichen des Textes angezeigt. Man kann aber auch auswählen, den gesamten Text oder nur den Thementitel zu sehen. Wir empfehlen, die Standardlänge eingestellt zu lasse, da der Digest sonst leicht so groß wird, dass er unbenutzbar wird. Es wurde auch schon gemeldet, dass sehr große Digests von den ISP's zurückgewiesen wurden oder die Server Speichergrenzen überschritten. Ein Auszug vermindert die benötigte Bandbreite und liefert im Allgemeinen alles, was man braucht. Warum? Weil jede Nachricht einen bequemen Link enthält, der direkt zu dem Thema oder der Nachricht führt.");
$faq[] = array("Wie kann ich anfangen?", "Einfach auf den Digests-Link in der linken Navigation anklicken oder wenn einfach hier klicken: <a href=\"./digests.php\">Digests</a>.");
$faq[] = array("Kann ich einen Digest wieder abmelden?", "Natürlich! Einfach auf die gleiche Seite gehen und &quot;Diesen Digest löschen&quot; auswählen. Dann das Formular abschicken und die Eintragung für diesen Digest endet sofort.");
$faq[] = array("Sind die Digests werbefrei?", "Natürlich. Es gibt keine nervenden Werbungen und es wird auf dieser Seite nie welche geben.");
$faq[] = array("Sind meine persönlichen Daten geschützt?", "Ja. Der Digest wird an die E-Mail Adresse geschickt, die im persönlichen Profil angegeben wurde. Dieser Digest ist nichts anderes als eine Zeitungs-Sonderausgabe, speziell für Dich zusammengestellt. Jemand anders bekommt vermutlich einen völlig anderen Digest.");


$faq[] = array("--", "Ungelesene Post Information 2 Database (UPI2DB)");
$faq[] = array("Was ist der Unterschied zwischen dem Cookie und dem UPI2DB System?", "Das Cookie System ist das Standard System von phpBB2 Foren. Wenn du einen Beitrag liest wird eine Information als Cookie auf Deinen Rechner gespeichert die besagt das du diesen Beitrag gelesen hast. Der so ziemlich größte Nachteil von diesem System ist das ungewollte &quot;als gelesen markieren&quot; der Beiträge beim Schließen oder Absturz des Browsers. Das UPI2DB System speichert die Information nicht als Cookie auf den Rechner sondern in die Datenbank");
$faq[] = array("Was sind die Vor und Nachteile vom Cookie System?", "<strong>Vorteil:</strong> Bei größeren Foren ist ein schnellerer Seitenaufbau zu erwarten, als gegenüber dem UPI2DB System, da die Informationen über gelesene Beiträge nicht erst aus der Datenbank ausgelesen werden müssen. Ein weiterer Vorteil ist, dass die Daten über viele Monate gespeichert bleiben, sofern man sie nicht selber vom Rechner löscht. Die ist für Benutzer interessant, die nur alle 2 Monate mal ins Forum schauen.<br /><strong> Nachteil:</strong> Der so ziemlich größte Nachteil von diesem System ist das ungewollte als gelesen markieren der Beiträge beim Schließen oder Absturz des Browsers. Ein weiterer Nachteil ist, dass bearbeitete Beiträge nicht als neu gekennzeichnet werden und somit in den meisten Fällen unbeachtet bleiben.");
$faq[] = array("Was sind die Vor und Nachteile vom UPI2DB System?", "<strong>Vorteil:</strong> Nicht gelesene Beiträge bleiben auch dann als &quot;ungelesen&quot; markiert, wenn man den Browser schließt. Man muss also nicht alle Beiträge innerhalb einer Sitzung lesen. Beiträge können auch mit dem UPI2DB System für eine Zeit von " . (!empty($config['upi2db_auto_read']) ? $config['upi2db_auto_read'] : 0) . " Tagen &quot;als gelesen markiert&quot; werden. Foren die nicht für Dich interessant sind, können als &quot;permanent gelesen&quot; markiert werden, bis du diese Einstellung änderst. bearbeitete Beiträge werden mit dem Hinweis &quot;bearbeitet&quot; als ungelesen angezeigt und in der Beitragsübersicht mit einer gesonderten Farbe angezeigt. Dazu gibt es eine Suchfunktion,  die es erlaubt nur &quot;ungelesene/bearbeitete&quot; Beiträge, &quot;markierte&quot; Beiträge oder &quot;permanent als gelesen&quot; markierten Themen anzuzeigen. Wenn vom Admin aktiviert, werden bearbeitete Beiträge in der Themen Ansicht als erstes einsortiert angezeigt.<br /><strong>Nachteil:</strong> Bei größeren Foren mit vielen Beiträgen und Benutzern kann es zu einen langsameren Seitenaufbau kommen. Die Information, ob ein Beitrag gelesen wurde, bleibt nur über eine gewisse Zeit gespeichert, danach werden Beiträge automatisch als gelesen markiert. Der Standard-Zeitraum ist 30 Tage. Die Zeitspanne kann aber vom Admin jederzeit geändert werden.");
$faq[] = array("Ich sehe in meinen Profil keine Auswahlmöglichkeit zum Einstellen des Cookie oder UPI2DB Systems", "Wenn du keine Einstellmöglichkeit findest, ist das UPI2DB System vom Admin entweder auf permanent &quot;Ein&quot; oder &quot;Aus&quot; geschaltet worden. Du hast dann keine Möglichkeit, diese Einstellung zu ändern.");
$faq[] = array("Welche Bedingungen zur Benutzung des UPI2DB Systems kann der Admin einstellen?", "Standardmäßig erlaubt das UPI2DB System dem Admin die Option einzustellen, ab wie vielen Beiträge ein Benutzer das System nutzen darf und/oder wie lange ein Benutzer registriert sein muss, bevor er das UPI2DB System nutzen kann.");
$faq[] = array("Egal was ich versuche, ich kann Wichtige Themen und Ankündigungen nicht als gelesen markieren!", "Wichtige Themen und Ankündigungen müssen besucht werden. Sie lassen sich daher nicht mit den Funktionen &quot;Alle Foren/Themen als gelesen markieren&quot; und in der &quot;Ungelesenen Beiträge anzeigen&quot; Ansicht als gelesen markieren!");
$faq[] = array("Ich muss alle " . (!empty($config['upi2db_auto_read']) ? $config['upi2db_auto_read'] : 0) . " Tage ein Thema &quot;als permanent gelesen&quot; markieren!", "So soll es auch sein und du kannst dies nicht ändern. Wir mussten da einen Kompromiss eingehen, um das System nicht zu sehr zu verlangsamen!");
$faq[] = array("Wie kann ich ein Forum auf &quot;permanent gelesen&quot; setzen?", "Einfach auf das Bild vor dem Forumnamen klicken. Als Rückmeldung ändert sich dann das Bild");
$faq[] = array("Wie kann ich ein Thema auf &quot;permanent gelesen&quot; setzen?", "Einfach auf das Bild vor dem Themennamen klicken. Als Rückmeldung ändert sich dann das Bild und das Thema springt an die letzte Stelle in der Themenübersicht. Alternativ kannst du auch im Thema ganz unten auf &quot;Thema permanent als gelesen markieren&quot; klicken.");
$faq[] = array("Ich kann Wichtige Themen und Ankündigungen nicht auf &quot;permanent gelesen&quot; setzen!", "Wichtige Themen und Ankündigungen können nicht &quot;permanent als gelesen&quot; markiert werden!");
$faq[] = array("Ich hatte ein Forum auf &quot;permanent gelesen&quot; gesetzt und nun zeigt es mir wieder eine neues Thema an!", "Wenn Wichtige Themen oder Ankündigungen gepostet werden, werden die &quot;permanent als gelesen&quot; markierten Foren wieder zurückgesetzt. Dies ist notwendig damit du keine wichtigen Themen und Ankündigungen verpasst.");
$faq[] = array("Wie kann ich ein Beitrag markieren, um ihn später wieder leichter zu finden?", "In jedem Beitrag gibt es eine Schaltfläche im Beitragstitel. Diese erlaubt Dir, diesen Beitrag zu markieren. Beiträge, die älter als " . (!empty($config['upi2db_auto_read']) ? $config['upi2db_auto_read'] : 0) . " Tage sind oder die geschrieben wurden, bevor du dich registriert hast, lassen sich nicht markieren.");
$faq[] = array("Wie hebe ich eine Markierung wieder auf? Nur lesen reicht nicht.", "Nein, markierte Beiträge müssen manuell &quot;demarkiert&quot; werden. Die Schaltfläche findest du an derselben Stelle, wie die &quot;markieren&quot; Schaltfläche.");
$faq[] = array("Warum kann ich manche Beiträge nicht markieren?", "Beiträge, die in einem &quot;als permanent gelesen&quot; markierten Thema oder Forum sind und Beiträge, die erstellt wurden, bevor du dich registriert hast, kannst du nicht markieren. Beiträge, die älter sind als " . (!empty($config['upi2db_auto_read']) ? $config['upi2db_auto_read'] : 0) . " Tage lassen sich ebenfalls nicht markieren.");
$faq[] = array("Bleiben markierte Beiträge für immer markiert?", "Nein, die Markierung werden automatisch nach " . (!empty($config['upi2db_del_mark']) ? $config['upi2db_del_mark'] : 0) . " Tagen gelöscht");
$faq[] = array("Was bedeutet AGM?", "Das ist die Abkürzung für &quot;Als gelesen markieren&quot;");


$faq[] = array("--", "phpBB 2 Issues");
$faq[] = array("Who wrote this bulletin board?", "This software (in its unmodified form) is produced, released and is copyrighted <a href=\"http://www.phpbb.com/\" target=\"_blank\">phpBB Group</a>. It is made available under the GNU General Public License and may be freely distributed; see link for more details");
$faq[] = array("Why isn't X feature available?", "This software was written by and licensed through phpBB Group. If you believe a feature needs to be added then please visit the phpbb.com website and see what the phpBB Group has to say. Please do not post feature requests to the board at phpbb.com, as the Group uses sourceforge to handle tasking of new features. Please read through the forums and see what, if any, our position may already be for features and then follow the procedure given there.");
$faq[] = array("Whom do I contact about abusive and/or legal matters related to this board?", "You should contact the administrator of this board. If you cannot find who that is, you should first contact one of the forum moderators and ask them who you should in turn contact. If still get no response you should contact the owner of the domain (do a whois lookup) or, if this is running on a free service (e.g. yahoo, free.fr, f2s.com, etc.), the management or abuse department of that service. Please note that phpBB Group has absolutely no control and cannot in any way be held liable over how, where or by whom this board is used. It is absolutely pointless contacting phpBB Group in relation to any legal (cease and desist, liable, defamatory comment, etc.) matter not directly related to the phpbb.com website or the discrete software of phpBB itself. If you do email phpBB Group about any third party use of this software then you should expect a terse response or no response at all.");


$faq[] = array("--", "Über Icy Phoenix");
$faq[] = array("Was ist Icy Phoenix?", "Icy Phoenix ist ein CMS (Content Management System). Die Benutzer können damit leicht eine dynamische Website mit verschiedenen eingebauten Funktionen: Forum, Portal, anpassbare Seiten und Blöcke, Downloads, Foto-Galerie und vielem mehr.");
$faq[] = array("Wer schrieb diese Software?", "Diese Software basiert auf phpBB die unter der GNU General Public License veröffentlicht wurde. Deshalb wurde Icy Phoenix unter derselben License veröffentlicht. Das bedeutet, dass auch Icy Phoenix frei verändert und ausgetauscht werden kann. Das Kernstück, die phpBB Dateien, wurden größtenteils von Mighty Gorgon und dem <a href=\"http://www.icyphoenix.com/\" target=\"_blank\">Icy Phoenix Team</a> programmiert oder verändert. Eine nicht ganz vollständige Liste der Mitwirkenden könnt ihr hier finden: <a href=\"http://www.icyphoenix.com/hacks_list.php\" target=\"_blank\">Icy Phoenix Credits</a>.");
$faq[] = array("Whom do I contact about abusive and/or legal matters related to this site?", "You should contact the webmaster. If you cannot find who that is, you should first contact one of the forum moderators and ask them who you should in turn contact. If still get no response you should contact the owner of the domain (do a whois lookup) or, if this is running on a free service (e.g. yahoo, free.fr, f2s.com, etc.), the management or abuse department of that service. Please note that Icy Phoenix has absolutely no control and cannot in any way be held liable over how, where or by whom this site is used. It is absolutely pointless contacting Icy Phoenix in relation to any legal (cease and desist, liable, defamatory comment, etc.) matter not directly related to the icyphoenix.com website or the discrete software of Icy Phoenix itself. If you do email Icy Phoenix about any third party use of this software then you should expect a terse response or no response at all.");


?>