<?php
/**
*
* @package Icy Phoenix
* @version $Id$
* @copyright (c) 2008 Icy Phoenix
* @license http://opensource.org/licenses/gpl-license.php GNU Public License
*
*/

if (!defined('IN_ICYPHOENIX'))
{
	exit;
}

//
// To add an entry to your BBCode guide simply add a line to this file in this format:
// $faq[] = array("question", "answer");
// If you want to separate a section enter $faq[] = array("--","Block heading goes here if wanted");
// Links will be created automatically
//
// DO NOT forget the ; at the end of the line.
// Do NOT put double quotes (") in your BBCode guide entries, if you absolutely must then escape them ie. \"something\"
// The BBCode guide items will appear on the BBCode guide page in the same order they are listed in this file
// If just translating this file please do not alter the actual HTML unless absolutely necessary, thanks :)
//
// In addition please do not translate the colours referenced in relation to BBCode any section, if you do
// users browsing in your language may be confused to find they're BBCode doesn't work :D You can change
// references which are 'in-line' within the text though.
//


$faq[] = array("--","Introduzione");
$faq[] = array("Cos'&egrave; il BBCode?", "BBCode &egrave; un ampliamento speciale del codice HTML. L'uso del BBCode nei tuoi messaggi &egrave; determinato dall'amministratore. Inoltre puoi disabilitare il BBCode in ogni messaggio attraverso il modulo di invio. Il BBCode ha uno stile simile all'HTML, i tag sono racchiusi in parentesi quadre [ e ] piuttosto che in &lt; e &gt; e offre grande controllo su cosa e come vogliamo mostrare il messaggio. La facilit&agrave; di utilizzo del BBCode nei tuoi messaggi dipende dal modello che stai utilizzando. Per ogni problema puoi far riferimento a questa guida.");


$faq[] = array("--","Formattazione del Testo");
$faq[] = array("Come creare il testo in grassetto, sottolineato o corsivo", "Il BBCode include dei tag per permetterti di cambiare velocemente lo stile di base del tuo testo. Questo avviene nel seguente modo: <ul><li>Per il testo in grassetto usa <b>[b][/b]</b>, es. <br /><br /><b>[b]</b>Ciao<b>[/b]</b><br /><br >diventer&agrave; <b>Ciao</b></li><li>Per il testo sottolineato usa<b>[u][/u]</b>, es.:<br /><br /><b>[u]</b>Buon Giorno<b>[/u]</b><br /><br />diventa <u>Buon Giorno</u></li><li>Per il testo in corsivo usa<b>[i][/i]</b>, es.<br /><br >Questo &egrave; <b>[i]</b>Grande!<b>[/i]</b><br /><br />diventa Questo &egrave; <i>Grande!</i></li></ul>");
$faq[] = array("Posso allineare il testo?", "Certamente, puoi allinearlo a sinistra, al centro, a destra e giustificarlo. Ti basta usare i seguenti tags: <b>[align=left]</b>ALLINEAMENTO A SINISTRA<b>[/align]</b>, <b>[align=center]</b>ALLINEAMENTO AL CENTRO<b>[/align]</b>, <b>[align=right]</b>ALLINEAMENTO A DESTRA<b>[/align]</b>, <b>[align=justify]</b>GIUSTIFICA IL TESTO<b>[/align]</b>.");
$faq[] = array("Come cambiare il colore o la dimensione del testo", "Per modificare il colore o la dimensione del testo puoi usare i seguenti tags. Ricordati che queste impostazioni dipendono dal browser e dal sistyema di chi guarda il messaggio: <ul><li>Per cambiare il colore del testo racchiudilo tra <b>[color=][/color]</b>. Puoi anche specificare un nome di colore conosciuto (es. rosso, blu, giallo, ecc.) o alternativamente il codice esadecimale, es. #FFFFFF, #000000. Per esempio, per creare un testo rosso puoi usare:<br /><br /><b>[color=red]</b>Ciao!<b>[/color]</b><br /><br />or<br /><br /><b>[color=#FF0000]</b>Ciao!<b>[/color]</b><br /><br />entrambi danno come risultato <span style=\"color:red\">Ciao!</span></li><li>Per cambiare la dimensione del testo usa <b>[size=][/size]</b>. Questo tag dipende dal modello che stai usando ma il formato raccomandato &egrave; un valore numerico che rappresenti la dimensione del testo in pixels, iniziando da 1 (cos&igrave; piccolo che non si riesce a vedere) fino a 29 (molto grande). Per esempio:<br /><br /><b>[size=9]</b>PICCOLO<b>[/size]</b><br /><br />generalmente &egrave; <span style=\"font-size:9px\">PICCOLO</span><br /><br />mentre:<br /><br /><b>[size=24]</b>ENORME!<b>[/size]</b><br /><br />sar&agrave; <span style=\"font-size:24px\">ENORME!</span></li></ul>");
$faq[] = array("Posso combinare i tags di formattazione?", "S&igrave;, certo, per esempio per richiamare l'attenzione puoi scrivere:<br /><br /><b>[size=18][color=red][b]</b>GUARDAMI!<b>[/b][/color][/size]</b><br /><br />cio&egrave; <span style=\"color:red;font-size:18px\"><b>GUARDAMI!</b></span><br /><br />Ti consigliamo di non usare troppo testo come questo, comunque! Ricorda che tu, l'autore, devi assicurarti che tutti i tags siano chiusi in modo corretto. Per esempio, quello che segue non &egrave; corretto:<br /><br /><b>[b][u]</b>Questo &egrave; sbagliato<b>[/b][/u]</b>");
$faq[] = array("Posso far scorrere del testo?", "S&igrave;, certo, pu&ograve; scorrere a sinistra, destra, in altro e in basso. Per esempio per far scorrere del testo a sinistra puoi scrivere:<br /><br /><b>[marquee direction=left]</b>SINISTRA!<b>[/marquee]</b>");
$faq[] = array("Posso usare altri tags per il testo?", "Puoi usare l'Apice e il Pedice con i tags: <b>[sup]</b>APICE<b>[/sup]</b> e <b>[sub]</b>PEDICE<b>[/sub]</b>, es. <br /><br /><b>[sup]</b>APICE<b>[/sup]</b><br /><br >diventer&agrave; <sup>APICE</sup> e <br /><br /><b>[sub]</b>PEDICE<b>[/sub]</b><br /><br >diventer&agrave; <sub>PEDICE</sub><br /><br >Puoi evidenziare del testo con il tags: <b>[highlight=#FFFFAA]</b>TESTO DA EVIDENZIARE<b>[/highlight]</b>, puoi sfumarlo con il tags: <b>[opacity]</b>TESTO DA SFUMARE<b>[/opacity]</b> e puoi renderlo gradiente con il tags: <b>[rainbow]</b>TESTO GRADIENTE<b>[/rainbow]</b><br /><br />Ricorda che devi assicurarti che tutti i tags siano chiusi in modo corretto, altrimenti la visualizzazione della pagina potrebbe non essere corretta e potrebbe anche violare le richieste del W3C sulla formattazione delle pagine. Per esempio, quello che segue non &egrave; corretto:<br /><br /><b>[b][u]</b>Questo &egrave; sbagliato<b>[/b][/u]</b>");


$faq[] = array("--","Citazioni e testo a larghezza fissa");
$faq[] = array("Citazioni di testo nelle risposte", "Ci sono due modi per fare una citazione, con un referente o senza.<ul><li>Quando utilizzi la funzione Citazione per rispondere ad un messaggio sul forum devi notare che il testo del messaggio viene incluso nella finestra del messaggio tra <b>[quote=\"\"][/quote]</b>. Questo metodo ti permette di fare una citazione riferendoti ad una persona o qualsiasi altra cosa che hai deciso di inserire! Per esempio, per citare un pezzo di testo di Mr. Blobby devi inserire:<br /><br /><b>[quote=\"Mr. Blobby\"]</b>Il testo di Mr. Blobby andr&agrave; qui<b>[/quote]</b><br /><br />Nel messaggio verr&agrave; automaticamente aggiunto, Mr. Blobby ha scritto: prima del testo citato. Ricorda che tu <b>devi</b> includere le parentesi \"\" attorno al nome che stai citando, non sono opzionali.</li><li>Il secondo metodo ti permette di citare qualcosa alla cieca. Per utilizzare questo metodo, racchiudi il testo tra i tags <b>[quote][/quote]</b>. Quando vedrai il messaggio comparir&agrave; semplicemente, Citazione: prima del testo stesso.</li></ul>");
$faq[] = array("Mostrare il codice", "Se vuoi mostrare un pezzo di codice o qualcosa che ha bisogno di una larghezza fissa, es. Courier devi racchiudere il testo tra i tags <b>[code][/code]</b>, es.<br /><br /><b>[code]</b>echo \"Questo &egrave; un codice\";<b>[/code]</b><br /><br />Tutta la formattazione utilizzata tra i tags <b>[code][/code]</b> viene mantenuta quando viene visualizzata in seguito.");


$faq[] = array("--","Creazione di liste e linea");
$faq[] = array("Creare una lista non ordinata", "BBCode supporta due tipi di liste, ordinate e non. Sono essenzialmente la stessa cosa del loro equivalente in HTML. Una lista non ordinata mostra ogni oggetto nella tua lista in modo sequenziale, uno dopo l'altro inserendo un punto per ogni riga. Per creare una lista non ordinata usa <b>[list][/list]</b> e definisci ogni oggetto nella lista usando <b>[*]</b>. Per esempio per fare una lista dei tuoi colori preferiti puoi usare:<br /><br /><b>[list]</b><br /><b>[*]</b>Rosso<br /><b>[*]</b>Blu<br /><b>[*]</b>Giallo<br /><b>[/list]</b><br /><br />Questo mostrer&agrave; questa lista:<ul><li>Rosso</li><li>Blu</li><li>Giallo</li></ul>");
$faq[] = array("Creare una lista ordinata", "Una lista ordinata ti permette di controllare il modo in cui ogni oggetto della lista viene mostrato. Per creare una lista ordinata usa <b>[list=1][/list]</b> per creare una lista numerata o alternativamente <b>[list=a][/list]</b> per una lista alfabetica. Come per la lista non ordinata gli oggetti vengono specificati utilizzando <b>[*]</b>. Per esempio:<br /><br /><b>[list=1]</b><br /><b>[*]</b>Vai al negozio<br /><b>[*]</b>Compra un nuovo computer<br /><b>[*]</b>Impreca sul computer quando si blocca<br /><b>[/list]</b><br /><br />verr&agrave; mostrato cos&igrave;:<ol type=\"1\"><li>Vai al negozio</li><li>Compra un nuovo computer</li><li>Impreca sul computer quando si blocca</li></ol>mentre per una lista alfabetica devi usare:<br /><br /><b>[list=a]</b><br /><b>[*]</b>La prima risposta possibile<br /><b>[*]</b>La seconda risposta possibile<br /><b>[*]</b>La terza risposta possibile<br /><b>[/list]</b><br /><br />sar&agrave;<ol type=\"a\"><li>La prima risposta possibile</li><li>La seconda risposta possibile</li><li>La terza risposta possibile</li></ol>");
$faq[] = array("Linea orizzontale", "Per aggiungere una linea orizzontale, ti basta inserire il tag <b>[hr]</b>.");


$faq[] = array("--", "Creare Links");
$faq[] = array("Linkare un altro sito", "Il BBCode di Icy Phoenix supporta diversi modi per creare URI, Uniform Resource Indicators meglio conosciuti come URL.<ul><li>Il primo di questi utilizza il tag <b>[url=][/url]</b>, qualunque cosa digiti dopo il segno = generer&agrave; il contenuto del tag che si comporter&agrave; come URL. Per esempio per linkarsi a phpBB.com devi usare:<br /><br /><b>[url=http://www.phpbb.com/]</b>Visita phpBB!<b>[/url]</b><br /><br />Questo genera il seguente link, <a href=\"http://www.phpbb.com/\" target=\"_blank\">Visita phpBB!</a> Come puoi vedere il link si apre in una nuova finestra cos&igrave; l'utente pu&ograve; continuare a navigare nei forum.</li><li>Se vuoi che l'URL stesso venga mostrato come link puoi fare questo semplicemente usando:<br /><br /><b>[url]</b>http://www.phpbb.com/<b>[/url]</b><br /><br />Questo genera il seguente link, <a href=\"http://www.phpbb.com/\" target=\"_blank\">http://www.phpbb.com/</a></li><li>Inoltre phpBB dispone di una cosa chiamata <i>Magic Links</i>, questo cambier&agrave; ogni URL sintatticamente corretta in un link senza la necessit&agrave; di specificare nessun tag o http://. Per esempio digitando www.phpbb.com nel tuo messaggio automaticamente verr&agrave; cambiato in <a href=\"http://www.icyphoenix.com/\" target=\"_blank\">www.icyphoenix.com</a> e verr&agrave; mostrato nel messaggio finale.</li><li>La stessa cosa accade per gli indirizzi email, puoi specificare un indirizzo esplicitamente, per esempio:<br /><br /><b>[email]</b>no.one@domain.adr<b>[/email]</b><br /><br />che mostrer&agrave; <a href=\"emailto:no.one@domain.adr\">no.one@domain.adr</a> o puoi digitare no.one@domain.adr nel tuo messaggio e verr&agrave; automaticamente convertito.</li></ul>Come per tutti i tag del BBCode puoi includere le URL in ogni altro tag come <b>[img][/img]</b> (guarda il successivo punto), <b>[b][/b]</b>, ecc. Come per i tag di formattazione dipende da te verificare che tutti i tag siano correttamente aperti e chiusi, per esempio:<br /><br /><b>[url=http://www.icyphoenix.com/][img]</b>http://www.icyphoenix.com/images/logo_ip.png<b>[/url][/img]</b><br /><br /> <u>non</u> &egrave; corretto e potrebbe cancellare il tuo messaggio. quindi presta attenzione. ");


$faq[] = array("--", "Mostrare immagini nei messaggi");
$faq[] = array("Aggiungere una immagine al messaggio", "Il BBCode di Icy Phoenix incorpora un tag per l'inclusione di immagini nei tuoi messaggi. Ci sono due cose importanti da ricordare nell'usare questo tag; a molti utenti non piacciono molte immagini nei messaggi e in secondo luogo l'immagine deve essere gi&agrave; disponibile su internet (non pu&ograve; esistere solo sul tuo computer per esempio, a meno che tu non abbia un webserver!). Non c'&egrave; modo di salvare le immagini localmente con phpBB (forse nella prossima release di phpBB). Per mostrare delle immagini devi inserire l'URL che rimanda all'immagine con il tag <b>[img][/img]</b>. Per esempio:<br /><br /><b>[img]</b>http://www.icyphoenix.com/images/logo_ip.png<b>[/img]</b><br /><br />Puoi inserire un'immagine nel tag <b>[url][/url]</b> se vuoi, es.<br /><br /><b>[url=http://www.icyphoenix.com/][img]</b>http://www.icyphoenix.com/images/logo_ip.png<b>[/img][/url]</b><br /><br />genera:<br /><br /><a href=\"http://www.icyphoenix.com/\" target=\"_blank\"><img src=\"http://www.icyphoenix.com/images/logo_ip.png\" border=\"0\" alt=\"\" /></a><br /><br />Puoi anche allineare le immagini come preferisci, utilizzando i tags <b>[img align=left][/img]</b> per allinearla a sinistra e <b>[img align=right][/img]</b> per allinearla a destra.<br /><br />Se vuoi sfumare un immagine, puoi utilizzare il tag <b>[opacity][img]</b>URL DELL'IMMAGINE<b>[/img][/opacity]</b>");
$faq[] = array("Aggiungere al messaggio un immagine presente nell'album", "Se vuoi aggiungere al tuo messaggio un immagine presente nell'album del forum, &egrave; presente un apposito tag <b>[albumimg]</b>ID<b>[/albumimg]</b>, in questo tag non dovrai immettere un URL che rimanda all'immagine ma baster&agrave; inserire l'ID che troverai visualizzando l'immagine stessa all'interno dell'album. Puoi anche sceglere di allinearla a sinistra con il tag <b>[albumimg align=left]</b>ID<b>[/albumimg]</b> o a destra con il tag <b>[albumimg align=right]</b>ID<b>[/albumimg]</b>");


$faq[] = array("--", "Multimedialit&agrave; nei messaggi");
$faq[] = array("Aggiungere un video o audio ai messaggi", "In questo forum puoi inserire quasi tutti i tipi di multimedia. Video in formato Windows Media Video, Quick Time e Real Media, filmati Flash anche da YouTube e GoogleVideo, audio in streaming ed MP3. Espempi pratici:<br /><br />Per inserire un video in formato <b>.wmv</b>, puoi usare il tag <b>[video width=320 height=240]</b>URL DEL FILE DEL VIDEO<b>[/video]</b>.<br /><br />Per inserire un video <b>.mov</b>, il formato Quick Time, ti basta inserire il tag <b>[quick]</b>URL DEL FILE VIDEO<b>[/quick]</b>, mentre per i filmati Real Media puoi utilizzare il tag <b>[ram]</b>URL DEL FILE RM<b>[/ram]</b><br /><br />Puoi aggiungere ai tuoi messaggi filmati in Adobe Flash <b>.swf</b> con il tag <b>[flash width=320 height=240]</b>URL DEL FILE FLASH<b>[/flash]</b>.<br /><br />Per i file Video, Flash, e possibile specificare anche la larghezza e l'altezza modificando all'interno del tag la parte <b>width=320 height=240</b><br /><br />Se invece vuoi condividere con gli altri utenti del forum un video caricato o visualizzato su GoogleVideo o YouTube, ti basta utilizzare il tag <b>[googlevideo]</b>ID<b>[/googlevideo]</b> per i video di Google e <b>[youtube]</b>ID<b>[/youtube]</b> per i video provenienti da YouTube.<br /><br />In entrambi i casi, non dovrai inserire l'URL del video ma solo l'ID, esempio di URL di YouTube <b>http://www.youtube.com/watch?v=icyphoenix2007_1</b>, ti baster&agrave; inserire <b>[youtube]</b>icyphoenix2007_1<b>[/youtube]</b>, stesso discorso per GoogleVideo, se l'URL &egrave; <b>http://video.google.it/videoplay?docid=1234567890</b>, dovrai inserire <b>[googlevideo]</b>1234567890<b>[/googlevideo]</b>.<br /><br />Per file audio o in formato MP3, usa i tags: <b>[stream]</b>URL DEL FILE AUDIO<b>[/stream]</b> e <b>[emff]</b>URL DEL FILE MP3<b>[/emff]</b><br /><br />Tutti i marchi citati, appartengono ai rispettivi proprietari.");


$faq[] = array("--", "Altro");
$faq[] = array("Posso aggiungere i miei tag personali?", "No, non direttamente tramite il pannello di amministrazione. Se conosci il PHP puoi provare a modificare il file <b>includes/bbcode.php</b> per aggiungere altri tags.");

// This ends the BBCode guide entries

?>