<?php
/**
*
* @package Icy Phoenix
* @version $Id$
* @copyright (c) 2008 Icy Phoenix
* @license http://opensource.org/licenses/gpl-license.php GNU Public License
*
*/

/**
*
* @Icy Phoenix is based on phpBB
* @copyright (c) 2008 phpBB Group
*
*/

/**
*
* @Extra credits for this file
* Lopalong
*
*/

if (!defined('IN_ICYPHOENIX'))
{
	exit;
}

//
// To add an entry to your FAQ simply add a line to this file in this format:
// $faq[] = array("question", "answer");
// If you want to separate a section enter $faq[] = array("--","Block heading goes here if wanted");
// Links will be created automatically
//
// DO NOT forget the ; at the end of the line.
// Do NOT put double quotes (") in your FAQ entries, if you absolutely must then escape them ie. \"something\"
// The FAQ items will appear on the FAQ page in the same order they are listed in this file


$faq[] = array("--","Acerca del inicio de cuenta (login) y registro");
$faq[] = array("&iquest;Por qu&eacute; no puedo iniciar mi cuenta?", "&iquest;Ya se registr&oacute;? Debe registrarse en el sistema antes de poder acceder a &eacute;l. &iquest;Ha sido bloqueado en el foro? (si es as&iacute;, le aparecer&aacute; un mensaje). Si le ha sucedido eso, env&iacute;e un mensaje al administrador del foro para saber la causa. Si se ha registrado y no ha sido bloqueado, compruebe que su nombre de usuario y contrase&ntilde;a coincidan, es el problema m&aacute;s com&uacute;n. Si est&aacute; seguro de que est&aacute;n correctos los datos, env&iacute;e un mensaje al administrador, quiz&aacute; el foro est&eacute; mal configurado y/o tenga fallos en la programaci&oacute;n.");
$faq[] = array("&iquest;Por qu&eacute; me tengo que registrar para todo?", "No est&aacute; obligado a hacerlo, la decisi&oacute;n la toman los administradores y moderadores. Sin embargo, estar registrado le da muchas ventajas que como usuario invitado no disfrutar&iacute;a, como tener su gr&aacute;fico personalizado (avatar), mensajes privados, suscripci&oacute;n a grupos de usuarios, etc.... S&oacute;lo le tomar&aacute; unos segundos, es muy recomendable.");
$faq[] = array("&iquest;Por qu&eacute; mi sesi&oacute;n de usuario/a expira autom&aacute;ticamente?", "Si no activa la casilla <i>Ingresar autom&aacute;ticamente</i> cuando ingresa al foro, sus datos se guardan en una cookie que se elimina al salir de la p&aacute;gina o tras cierto tiempo. Esto previene que su cuenta pueda ser usada por alguien m&aacute;s. Para que el sistema le reconozca autom&aacute;ticamente, basta con que active la casilla al ingresar. NO es recomendable si accede al foro desde un ordenador compartido (cibercaf&eacute;, biblioteca, colegio, etc).");
$faq[] = array("&iquest;C&oacute;mo evito aparecer en las listas de usuarios/as conectados/as?", "En su perfil encontrar&aacute; la opci&oacute;n <i>Ocultar mi estado de conexi&oacute;n</i>. Si activa esta opci&oacute;n aparecer&aacute; solo para los administradores, moderadores y para s&iacute; mismo; para los dem&aacute;s ser&aacute; un usuario oculto.");
$faq[] = array("&iexcl;He perdido mi contrase&ntilde;a!", "Calma, si su contrase&ntilde;a no puede ser recuperada puede desactivarla o cambiarla. Para hacer esto dir&iacute;jase a la p&aacute;gina de registro y pulse en <u>Olvid&eacute; mi contrase&ntilde;a</u>, siga las instrucciones, y estar&aacute; dentro en muy poco tiempo");
$faq[] = array("&iexcl;Me he registrado y no puedo ingresar!", "Primeramente compruebe sus datos (usuario y contrase&ntilde;a). Si todo es correcto, hay dos posibles razones. Si el sistema de protecci&oacute;n infantil (COPPA) est&aacute; activado y cuando se registr&oacute; eligi&oacute; la opci&oacute;n <u>Soy menor de 13 a&ntilde;os</u>, entonces tendr&aacute; que seguir algunas instrucciones que se le dar&aacute;n para activar la cuenta. En otros casos, el administrador pide que las cuentas se activen mediante un e-mail, as&iacute; que revise su correo y confirme su suscripci&oacute;n. Algunos foros necesitan confirmaci&oacute;n de registro. Si no sucede nada de esto, contacte con el administrador del foro.");
$faq[] = array("&iexcl;Hace un tiempo me registr&eacute;, pero ahora no puedo ingresar!", "Hay varias razones posibles. Ingres&oacute; un nombre de usuario o contrase&ntilde;a incorrectos (verifique el mensaje que se le envi&oacute; al registrarse). O quiz&aacute; el administrador haya borrado su cuenta: esto es muy frecuente, pues si no ha escrito ning&uacute;n mensaje en cierto tiempo el administrador puede borrar al usuario para que la base de datos no se sature de registros. Si es as&iacute;, reg&iacute;strese de nuevo y participe :)");


$faq[] = array("--","Preferencias de usuario y configuraciones");
$faq[] = array("&iquest;C&oacute;mo puedo cambiar mi configuraci&oacute;n?", "Todos sus datos y configuraciones (si est&aacute; registrado) est&aacute;n archivados en nuestra base de datos. Para modificarlos pulse en el enlace <u>Perfil</u>, generalmente se encuentra arriba de cada p&aacute;gina.");
$faq[] = array("&iexcl;La hora de los foros no es correcta!", "Las horas son correctas, es posible que est&eacute; viendo las horas correspondientes a otra zona horaria. Si ese es el caso, ingrese en su perfil y defina su zona horaria de acuerdo a su ubicaci&oacute;n (ej. Londres, Par&iacute;s, New York, Sydney, etc.). Cambiando esto las horas deben aparecer de acuerdo a su zona y tiempo. Si no se ha registrado, es hora de hacerlo :)");
$faq[] = array("&iexcl;He cambiado la zona horaria en mi perfil, pero la hora sigue siendo incorrecta!", "Si est&aacute; segur@ de que la zona horaria es correcta, es posible que se deba a los horarios de verano implementados por algunos pa&iacute;ses.");
$faq[] = array("&iexcl;Mi idioma no est&aacute; en la lista!", "Esto se puede deber a que el administrador no ha instalado el paquete de su idioma para el foro, o nadie ha creado una traducci&oacute;n: (Si es as&iacute;, si&eacute;ntase libre de hacer una traducci&oacute;n (miles de personas se lo agradecer&aacute;n); encuentre informaci&oacute;n sobre esto en la web de Icy Phoenix (Pulse en el enlace que se encuentra al final de la p&aacute;gina)");
$faq[] = array("&iquest;C&oacute;mo puedo poner una imagen bajo mi nombre de usuario?", "Hay dos tipos de im&aacute;genes debajo de su nombre de usuario. La primera es el rango, que est&aacute; asociada con el n&uacute;mero de mensajes que ha escrito en el foro (generalmente son estrellas o bloques). La segunda es el avatar, que es un gr&aacute;fico generalmente &uacute;nico y personal. El administrador decide si se pueden usar o no; si es posible, puede introducirlo en su perfil. En caso de que no exista esa opci&oacute;n, contacte con el administrador y pida que sea activada esa opci&oacute;n :)");
$faq[] = array("&iquest;C&oacute;mo puedo cambiar mi rango?", "No puede cambiar su rango directamente, ya que est&aacute; asociado directamente al n&uacute;mero de mensajes publicados o a su estado de moderador, administrador, u otros rangos especiales. Por favor, no abuse de escribir mensajes innecesariamente para incrementar su rango.");
$faq[] = array("Cuando pulso sobre el enlace de correo me pide que me registre.", "Para poder enviar correo a un usuario via formulario (si el administrador lo tiene activado) necesita estar registrado. As&iacute; se evitar SPAM o mensajes maliciosos de usuarios an&oacute;nimos.");

$faq[] = array("--","Publicaci&oacute;n de mensajes");
$faq[] = array("&iquest;C&oacute;mo puedo publicar un mensaje en el foro?", "F&aacute;cil. Reg&iacute;strese como usuario del foro (pulsando en el enlace de registro, generalmente arriba de cada p&aacute;gina). Tras registrarse, pulse en <i>Enviar nuevo mensaje</i>: se le presentar&aacute; un panel con el que f&aacute;cilmente publicar&aacute; su mensaje :)");
$faq[] = array("&iquest;C&oacute;mo puedo editar o borrar un mensaje?", "Si no es administrador o moderador del foro, s&oacute;lo puede borrar los mensajes que haya enviado usted mismo. Puede editar un mensaje pulsando en <i>editar</i>. Si alguien ya ha respondido a su mensaje, encontrar&aacute; un peque&ntilde;o texto en el suyo diciendo que ha sido modificado y las veces que lo ha hecho; no aparece si fue un moderador o el administrador el que lo edit&oacute; (la mayor&iacute;a de las veces dejan un mensaje aclaratorio).");
$faq[] = array("&iquest;C&oacute;mo puedo agregar una firma a mis mensajes?", "Primero debe crear una firma, lo que puede hacer desde su perfil. Una vez creada, active la opci&oacute;n <i>Agregar firma</i> cuando publique un mensaje. Tambi&eacute;n puede hacer que todos sus mensajes tengan su firma, activando la opci&oacute;n en su perfil.");
$faq[] = array("&iquest;C&oacute;mo creo una encuesta?", "Crear una encuesta es f&aacute;cil. Cuando inicie un nuevo tema ver&aacute; la opci&oacute;n <i>Crear una encuesta</i>. Introduzca los datos de la encuesta, como t&iacute;tulo y opciones. Puede poner l&iacute;mite al n&uacute;mero de participantes (0 es infinito)");
$faq[] = array("&iquest;C&oacute;mo edito o borro una encuesta?", "Si usted inici&oacute; la encuesta puede editarla de la misma manera que un mensaje. Pero esto s&oacute;lo es posible si la encuesta a&uacute;n no tiene respuestas, pues, de tenerlas, s&oacute;lo el administrador o moderadores podr&aacute;n editarla o borrarla");
$faq[] = array("&iquest;Por qu&eacute; no puedo acceder a un foro?", "Algunos foros pueden estar limitados a ciertos usuarios o grupos. Para verlos, leer, escribir, etc., podr&iacute;a necesitar una autorizaci&oacute;n especial que s&oacute;lo el moderador del foro o el administrador del sitio pueden dar, as&iacute; que deber&iacute;a contactar con ellos.");
$faq[] = array("&iquest;Por qu&eacute; no puedo votar en encuestas?", "Para prevenir resultados trucados, s&oacute;lo los usuarios registrados pueden votar en encuestas. Si se ha registrado pero no puede votar, es posible que no tenga autorizaci&oacute;n para votar en esa encuesta.");

$faq[] = array("--","Formateo de mensajes y tipos de temas");
$faq[] = array("&iquest;Qu&eacute; es el c&oacute;digo BBCode?", "BBCode es una implementaci&oacute;n especial del HTML; la forma en que puede usarse es determinada por el administrador. Es muy similar al HTML: las etiquetas van entre corchetes [ y ] para mas informaci&oacute;n puede ver el manual de BBCode, el enlace aparece cada vez que va a publicar un mensaje.");
$faq[] = array("&iquest;Puedo usar HTML?", "Depende de si el administrador tenga habilitada la opci&oacute;n y de qu&eacute; etiquetas HTML est&eacute;n activadas, ya que muchas etiquetas HTML podr&iacute;an da&ntilde;ar severamente la estructura del mensaje.");
$faq[] = array("&iquest;Qu&eacute; son los emoticonos?", "Emoticonos son peque&ntilde;os gr&aacute;ficos que pueden ser usados para expresar emociones. Aparecen introduciendo un peque&ntilde;o c&oacute;digo. Por ejemplo:  :) significa feliz, :( significa triste. La lista completa de emoticonos se despliega cuando va a escribir un mensaje.");
$faq[] = array("&iquest;Puedo publicar im&aacute;genes?", "Las im&aacute;genes pueden ser adheridas al mensaje insert&aacute;ndolas en el momento de redactarlo. No puede haber im&aacute;genes de sitios de correo, b&uacute;squeda o que requieran autentificaci&oacute;n (Yahoo, Hotmail...).");
$faq[] = array("&iquest;Qu&eacute; son los anuncios?", "Los anuncios contienen informaci&oacute;n importante para los usuarios.");
$faq[] = array("&iquest;Qu&eacute; son las notas?", "Temas importantes, aparecen debajo de los anuncios y s&oacute;lo en la primera p&aacute;gina. Es informaci&oacute;n importante que deber&iacute;a leer :)");
$faq[] = array("&iquest;Qu&eacute; son los temas cerrados o bloqueados?", "Los temas cerrados o bloqueados son temas en los que ya no se puede escribir por decisi&oacute;n del administrador o moderadores.");

$faq[] = array("--","Niveles de usuario/a y grupos");
$faq[] = array("&iquest;Qu&eacute; son los administradores/as?", "Son personas que tienen asignado un alto nivel de control sobre el foro entero: permisos, moderaci&oacute;n, y todo tipo de configuraciones.");
$faq[] = array("&iquest;Qu&eacute; son los moderadores/as?", "Son personas que tienen el poder de editar o borrar foros, cerrarlos o abrirlos. Son designados por el administrador y tienen menos opciones que &eacute;l.");
$faq[] = array("Qu&eacute; son los grupos de usuarios/as?", "Son una de las formas en las que el administrador del foro puede agrupar usuarios. Un usuario puede pertenecer a varios grupos. Esto se hace con el fin de conceder permisos colectivos sobre el foro (como convertir a todo un grupo en moderadores).");
$faq[] = array("&iquest;C&oacute;mo puedo pertenecer a un grupo de usuarios/as?", "Pulse en grupos de usuarios y pida su inscripcion. Recibir&aacute; un correo si es aceptado. No todos los grupos son abiertos.");
$faq[] = array("&iquest;C&oacute;mo me convierto en el moderador/a de un grupo de usuarios/as?", "S&oacute;lo el administrador puede asignar ese permiso, contacte con &eacute;l :)");

$faq[] = array("--","Mensajer&iacute;a privada");
$faq[] = array("&iexcl;No puedo enviar mensajes privados!", "Hay tres posibles razones: No est&aacute; registrado o no ha ingresado, el administrador deshabilit&oacute; el sistema de mensajes privados, o deshabilit&oacute; para usted la mensajer&iacute;a.");
$faq[] = array("&iexcl;Quiero evitar mensajes privados no deseados!", "En el futuro ser&aacute; agregada la caracter&iacute;stica de ignorar mensajes; por ahora, env&iacute;e un mensaje al administrador si recibe mensajes no deseados :(.");
$faq[] = array("&iexcl;He recibido spam o correos maliciosos de alguien en este foro!", "Lo sentimos mucho, la caracter&iacute;stica de mandar correos tiene amplios conceptos de seguridad y privacidad. Env&iacute;e el correo al administrador, tal como ven&iacute;a, incluyendo cabeceras y dem&aacute;s. &Eacute;l tomar&aacute; medidas.");

$faq[] = array("--","Generador de avatar");
$faq[] = array("&iquest;Qu&eacute; es?", "El <strong>Generador de avatar</strong> es usado para generar avatares para este foro phpBB por los usuarios.");
$faq[] = array("&iquest;D&oacute;nde lo puedo encontrar?", "Los puede encontrar en su perfil en la secci&oacute;n de avatares");
$faq[] = array("&iquest;C&oacute;mo guardo mi avatar?", "Debe de haber un enlace debajo del avatar que se ha generado. El enlace dice <strong>Pulse aqu&iacute; para a&ntilde;adir este avatar a su perfil</strong>. Una vez que pulse en &eacute;l, ver&aacute; un mensaje que le informara sobre el cambio.");

$faq[] = array("--","&Aacute;lbum de fotos");
$faq[] = array("&iquest;C&oacute;mo puedo acceder al &aacute;lbum de fotos? ", "Basta con usar el enlace '&Aacute;lbum de fotos' en el men&uacute; de navegaci&oacute;n. Esto le llevar&aacute; al directorio principal donde se muestran todos los &aacute;lbumes p&uacute;blicos. Tambi&eacute;n puede acceder a la galer&iacute;a personal de un usuario haciendo clic en el enlace 'Galer&iacute;as personales de usuarios' debajo de la categor&iacute;a p&uacute;blica.");
$faq[] = array("&iquest;C&oacute;mo puedo a&ntilde;adir una imagen a un &aacute;lbum de fotos?", "Una vez que usted est&aacute; en el directorio principal del &aacute;lbum de fotos, seleccione una de las' categor&iacute;as p&uacute;blicas' o 'Galer&iacute;as personales de usuarios'. Ahora debe ver un bot&oacute;n que dice 'Subir imagen' en la parte superior y la parte inferior de la p&aacute;gina. Haga clic en este bot&oacute;n y siga las instrucciones en la p&aacute;gina siguiente.");
$faq[] = array("&iquest;Cu&aacute;l es el tama&ntilde;o m&aacute;ximo de archivo, m&aacute;ximo ancho y la m&aacute;xima altura de la imagen permitido?", "Estos ajustes aparecen en 'Subir imagen'. El administrador fija el l&iacute;mite superior para el tama&ntilde;o del archivo, define las extensiones de archivos permitidas y otras cosas para cargar im&aacute;genes en los &aacute;lbumes.");
$faq[] = array("&iquest;Qu&eacute; formato tiene que tener mi imagen?", "Estos ajustes aparecen en 'Subir imagen'. El administrador fija un l&iacute;mite superior para el tama&ntilde;o del archivo, define las extensiones de archivos y otras cosas para cargar im&aacute;genes en los &aacute;lbumes.");
$faq[] = array("Al subir mi imagen me aparece un mensaje de error!", "Vuelva a la p&aacute;gina 'Subir imagen' y aseg&uacute;rese de seguir todas las instrucciones que aparecen all&iacute;. El fichero que usted ha intentado subir puede ser m&aacute;s grande que el tama&ntilde;o m&aacute;ximo de archivo permitido, puede estar tratando de subir una foto que no se ajustan a las dimensiones especificadas, puede estar tratando de cargar una foto en un formato no est&aacute; disponible, o simplemente pueden haber olvidado que rellenar los campos necesarios para enviar correctamente la foto.");
$faq[] = array("He cometido un error en el t&iacute;tulo y/o descripci&oacute;n de mi imagen. &iquest;Qu&eacute; puedo hacer?", "Al ver un &aacute;lbum, hay varias opciones disponibles para los usuarios. Si el administrador lo ha permitido, usted encontrar&aacute; el enlace 'Editar' debajo de cada miniatura que le permitir&aacute; modificar esta informaci&oacute;n en cualquier momento.");
$faq[] = array("&iquest;C&oacute;mo puedo borrar una foto?", "Al ver un &aacute;lbum, hay varias opciones disponibles para los usuarios. Si el administrador lo ha permitido, usted encontrar&aacute; el enlace 'Eliminar' debajo de cada miniatura que le permitir&aacute; eliminar cualquier imagen suya.");
$faq[] = array("Me gustar&iacute;a saber si a la gente le gusta o no le gusta mi imagen. &iquest;C&oacute;mo puedo hacerlo?", "Al ver un &aacute;lbum o una foto, hay varias opciones disponibles para los usuarios. Si el administrador lo ha permitido, encontrar&aacute;s los enlaces' calificaci&oacute;n 'y' comentarios' debajo de cada miniatura o imagen que le permiten hacer esto de un par de maneras en cualquier momento.");

$faq[] = array("--","Archivos adjuntos");
$faq[] = array("&iquest;C&oacute;mo puedo a&ntilde;adir un archivo adjunto?", "Puede agregar un adjunto cuando se publica un nuevo mensaje si el administrador se lo ha permitido. Deber&iacute;a ver 'A&ntilde;adir adjunto' debajo de la zona donde se escribe el texto del mensaje. P&uacute;lselo y despu&eacute;s haga clic en 'examinar' para que se abra un cuadro dialogo est&aacute;ndar de selecci&oacute;n de archivos. Busque el archivo que desea adjuntar, selecci&oacute;nelo y haga clic en OK, Abrir o doble clic como lo har&iacute;a cuando usa el explorador de archivos en su ordenador. Si decide a&ntilde;adir un comentario en el campo comentario del archivo este comentario ser&aacute; usado como un enlace al archivo adjunto. Si no ha a&ntilde;adido un comentario se utilizar&aacute; el nombre del archivo para enlazar con el archivo adjunto. Si el administrador lo ha permitido usted podr&aacute; subir varios adjuntos siguiendo el mismo procedimiento que se describe m&aacute;s arriba hasta llegar al m&aacute;ximo n&uacute;mero de archivos adjuntos permitidos para cada mensaje.<br /><br />El administrador fija el l&iacute;mite de tama&ntilde;o de archivo, define las extensiones de archivos permitidas y otras cosas para los archivos adjuntos en el foro. Tenga en cuenta que es su responsabilidad de que sus archivos adjuntos cumplan la legalidad vigente, las normas de uso del foro, y que pueden ser borrados sin previo aviso.<br /><br />Por favor tenga en cuenta que el propietario del foro, el webmaster, administrador o moderadores declinan toda responsabilidad por cualquier p&eacute;rdida de datos.");
$faq[] = array("&iquest;C&oacute;mo puedo a&ntilde;adir un archivo adjunto despu&eacute;s de haber publicado un mensaje?", "Para a&ntilde;adir un archivo adjunto despu&eacute;s de haber publicado un mensaje deber&aacute; editar su mensaje y seguir los pasos anteriores. El nuevo archivo adjunto se agregar&aacute; al mensaje editado al hacer clic en <i>Enviar</i>.");
$faq[] = array("&iquest;C&oacute;mo se elimina un archivo adjunto?", "Para borrar los archivos adjuntos deber&aacute; editar el mensaje y hacer clic en <i>Eliminar adjunto</i>, junto al adjunto que quiere borrar en la zona <i>Adjuntos agregados</i>. El archivo adjunto se elimina cuando se haga clic en <i>Enviar</i>.");
$faq[] = array("&iquest;C&oacute;mo puedo actualizar el comentario de un adjunto?", "Para actualizar el comentario de un adjunto deber&aacute; editar su mensaje, edite el texto en <i>Comentario del archivo</i> y haga clic en el bot&oacute;n <i>Actualizar comentario</i>, situado junto al archivo que desea comentar. El comentario del archivo se actualizar&aacute; en el mensaje cuando haga clic en <i>Enviar</i>.");
$faq[] = array("&iquest;Por qu&eacute; no veo el adjunto en mi mensaje?", "Probablemente el archivo o la extensi&oacute;n no est&aacute;n permitido en el foro, o un moderador o administrador lo han eliminado por no cumplir las normas de uso de la web.");
$faq[] = array("&iquest;Por qu&eacute; no puedo agregar adjuntos?", "En algunos foros a&ntilde;adir adjuntos puede estar limitado a ciertos grupos de usuarios. Para agregar un adjunto podr&iacute;a necesitar una autorizaci&oacute;n especial, solo un moderador o administrador puede otorgar este permiso, p&oacute;ngase en contacto con ellos.");
$faq[] = array("Tengo los permisos necesarios, &iquest;porque no puedo agregar adjuntos?", "El administrador fija un l&iacute;mite m&aacute;ximo de tama&ntilde;o del archivo, extensiones y otras cosas para los archivos adjuntos en el foro. Un administrador o moderador puede haber modificado o cancelado sus permisos, para adjuntar archivos en un foro espec&iacute;fico. Deber&iacute;a obtener una explicaci&oacute;n en el mensaje de error que aparece al tratar de agregar un archivo adjunto, si no, considere la posibilidad de contactar con el administrador o moderador.");
$faq[] = array("&iquest;Por qu&eacute; no puedo borrar adjuntos?", "En algunos foros borrar adjuntos puede estar limitado a ciertos grupos de usuarios. Para borrar un adjunto podr&iacute;a necesitar una autorizaci&oacute;n especial, solo un moderador o administrador puede otorgar este permiso, p&oacute;ngase en contacto con ellos.");
$faq[] = array("&iquest;Por qu&eacute; no puedo ver/bajar adjuntos?", "En algunos foros la visualizaci&oacute;n/descarga de los adjuntos puede estar limitado a ciertos grupos de usuarios. Para ver/bajar un adjunto podr&iacute;a necesitar una autorizaci&oacute;n especial, solo un moderador o administrador puede otorgar este permiso, p&oacute;ngase en contacto con ellos.");
$faq[] = array("&iquest;Con quien contacto sobre los adjuntos ilegales o posiblemente ilegales?", "Usted debe ponerse en contacto con el administrador de este foro. Si no lo encuentra en primer lugar deber&iacute;a contactar uno de los moderadores de los foros para preguntarle a quien se debe dirigir. Si aun as&iacute; no obtiene respuesta deber&iacute;a ponerse en contacto con el propietario del dominio (hacer b&uacute;squeda whois) o, si este se est&aacute; ejecutando en un servicio gratuito (ej. yahoo, free.fr, f2s.com, etc), con el departamento que gestiona el abuso de ese servicio. Tenga en cuenta que el equipo de Icy Phoenix no tiene absolutamente ning&uacute;n control y no puede de ninguna manera ser considerado responsable de como, donde o quien usa este foro. Es absolutamente in&uacute;til contactar con el equipo de Icy Phoenix en relaci&oacute;n a cualquier acto ilegal (cesar y desistir, responsabilidades, comentarios difamatorios, etc) que no est&eacute; directamente relacionado con el sitio web Icy Phoenix.com o al software de Icy Phoenix. Si lo hace al e-mail de equipo de Icy Phoenix acerca de cualquier utilizaci&oacute;n por un tercero de este software es posible que le contestemos o que no dependiendo del caso.");

$faq[] = array("--","Descargas");
$faq[] = array("&iquest;D&oacute;nde puedo encontrar las descargas?", "Links a las descargas est&aacute;n situados en el menu de navegaci&oacute;n y en la navegaci&oacute;n del portal. Directlink: [<a href=\"downloads.php\">Downloads</a>]");
$faq[] = array("&iquest;Qu&eacute; significa <img border=\"0\" src=\"" . $images['Dl_blue'] . "\" alt=\"\" title=\"\" />?", "No es posible la descarga. El tr&aacute;fico total ajustado por el administrador para cada descarga o para la categor&iacute;a ys se ha alcanzado este mes.");
$faq[] = array("&iquest;Qu&eacute; significa <img border=\"0\" src=\"" . $images['Dl_red'] . "\" alt=\"\" title=\"\" />?", "No es posible la descarga. Puede ser:<br />- La descarga est&aacute; bloqueada por el administrador.<br />- El usuario no est&aacute; logado y la descarga solo est&aacute; permitida para usuarios registrados.<br />- El usuario no tiene suficiente tr&aacute;fico para descargar el fichero.<br />- El administrador ha fijado un n&uacute;mero m&iacute;nimo de posteos y el usuario no los tiene\"t.<br />- El l&iacute;mite de tr&aacute;fico para este fichero se ha superado.");
$faq[] = array("&iquest;Qu&eacute; significa <img border=\"0\" src=\"" . $images['Dl_grey'] . "\" alt=\"\" title=\"\" />?", "Fuente externa. La descarga comenzar&aacute; desde un servidor externo. Esto ser&aacute; manejado como <img border=\"0\" src=\"" . $images['Dl_green'] . "\" alt=\"\" title=\"\" />. El tr&aacute;fico del usuario o el total no se decrementar&aacute;n.");
$faq[] = array("&iquest;Qu&eacute; significa <img border=\"0\" src=\"" . $images['Dl_white'] . "\" alt=\"\" title=\"\" />?", "Como <img border=\"0\" src=\"" . $images['Dl_green'] . "\" alt=\"\" title=\"\" /> el tr&aacute;fico del usuario no se decrementar&aacute; . Pero solo usuarios logados pueden descargar gratuitamente. El tr&aacute;fico total se decrementar&aacute;.");
$faq[] = array("&iquest;Qu&eacute; significa <img border=\"0\" src=\"" . $images['Dl_yellow'] . "\" alt=\"\" title=\"\" />?", "Descarga es posible con restricciones. La descarga es solo posible para usuarios registrados. El usuario debe logarse. El tama&ntilde;o del fichero ser&aacute; restado de su tr&aacute;fico y del tr&aacute;fico total.");
$faq[] = array("&iquest;Qu&eacute; significa <img border=\"0\" src=\"" . $images['Dl_green'] . "\" alt=\"\" title=\"\" />?", "Descarga gratuita. La descarga no ser&aacute; restringida. Este fichero puede ser descargado por invitados. No es necesario estar logado. Tu tr&aacute;fico no se decrementar&aacute;, pero si el total.");
$faq[] = array("&iquest;Por qu&eacute; no puedo descargar un fichero?", "Puede ser por varias razones. Mira bajo <img border=\"0\" src=\"" . $images['Dl_blue'] . "\" alt=\"\" title=\"\" /> y <img border=\"0\" src=\"" . $images['Dl_red'] . "\" alt=\"\" title=\"\" />.");
$faq[] = array("&iquest;C&oacute;mo y cu&aacute;ndo obtengo nuevo tr&aacute;fico para mi cuenta?", "Despu&eacute;s del primer login el usuario obtiene un timestamp. Cada primer d&iacute;a de mes, cuando el usuario entre a descargas, el tr&aacute;fico ser&aacute; refrescado. Preguta a tu administrador la cantidad que obtendr&aacute;s.");
$faq[] = array("Deseo a&uacute;n descargar un fichero m&aacute;s, pero no me queda m&aacute;s tr&aacute;fico", "En estos caso, p&iacute;deselo a tu administrador. Solo &eacute;l puede decidir incrementar el tr&aacute;fico de usuario antes de que la cuenta obtenga nueva cuota de forma autom&aacute;tica el siguiente mes.");
$faq[] = array("&iquest;C&oacute;mo puedo calificar descargas?", "Despu&eacute;s de cada descarga en la categor&iacute;a o en la vista de detalle ver&aacute;s una secci&oacute;n para evaluar.<br />By pulsa en  \"Rate\" un usuario registrado puede evaluar una descarga desde 1 punto (muy mala) a 10 puntos (muy buena). Puedes evaluar una descarga una sola vez.");

$faq[] = array("--","Res&uacute;menes");
$faq[] = array("&iquest;Qu&eacute; son los res&uacute;menes?", "Son correos que se env&iacute;an peri&oacute;dicamente con el resumen de los posts hechos en el sitio. Est&aacute;n disponibles diaria o semanalmente.");
$faq[] = array("&iquest;Por qu&eacute; podr&iacute;a desear un resumen?", "Hace la vida m&aacute;s f&aacute;cil. No tienes que visitar el sitio expl&iacute;citamente para ver que conversaciones est&aacute;n teniendo lugar. Solo con leer el resumen vemos lo que nos interesa y con un clic de rat&oacute;n accederemos a &eacute;l y comenzaremos nuestra participaci&oacute;n. Puedes eliminar la suscripci&oacute;n en cualquier momento.");
$faq[] = array("&iquest;Cada cu&aacute;nto tiempo se env&iacute;a?", "Diaria o semanalmente. Los env&iacute;os semanales son procesados el domingo.");
$faq[] = array("&iquest;Cu&aacute;ndo se env&iacute;an los res&uacute;menes?", "Tu determinas la hora a la que deseas recibir el resumen. Se a cual fuere la hora que elijas, obtendr&aacute;s siempre las &uacute;ltimas noticias de tal manera que se ajuste a tu estilo de vida.");
$faq[] = array("&iquest;Qu&eacute; per&iacute;odo de tiempo cubre el resumen?", "24 horas o  7 d&iacute;as, dependiendo de si seleccionaste resumen diario o semanal. Los mensajes m&aacute;s antiguos que esas fechas no se enviar&aacute;n. Adem&aacute;s, si lo deseas, puedes elegir no ver los mensajes desde tu &uacute;ltimo login si hiciste esa visita recientemente. Puedes incluso filtrar tus propios mensajes");
$faq[] = array("Supongamos que no deseo res&uacute;menes de cada mensaje. &iquest;Puedo ser selectivo?", "Si. Puedes seleccionar el foro o foros que te interesen. Por defecto, obtendr&aacute;s los mensajes de todos los foros a los que tengas acceso.");
$faq[] = array("&iquest;Qu&eacute; formatos de correo est&aacute;n disponibles?", "Se pueden mandar correos en HTML o texto. A menos que tu programa de correo no maneje HTML (muy raro actualmente), te sugerimos usar este formato. Sinceramente, los res&uacute;menes en formato texto parecen demasiado planos y dif&iacute;ciles de leer Esto es la naturaleza de los textos planos.");
$faq[] = array("&iquest;se env&iacute;a el mensaje completo en el resumen?", "Por defecto, se env&iacute;an los primeros 150 caracteres del mensaje, o puedes elegir no ver nada del mensaje y solo el t&iacute;tulo en su lugar. Puedes elegir la inclusi&oacute;n de los primeros 50, 100, 150, 300 o 600 caracteres o el texto completo del mensaje hasta 32.000 caracteres. M&aacute;s all&aacute; de este tama&ntilde;o, ser&aacute; trucado. Recomendamos mantener la longitud del mensaje por defecto porque si no, los res&uacute;menes ser&aacute;n inmanejables. Tambi&eacute;n tenemos noticias de que grandes res&uacute;menes son rechazados por los ISP o pueden superar las cuotas de almacenamiento de los servidores. Un extracto no reduce los anchos de banda y es usualmente todo lo que se necesita. &iquest;Por qu&eacute;? Porque cada mensaje tiene un enlace que te permitir&aacute; ir al tema de inter&eacute;s. .");
$faq[] = array("&iquest;C&oacute;mo puedo empezar?", "Pulsa en el enlace a res&uacute;menes (Digests) en el bloque de enlaces de navegaci&oacute;n o aqu&iacute;: <a href=\"./digests.php\">Digests</a>.");
$faq[] = array("&iquest;Puedo cancelar la suscripci&oacute;n?", "&iexcl;Por supuesto!. Solo con ir a la misma p&aacute;gina y pulsar  \"None\" for \"Type of Digest Wanted\". Entonces rellena el formulario. Tu suscripci&oacute;n finalizar&aacute; de inmediato.");
$faq[] = array("&iquest;Los res&uacute;menes est&aacute;n libres de publicidad?", "Por supuesto. No hay ning&uacute;n molesto anuncio y nunca lo habr&aacute;.");
$faq[] = array("&iquest;Est&aacute; mi privacidad protegida?", "Si. Tu resumen se env&iacute;a a t&iacute; y a nadie m&aacute;s. A nadie m&aacute;s que a qu&iacute;en tu nos digas en tu perfil. Piensa en el resumen como una edici&oacute;n especial de un per&iacute;odico parametrizado solo para ti. Algo diferente a eso es otro tipo de resumen.");


$faq[] = array("--","Informaci&oacute;n de mensajes no le&iacute;dos almacenados en base de datos (UPI2DB)");
$faq[] = array("&iquest;Cu&aacute;l es la diferencia entre el sistema basado en  cookies usado por defecto y el sistema UP2DB?", "El sistema basado en cookies es el sistema por defecto de los foros phpBB2. Cuando un mensaje es le&iacute;do, la informaci&oacute;n al respecto es almacenada en una cookie en tu ordenador, la cual incluye la informaci&oacute;n de que has le&iacute;do el mensaje. La mayor desventaja de este sistema es que se pierden las informaciones sobre hilos marcados como le&iacute;dos o no le&iacute;dos al cerrar el explorador. El sistema UPI2DB no almacena informaci&oacute;n como cookies en tu ordenador, lo hace de forma separada en la base de datos.");
$faq[] = array("&iquest;C&uacute;ales son los pros y contras del sistema de cookies?", "<strong>Ventaja:</strong> Con grandes foros el sistema de cookies tiene una mayor velocidad de carga de p&aacute;ginas que el sistema UPI2DB, porque el sistema debe tambi&eacute;n cargar la informaci&oacute;n sobre los mensajes le&iacute;dos desde la base de datos. Otra ventaja es que los datos se almacenar&aacute;n varios meses (si no los borras del ordenador) y no estar&aacute;n sujetos a borrados de archivos antiguos en la base de datos del sistema. Esto es interesante para usuarios que solo leen el foro cada 2 meses, por ejemplo. <br /><strong>Desventaja:</strong> La mayor desventaja es que todos los mensajes son marcados como le&iacute;dos al cerrar el explotador. Otra desventaja es que los mensajes editados no se marcan de nuevo como no le&iacute;dos y por ello no fijar&aacute;s atenci&oacute;n en ellos.");
$faq[] = array("&iquest;Cu&aacute;les son los pros y contras del sistema UPI2DB?", "<strong>Ventaja:</strong> Mensajes no le&iacute;dos quedan como no le&iacute;dos si se cierra el explorador. Si se cierra el explorador, no tendr&aacute;s que buscar los elementos que no hayas le&iacute;do porque el sistema te los se&ntilde;ala. Los posts se pueden tambi&eacute;n marcar como le&iacute;dos durante un per&iacute;do de " . $unread_days . " con el sistema UPI2DB. Los foros que no te interesen pueden ser marcador como \"permanentemente le&iacute;dos\", hasta que cambies esa opci&oacute;n. Contribuciones editadas se marcan como no le&iacute;das con la nota \"Editado\" y adem&aacute;s tienen otro color diferente de los mensajes normales no le&iacute;dos. Una nueva funci&oacute;n de b&uacute;squeda permite buscar solo entre los mensajes no le&iacute;dos o editados. Cuando el administrador activa la visualizaci&oacute;n de contribuciones editadas en la parte superior del los posts, esas contribuciones editadas se marcar&aacute;n en la primera l&iacute;nea del mensaje.<br /><strong>Desventajas:</strong> Para foros muy grandes con muchos mensajes y usuarios, puede tardar m&aacute;s en cargar la p&aacute;gina. La informaci&oacute;n de si una contribuci&oacute;n ha sido le&iacute;da est&aacute; en la base de datos solo durante un determinado tiempo tras el cual es marcada como le&iacute;da. El per&iacute;odo est&aacute;ndar es de 30 d&iacute;as, pero puede se modificado por el administrador.");
$faq[] = array("No puedo ver ning&uacute;n par&aacute;metro en mi perfil donde seleccionar el uso de cookies o el sistema UPI2DB", "Si no ves las opciones para el sistema UPI2DB, el administrador ha activado o desactivado permanentemente el sistema. En ese caso, no tienes posibilidad de cambiar la opci&oacute;n.");
$faq[] = array("&iquest;Qu&eacute; condiciones puede fijar el administrador?", "Por defecto, el sistema UPI2DB permite al administrador la opci&oacute;n de seleccionar cuantos posts debe haber posteado un usuario en el sistema para poder usar esta opci&oacute;n o desde hace cuanto tiempo se debe haber registrado para poder usarla.");
$faq[] = array("Siempre que intento, no puedo marcar notas o anuncios como le&iacute;dos", "Notas y anuncios deben ser le&iacute;dos, no pueden ser marcados como le&iacute;dos y por ello no se pueden usar las funciones de: \"Marcar todos los foros/contribuciones como le&iacute;dos\" o \"Mostrar contribuciones no le&iacute;das\"!");
$faq[] = array("Quiero marcar todos los mensajes de m&aacute;s de " . $unread_days . " d&iacute;as como \"permanentemente le&iacute;dos\"!", "Esto es como ocurrir&aacute; y no puede ser cambiado. Tenemos que mantener el compromiso de hacer que el sistema no ir&aacute; demasiado lento.");
$faq[] = array("&iquest;Como se puede marcar un foro como \"permanentemente le&iacute;do\"?", "Solamente pulsa en el dibujo delante del nombre del foro. El dibujo debe cambiar.");
$faq[] = array("&iquest;C&oacute;mo puedo marcar un tema como \"permanentemente le&iacute;do\"?", "Pulsa en el dibujo delante del nombre del hilo. El dibujo deber&iacute;a cambiar u el tema se mover&aacute; al &uacute;ltimo lugar en la lista. Alternativamente, puedes pulsar \"Tema marcado permanentemente como le&iacute;do\" en la parte de abajo de la p&aacute;gina.");
$faq[] = array("No puedo marcar notas y anuncios como  \"permanentemente le&iacute;dos\"!", "Notas y anuncios no pueden ser marcados como \"permanentemente le&iacute;dos\", porque podr&iacute;as perder informaciones valiosas. ");
$faq[] = array("He marcado un foro como \"permanentemente le&iacute;do\", pero, &iexcl;aparecen nuevos mensajes!", "Cuando alguien contribuye con una nota o un anuncio, el foro marcado como \"permanentemente le&iacute;do\" ser&aacute; ajustado de nuevo a su valor por defecto. Esto es importante para evitar que se pierdan importantes informaciones.");
$faq[] = array("&iquest;C&oacute;mo puedo marcar una informaci&oacute;n para encontrarla f&aacute;cilmente m&aacute;s tarde?", "En cada contribuci&oacute;n puedes encontrar un bot&oacute;n en el t&iacute;tulo que se puede usar para marcarla. Contribuciones m&aacute;s antiguas que " . $unread_days . " d&iacute;as o contribuciones que fueron escritas antes de tu fecha de registro en este foro no ser&aacute;n marcadas.");
$faq[] = array("&iquest;C&oacute;mo puedo fijar de nuevo un hilo le&iacute;do como no le&iacute;do?", "En cada mensaje hay un enlace al t&iacute;tulo del tema. Con este enlace se pueden marcar todos los posts enviados o editados despu&eacute;s de &eacute;l como nuevos o editados.");
$faq[] = array("&iquest;Por qu&eacute; no puedo marcar algunos hilos?", "Hilos marcados como \"permanentemente le&iacute;dos\" en un foro o lo que fue escrito antes de tu fecha de registro no pueden ser marcados. Contribuciones m&aacute;s antiguas de " . $unread_days . " d&iacute;as, tampoco pueden ser marcadas..");
$faq[] = array("&iquest;Los hilos marcados permanecen as&iacute; para siempre?", "No, todas las marcas que pongas ser&aacute;n borradas autom&aacute;ticamente despu&eacute;s de " . $del_mark . " d&iacute;as desde que se puso la marca.");
$faq[] = array("&iquest;Qu&eacute; significa MAR?", "Es la abreviatura de \"Marcar todo le&iacute;do\"");


$faq[] = array("--","Temas relacionados con phpBB");
$faq[] = array("&iquest;Qui&eacute;n escribi&oacute; este tabl&oacute;n de anuncios?", "Este software (en su forma no modificada) es producido, liberado y con copyright de <a href=\"http://www.phpbb.com/\" target=\"_blank\">phpBB Group</a>. Se libera bajo Licencia P&uacute;blica General GNU y puede ser libremente distribuido; ver enlace para m&aacute;s detalles.");
$faq[] = array("&iquest;Por qu&eacute; no est&aacute; disponible la funcionalidad X?", "Este software fue escrito y licenciado a trav&eacute;s del grupo phpBB. Si tu crees que esta funcionalidad necesita ser incluida, entonces visita la web phpbb.com y mira lo que tiene que decir el grupo phpBB Group. Por favor, no escribir peticiones de funcionalidades en phpbb.com. El grupo usa sourceforge para manejar las nuevas funcionalidades. Por favor, lee cuidadosamente los foros y observa que mira que puede ya haberse tomado una decisi&oacute;n sobre la funcionalidad y entonces sigue el procedimiento all&iacute; indicado.");
$faq[] = array("&iquest;Con qui&eacute;n debo contactar por uso abusivo y/o asuntos legales relativos a esta web?", "Debes contactar con el administrador. Si no puedes encontrar qui&eacute;n es, deber&iacute;as primero contactar con un moderador y preguntarle con qui&eacute;n debes contactar. Si no hay respuesta, debes contactar con el due&ntilde;o del dominio o si est&aacute; ejecut&aacute;ndose en uno gratuito (como yahoo, free.fr, f2s.com, etc.), con el departamento de gesti&oacute;n de uso abusivo o ilegal de ese servicio. Por favor, nota que el grupo phpBB Group no tiene control de ning&uacute;n modo de c&oacute;mo, d&oacute;nde y por qui&eacute;n es usado. Es absolutamente in&uacute;til contactar con el grupo phpBB en relaci&oacute;n con asuntos legales (cesar y desistir, responsable, comentarios difamatorios, etc) por que es una cuesti&oacute;n que no est&aacute; directamente relacionada con el sitio web phpbb.com o con el software de phpBB. Si a pesar de todo lo comunica por correo al grupo phpBB no debe esperar una respuesta.");


$faq[] = array("--", "Sobre Icy Phoenix");
$faq[] = array("&iquest;Qu&eacute; es Icy Phoenix?", "Icy Phoenix es un sistema de gesti&oacute;n de contenidos que permite al usuario crear una web din&aacute;mica con muchas caracter&iacute;sticas embebidas: foro, portal, p&aacute;ginas y bloques parametrizables, descargas, galer&iacute;a de fotos y mucho m&aacute;s.");
$faq[] = array("&iquest;Qui&eacute;n escribi&oacute; el software?", "Este software est&aacute; basado en phpBB el cual est&aacute; liberado bajo una Licencia General P&uacute;blica (GNU), as&iacute;, Icy Phoenix debe estar liberado bajo el mismo tipo de licencia y esto significa que puede ser modificado y distribuido libremente. Aparte de los ficheros core phpBB, la mayor&iacute;a de los ficheros han sido directamente codificados o modificados por Mighty Gorgon y el <a href=\"http://www.icyphoenix.com/\" target=\"_blank\">equipo de Icy Phoenix</a>. Una lista no exhaustiva de colaboradores a este proyecto se puede encontrar en: <a href=\"http://www.icyphoenix.com/credits.php\" target=\"_blank\">Icy Phoenix credits</a>.");



?>