<?php
/**
*
* @package Icy Phoenix
* @version $Id$
* @copyright (c) 2008 Icy Phoenix
* @license http://opensource.org/licenses/gpl-license.php GNU Public License
*
*/

/**
*
* @Icy Phoenix is based on phpBB
* @copyright (c) 2008 phpBB Group
*
*/

/**
*
* @Extra credits for this file
* Lopalong
*
*/

if (!defined('IN_ICYPHOENIX'))
{
	exit;
}

//
// To add an entry to your FAQ simply add a line to this file in this format:
// $faq[] = array("question", "answer");
// If you want to separate a section enter $faq[] = array("--","Block heading goes here if wanted");
// Links will be created automatically
//
// DO NOT forget the ; at the end of the line.
// Do NOT put double quotes (") in your FAQ entries, if you absolutely must then escape them ie. \"something\"
// The FAQ items will appear on the FAQ page in the same order they are listed in this file


$faq[] = array('--','Belépési és Regisztrációs tudnivalók');
$faq[] = array('Miért nem tudok belépni?','Regisztráltad magadat? Elõfordulhat, hogy a fórum látogatása regisztrációhoz kötött. Ki lettél tiltva a Fórumról (ebben az esetben egy üzenet jelenik meg)? Lépj kapcsolatba a Webmesterrel, vagy az Adminisztrátorral, hogy miért tiltottak le. Ha regisztrálva vagy, és nem vagy kitiltva az oldalról, akkor ellenõrizd, hogy nem gépelted-e el a nevet, vagy a jelszót. Ellenõrizd kétszer is, mivel legtöbbször ez a hiba. Ha a hiba még mindig fennáll, akkor lépj kapcsolatba az Adminisztrátorral, megadva a hiba pontos okát.');
$faq[] = array('Miért kell regisztrálnom magamat?','A regisztráció nem kötelezõ, ez az Adminisztrátoron múlik, hogy szükségessé teszi-e. A regisztrált felhasználók több szolgáltatáshoz jutnak, melyek nem érhetõek el a vendégeknek, mint például egyéni avatar képek, privát üzenet küldése, email küldés, csoporttagságok, stb. Pusztán néhány perc a regisztráció, mely megéri a több funkció érdekében.');
$faq[] = array('Miért lép ki automatikusan a rendszerbõl?','Amennyiben a belépésnél nem jelölted be az <i>Automatikus belépés</i> opciót, akkor csak egy meghatározott ideig lát a rendszer, mint aktív felhasználó. Ez megakadályozza, hogy illetéktelenek férjenek hozzá az azonosítódhoz, vagy hogy a nevedben írjanak a Fórumba. Nem ajánlott az <i>Automatikus belépés</i> használata ha nyilvános helyrõl használod a Fórumot, mint például könyvtár, internet kávézó, stb.');
$faq[] = array('Hogyan tudom megakadályozni, hogy mások lássák mikor vagyok épp jelen a Fórumon?','A profilban beállítható egy opció, mellyel ez letiltható: <i>Jelenlét elrejtése</i>. Ha ezt bekapcsolod, akkor csak az Adminisztrátor, vagy saját magad fogod látni, hogy jelen vagy-e. A bekapcsolásával rejtett felhasználónak számítasz.');
$faq[] = array('Elfelejtettem a jelszavamat!','Semmi pánik! A jelszót nem lehet utólag kideríteni, de lehet újat készíttetni. Ehhez menj vissza a Belépés oldalra, kattints az <u>Elfelejtettem a jelszót</u> linkre, kövesd az utasításokat, és rövid idõn belül újra be tudsz lépni a Fórumba.');
$faq[] = array('Regisztráltam magamat, de mégsem tudok belépni!','Elõször ellenõrizd, hogy helyes nevet, és jelszót adtál-e meg. Ha ez rendben van, akkor két dolog miatt nem tudsz belépni. Az egyik, hogy néhány fórumon elõbb aktiválni kell a regisztrációt, hogy be tudj lépni. Ezt vagy neked, vagy az Adminisztrátornak kell megtennie, még az elsõ belépés elõtt. A regisztráció végén megtudhatod, hogy szükséges-e aktiválnod a regisztrációt. Az aktiválás lehet emailen keresztüli: ekkor ellenõrizd a regisztrációnál megadott email-címedet, és kövesd a benne lévõ utasításokat. Az aktivációra azért van szükség, hogy megakadályozzuk a Fórum névtelenségével visszaélõ felhasználókat. Ha biztos vagy benne, hogy érvényes email-címet adtál meg, és belátható idõn belül nem kaptál emailt, akkor lépj kapcsolatba az Adminisztrátorral.');
$faq[] = array('Régebben regisztráltam magamat, de egy ideje nem tudok belépni?!','Ennek az a leggyakoribb oka, hogy hibás nevet, vagy jelszót adtál meg (ellenõrizd az emailt, amit regisztrálásnál kaptál); vagy mert az Adminisztrátor valami oknál fogva törölte az azonosítódat. Lehet hogy már regisztrálva vagy, de még semmihez sem szóltál hozzá? A Fórum bizonyos idõközönként törli azokat a felhasználókat, akik régóta nem szóltak hozzá egy témához sem. Regisztráld újra magadat, és kapcsolódj be a beszélgetésekbe.');


$faq[] = array('--','Felhasználói beállítások');
$faq[] = array('Hogyan változtathatom meg a beállításaimat?','Amennyiben regisztrált felhasználó vagy, a beállításaidat a <u>Profil</u> menüpontra kattintva érheted el. Ez általában az oldal tetején található, de nem minden esetben - függ a használatban lévõ sablontól.');
$faq[] = array('A dátum és/vagy idõbeállítás nem pontos!','Az idõ helyesen jelenik meg, ha helyes idõzóna van beállítva (Magyarország a "GMT +1" zónába tartozik). Ezt a szolgáltatást csak regisztrált felhasználók vehetik igénybe.');
$faq[] = array('Megváltoztattam az idõzónát, de még mindig pontatlan az idõ!','Ha biztosan a helyes idõzóna van beállítva, akkor feltehetõleg azért nem pontos, mivel probléma lehet a kétfajta idõszámítás. Jelenleg a fórum motorja nem támogatja a téli-nyári idõszámítás változásának követését, így fordulhat elõ a +-1 óra eltérés a pontos idõhöz képest. Ezt orvosolhatod, ha télen GMT+1-es idõzónát, míg nyáron GMT+2-es idõzónát állítasz be a profilodban.');
$faq[] = array('A használni kívánt nyelv nincs a listában!','Ennek az az oka, hogy az Adminisztrátor nem telepített más nyelvet a Fórumhoz, vagy mert a Fórumhoz nincsen fordítás a kívánt nyelven. Kérd meg az Adminisztrátort, hogy telepítse a nyelvet a Fórumhoz, vagy ha ilyen nem létezik, nyugodtan készítsd el a fordítást. További információért keresd fel a phpBB Csoport weboldalát (a link az oldal alján található).');
$faq[] = array('Hogyan jeleníthetek meg egy képet a nevem alatt?','A felhasználói név alatt két kép található. Az egyik a rangot mutatja (ezek általában csillagok, vagy egyéb sorminta, melyek a hozzászólások számának függvényében változnak). Ez alatt van egy nagyobb kép, melyet avatarnak nevezünk. Az avatar egy egyedi és személyes kép, mely más és más a legtöbb felhasználónak. A Fórum Adminisztrátorától függ, hogy lehetõség van-e avatar megjelenítésére. Ha nem tudsz avatart használni, akkor az Adminisztrátor letiltotta ezt a lehetõséget.');
$faq[] = array('Hogyan tudom megváltoztatni a rangomat?','Általában a felhasználók nem változtathatják meg közvetlenül a rangot, mivel ez a hozzászólások számától függ. Minél több hozzászólást írsz, annál nagyobb lesz a rangod. A rang általában a felhasználónév alatt látható a témákban. Léteznek speciális rangok, mint például "Adminsztrátor", vagy "Moderátor". Lehetõleg ne szólj hozzá feleslegesen a témákhoz csak mert a rangodat szeretnéd növelni: az Adminisztrátornak és a Moderátoroknak bármikor lehetõsége van lefokozni a rangodat, ha úgy látják jónak.');
$faq[] = array('Miért kell bejelentkezni az emailküldéshez?','A Fórumon keresztüli emailküldés csak regisztrált felhasználók számára lehetséges. Ez a névtelen emberek nemkívánt levelezésének elkerülésére van.');

$faq[] = array('--','Hozzászólással kapcsolatos kérdések');
$faq[] = array('Hogyan szólhatok hozzá a fórumokhoz?','Egyszerû, csak a megfelelõ gombra kell kattintanod, mely vagy a fórumban található, vagy a témában. Ha a fórumban egy új hozzászólást készítesz, akkor egy címet is adj meg a témának. Ha egy már megnyitott témában írsz egy új hozzászólást, akkor nem kötelezõ címet megadni. Hozzászólás küldéséhez lehet, hogy elõbb regisztrálnod kell magadat. A fórum vagy a téma alján találhatóak meg a jogosultságaid (<i>Új témát nyithat, Szavazhat, stb.</i>)');
$faq[] = array('Hogyan szerkeszthetek vagy törölhetek egy hozzászólást?','Csak abban az esetben módosíthatsz vagy törölhetsz egy hozzászólást, ha azt te készítetted, vagy ha Moderátor, vagy a Fórum adminisztrátora vagy. A <i>Szerkeszt</i> gombra kattintva tudsz módosítani egy hozzászólást. Ha valaki már válaszolt a hozzászólásodra, abban az esetben egy rövid megjegyzést találsz, hogy az hányszor lett már módosítva. Ez nem jelenik meg, ha még senki sem válaszolt a hozzászólásra, vagy ha a Moderátorok vagy az Adminisztrátor szerkesztette át.');
$faq[] = array('Hogyan csatolhatom az aláírásomat a hozzászóláshoz?','A csatoláshoz elõször el kell készítened az aláírást, ezt a profilodban teheted meg. Utána a hozzászólásban be kell kapcsolni az <i>Aláírás hozzáadását</i>. Az aláírás automatikusan is hozzáadható minden hozzászóláshoz, ez szintén a profilban kapcsolható be (ha ez be van kapcsolva, ettõl függetlenül hozzászólásonként még kikapcsolható).');
$faq[] = array('Hogyan készíthetek szavazást?','A szavazás készítése egyszerû, amikor egy új témát nyitsz, akkor ezzel együtt egy szavazást is indíthatsz. A szavazás természetesen opcionális, nem kötelezõ a témanyitáshoz. Szavazást úgy is készíthetsz, ha hozzászólásban a Szerkesztre kattintasz (a módosításhoz terrészetesen megfelelõ jogokkal kell rendelkezned); és a <i>Szavazás hozzáadása</i> linkre kattintassz. Megadhatsz egy címet a szavazásnak, és legalább két választási lehetõséget írj be (több lehetõség beírásához kattints a <i>Hozzáadás</i> gombra. Ezenkívül idõlimitet is megadhatsz a szavazáshoz, mellyel megadható, hogy hány napig legyen érvényes a szavazás. A választási lehetõségek maximális száma meg van határozva, melyet az Adminisztrátor határoz meg.');
$faq[] = array('Hogyan szerkeszthetek vagy törölhetek egy szavazást?','A hozzászólásokhoz hasonlóan a szavazásokat is csak a szavazás készítõje, egy Moderátor, vagy az Adminisztrátor szerkesztheti. Egy szavazás módosításához menj a téma elsõ hozzászólásához (általában ehhez tartozik a szavazás); és kattints a Szerkeszt gombra. Ha senki sem szavazott az adott témában, akkor a készítõje törölheti a szavazást; ha már szavaztak, akkor csak egy Moderátor vagy az Adminisztrátor módosíthatja vagy törölheti.');
$faq[] = array('Miért nem férek hozzá egyes fórumokhoz?','Néhány fórum csak kiemelt felhasználók és/vagy csoportok számára hozzáférhetõ. A fórum megtekintéséhez, olvasásához, hozzászólás küldéséhez speciális engedély kell, amit vagy a fórum Moderátorától vagy az Adminisztrátortól kaphatsz meg.');
$faq[] = array('Miért nem tudok szavazni?','Csak regisztrált felhasználók vehetnek részt a szavazásokban (a többszöri szavazás elkerülése végett). Amennyiben regisztrált felhasználó vagy de mégsem tudsz szavazni, akkor nincsen jogosultságod a szavazáshoz.');

$faq[] = array('--','Formázás és téma típusok');
$faq[] = array('Mi az a BBCode?','A BBCode egy speciális változata a HTML nyelvnek. A BBCode használatának engedélyezése a fórum Adminisztrátorától függ, de neked is lehetõséged van arra, hogy a hozzászólásaidban ki-, vagy bekapcsold a BBCode-t. A BBCode hasonló felépítésû, mint a HTML, kivéve hogy a tagek nem kacsacsõrök között (&lt; és &gt;); hanem szögletes zárójelben "[" "]" vannak;  amellett  lehetõséget nyújt a szövegeket szebben, jobban, tagoltabban megjeleníteni. A használatban lévõ sablontól függ, hogy pontosan hol található a BBCode panel, melyrõl könnyedén és gyorsan be lehet illeszteni a tageket a szövegbe. Fontos, hogy mindig ügyeljünk a tagek lezárására. Egy részletesebb leírás található még a BBCode Gy.I.K-ben, melyet a hozzászólás készítésénél találsz meg.');
$faq[] = array('Használhatok HTML-t kódot?','Ez az Adminisztrátortól függ, õ határozza meg hogy lehet-e használni vagy nem. Ha engedélyezte a használatát, akkor is csak valószínûleg néhány tag fog mûködni. Ennek <i>biztonsági</i> okai vannak; megakadályozza hogy a felhasználók akár véletlenül akár szándékosan megváltoztassák az oldal(ak) formátumát vagy kinézetét, vagy hogy egyéb problémát okozzanak. A HTML kódokat bárki letilthatja a hozzászólásában.');
$faq[] = array('Mik az emotikonok?','Smiley-k vagy másnéven emotikonok kis grafikák, melyekkel érzéseket lehet kifejeztetni. Például a :) jelentése mosolygás, boldogság, a :( jelentése szomorúság. A használható emotikonok teljes listája megtalálhatók a hozzászólás készítésénél. Lehetõleg ne használj túl sok emotikont, mert nehezen lesz olvasható a hozzászólás.');
$faq[] = array('Csatolhatok képeket a hozzászóláshoz?','Egy hozzászólásban képeket is meg lehet jeleníttetni, de ezt csak külsõ webcím megadásával. Jelenleg nincs lehetõség arra, hogy a Fórumra töltsd fel a képeket. A megjelenítéséhez egy publikus, az interneten elérhetõ képet kell megadni, például: http://www.akarmi.hu/kep.jpg. A saját gépen található képeket nem lehet megjeleníteni (kivéve ha fut egy webszerver a gépen); sem a védett oldalakon található képeket (például levélfiókokban: Hotmail, Yahoo, vagy jelszóval védett oldalakon, stb). A kép megjelenítéséhez használd a BBCode [img] tagjét, vagy a megfelelõ HTML taget (amennyiben ez utóbbi engedélyezve van).');
$faq[] = array('Mik azok a közlemények?','A közlemények gyakran fontos információkat tartalmaznak, érdemes ezeket minél hamarabb elolvasni. A közlemények az adott fórumban mindig az oldal tetején, az összes oldalon megtalálhatóak. Ahhoz, hogy valaki közleményt küldjön, megfelelõ jogokkal kell rendelkeznie, melyet az Adminisztrátor állít be.');
$faq[] = array('Mik azok a kiemelt témák?','A kiemelt témák a közlemények alatt jelennek meg, de csak a fórum elsõ oldalán. Ezek általában elég fontos információkat tartalmaznak, ezért ajánlott az elolvasása. Hasonlóan a közleményekhez, az Adminisztrátor dönti el, hogy ki írhat kiemelt témát.');
$faq[] = array('Mik azok a lezárt témák?','A témákat vagy a Moderátorok, vagy az Adminisztrátor zárhatja le. Az ilyen témákba nem lehet több hozzászólást vagy szavazatot küldeni. Egy téma lezárásának több oka lehet.');

$faq[] = array('--','Felhasználói szintek és soportok');
$faq[] = array('Ki az Adminisztrátor?','Az Adminisztrátor a Fórum legmagasabb rangú és jogú felhasználója, õ üzemelteti, és tartja karban. Az egész Fórumhoz hozzáférhet, és módosíthatja, például jogosultságokat adhat, letilthat felhasználókat, csoportokat hozhat létre, Moderátori jogosultságokat adhat, stb. Ezenkívül bármely fórumot és témát moderálhatja. Az Adminisztrátor általában egy személy, de ez Fórumtól függ, van ahol többen rendelkeznek ilyen jogosultsággal.');
$faq[] = array('Kik azok a Moderátorok?','A Moderátorok olyan különleges jogosultságokkal rendelkezõ felhasználók, akiknek az a feladata, hogy napról napra figyelemmel kövessék a fórumok mûködését. Jogukban áll bármely hozzászólás szerkesztése vagy törlése, ezenkívül lezárhatják, kinyithatják, áthelyezhetik, törölhetik vagy szétválaszthatják a témákat, amikben moderálhatnak. Általában az a dolguk, hogy eltávolítsák a témába nem illõ hozzászólásokat, vagy a sértegetõ, támadó hangvételû anyagokat.');
$faq[] = array('Mik azok a csoportok?','Az Adminisztrátor csoportokba rendezheti az azonos érdeklõdési körû felhasználókat. Egy felhasználó több csoportba is tartozhat, és a csoportokhoz különbözõ hozzáférési jogok rendelhetõek. Ezzel könnyedén lehet például zártkörû fórumokat készíteni, vagy moderátori jogokat adni egyszerre több felhasználóknak.');
$faq[] = array('Hogyan csatlakozhatok egy csoporthoz?','A csoportok megtekintéséhez kattints a lap tetején található Csoportok menüpontra. A link helye a használt sablontól függ. Nem minden csoport érhetõ el, lehetnek <i>nyílt</i> csoportok, <i>zárt</i> csoportok, vagy akár <i>rejtett</i> csoportok is. Ha csoport nyitott, akkor a megfelelõ gombra kattintva el lehet küldeni a csatlakozási kérelmet. A csatlakozáshoz szükséges a csoport moderátorának jóváhagyása, megkérdezheti, hogy miért akarsz csatlakozni a csoportba. Ha a moderátor elutasítja a kérelmedet, akkor annak biztosan megvan az oka, így ne õt hibáztasd.');
$faq[] = array('Hogyan lehetek csoport moderátor?','A csoportokat az Adminisztrátor készíti, így a hozzátartozó moderátori jogokat is õ adja ki. Ha saját csoportot akarsz indítani, akkor lépj kapcsolatba az Adminisztrátorral, például egy privát üzenet küldésével.');

$faq[] = array('--','Privát üzenet');
$faq[] = array('Nem tudok privát üzenetet küldeni!','Ennek négy oka lehet: 1. Nem vagy regisztrálva. 2. Nem vagy belépve a Fórumra. 3. Az Adminisztrátor nem engedélyezte a Fórumon privát üzenet küldését. 4. Nem küldhetsz privát üzeneteket. Ha a legutolsó eset áll fenn, lépj kapcsolatba az Adminisztrátorral.');
$faq[] = array('Folyamatosan kéretlen üzeneteket kapok!','A jövõben lehetõség lesz letiltani a nemkívánt privát üzeneteket. Egyelõre erre nincs lehetõség, ha kéretlen üzeneteket kapsz, értesítsd az Adminisztrátort, és õ megteszi a szükséges lépéseket.');
$faq[] = array('Kéretlen vagy sértegetõ leveleket kapok valakitõl a Fórumról!','Ezt sajnálattal halljuk, ebben az esetben a következõ lépéseket tedd meg. Értesítsd az Adminisztrátort, és küldd el neki a kapott levelet, elsõsorban a levél fejléce szükséges (mivel ez tartalmazza a feladó adatait). Az Adminisztrátor meg fogja tenni a szükséges lépéseket.');

$faq[] = array("--","Avatar Generátor");
$faq[] = array("Mi is ez?", "Az <strong>Avatar Generátor</strong> használatával az általunk ajánlott alapokra építkezve saját avatart készíthetsz.");
$faq[] = array("Hol található?", "Be kell jelentkezned az Avatar Generátor használatához. A pontos helye a profilod beállításánál van.");
$faq[] = array("Hogyan tudom az elkészített avatart elmenteni?", "Amikor legenerálod a saját avatarod, lesz ott egy link, ami így hangzik: <strong>Kattints ide, hogy hozzáadd a profilodhoz ezt az avatart</strong>. Ha rákattintasz, akkor kapsz egy üzenetet, ami arról tájékoztat, hogy sikeres volt-e a mûvelet vagy sem.");

$faq[] = array("--","Fotóalbum");
$faq[] = array('Hogyan tudom elérni a fotóalbumot?','Egyszerûen használd az \'Album\' linket a navigációs menüben. Itt megtekintheted a saját fotóalbumodat, illetve minden publikus fotóalbumot. Ha engedélyezve van, akkor a Felhasználók személyes fotóalbuma linkre kattintva mások által megosztott, de személyes értékû képeket is megtekinthetsz.');
$faq[] = array('Hogyan tudok egy képet feltölteni az albumba?','Menj el a fotóalbum index oldalára, és kattints a \'Publikus kategóriákra\' vagy a \'Felhasználók személyes galériájára\'. Ha látsz ott egy \'Kép feltöltése\' gombot az oldal alján vagy tetején, akkor jogod van képet feltölteni. Kattints rá, és kövesd a kapott instrukciókat.');
$faq[] = array('Mi az elfogadott maximális fájlméret, illetve maximális kép szélesség és magasság?','Ezeket a beállításokat megtalálod a \'Kép feltöltése\' oldalon. Az oldal adminisztrátora meghatározta a feltölthetõ legnagyobb fájlméretet, az elfogadott fájltípusokat, és még néhány adatát az Albumba feltölthetõ képeknek.');
$faq[] = array('Milyen formátumú képeket tudok használni?','Ezeket a beállításokat megtalálod a \'Kép feltöltése\' oldalon. Az oldal adminisztrátora meghatározta a feltölthetõ legnagyobb fájlméretet, az elfogadott fájltípusokat, és még néhány adatát az Albumba feltölthetõ képeknek.');
$faq[] = array('Nem tudom feltölteni a képeimet; Mindig hibaüzenetet kapok!','Menj vissza a \'Kép felöltése\' oldalra, és az ott leírtakat pontosan tartsd be. A feltöltendõ fájl a feltöltés elõtt nem lehet nagyobb a Maximálisan elfogadott legnagyobb fájlméretnél, és a kép mérete nem lehet nagyobb az ott meghatározott értékeknél, illetve a feltöltendõ kép formátuma mindenképpen az egyik elfogadott legyen. Persze legtöbbször az a hiba oka, hogy az egyik mezõ nincs kitöltve.');
$faq[] = array('Elrontottam a kép címét vagy meghatározását. Mit tehetek?','Amikor az albumodban megnézed a képet, akkor te egy-két opcióval többet fogsz látni, mint a többiek - ha az adminisztrátor nem tiltotta le. Ezek közé tartozik a \'Szerkeszt\' gomb. Ha rákattintasz, akkor a képnek ezen jellemzõit tudod változtatni.');
$faq[] = array('Hogyan tudok egy képet törölni?','Amikor az albumodban megnézed a képet, akkor te egy-két opcióval többet fogsz látni, mint a többiek - ha az adminisztrátor nem tiltotta le. Ezek közé tartozik a \'Törlés\' gomb, ha a kép a te tulajdonodban van. Ha rákattintva tudod a képet törölni.');
$faq[] = array('Szeretném elmondani, hogy egy kép mennyire ellenszenves vagy kedves számomra. Hogyan tudom ezt megtenni?','Amikor az albumokban megnézed a képeket, akkor egy-két opciót találhatsz ott, amennyiben az adminisztrátor nem tiltotta õket le. Találhatsz közöttük \'Értékel\' és \'Komment\' gombot, amikkel a képrõl vagy bélyegrõl alkotott véleményedet tudod kifejezni.');

$faq[] = array('--','Csatolmányok');
$faq[] = array('Hogyan tudok csatolni?','A hozzászólásaidban használhatsz csatolt állományokat. Látni fogsz <i>Egy csatolmány hozzáadása</i> részt a hozzászólásnál. Ha rákattintasz a Tallózás... gombra, akkor egy általános Megnyitás ablakban kiválaszthatod a feltölteni kívánt fájlt. Jelöld ki a fájlt és kattints az Ok-ra, vagy kattints duplán a fájlra. Ha szeretnéd kommentálni a fájlt, amit érdemes megtenni, akkor azt az alatta lévõ <i>Fájl kommentálása</i> mezõben megteheted. Amikor végeztél mind a fájl kijelölésével, mind a kommentár begépelésével, a <i> Csatolmány hozzáadása</i> gombbal fel tudod tölteni a fájl. Ha a fórum adminisztrátora megengedte, hogy egy hozzászóláshoz több fájlt is fel lehessen tölteni, és te szeretnél több fájlt feltölteni, akkor az elõbbi mûveleteket megismételgetve több fájlt is tudsz csatolni, mígnem eléred az egy hozzászóláshoz csatolható maximális csatolmányok számát.<br/><br/>A fórum adminisztrátora beállíthatja a maximális fájlméretet, az engedélyezett kiterjesztéseket és a csatolmányok más, egyéb tényezõit. Amennyiben ezen szabályoknak nem tesz eleget a csatolmány, akkor figyelmeztetés nélkül törlésre fog kerülni.<br/><br/>Kérlek egyeztess a fórum tulajdonosával, webmesterével, adminisztrátorával vagy moderátoraival, hogy elkerülj egy kellemetlen adatvesztést.');
$faq[] = array('Hogyan tudok csatolni utólag?','Csak szerkesztened kell a hozzászólásodat, és a feljebb lévõ instrukciók alapján fel kell töltened a fájlt. Az új csatolmány akkor lesz hozzáadva, amikor rákattintasz az <i>Elküld</i> gombra a szerkesztés végén.');
$faq[] = array('Hogyan tudok törölni egy csatolmányt?','A csatolmány törléséhez szerkesztened kell a hozzászólást. Csak kattints a <i> csatolmány törlésére</i> a <i>Beküldött csatolmányok</i> dobozban. A csatolmány akkor lesz törölve, amikor rákattintasz az <i>Elküld</i> gombra a szerkesztés végén.');
$faq[] = array('Hogyan tudom frissíteni egy fájl kommentjét?','Egy fájl kommentjének a frissítéséhez szerkesztened kell a hozzászólásod, és ott szerkesztheted a <i>fájl komment</i> mezõt a <i>Beküldött csatolmányok</i> dobozban. Utána kattints a <i>Komment frissítése</i> gombra. A fájl kommentje akkor fog frissülni, amikor rákattintasz az <i>Elküld</i> gombra a szerkesztés végén.');
$faq[] = array('Miért nem látható a csatolmányom a hozzászólásomban?','Legvalószínûbb oka, hogy nem elfogadott formátuma vagy kiterjesztése volt a csatolmánynak, vagy egy moderátor vagy adminisztrátor törölte, mivel ütközött a fórumon érvényes szabályokkal.');
$faq[] = array('Miért nem tudok csatolni?','Elõfordulhat, hogy a csatolmány lehetõsége le van korlátozva pár felhasználóra, vagy csoportra. Amennyiben a csatolmányok használatához különleges jogokra van szükség, akkor annak a megállapítása, hogy számodra szükséges-e ez a funkció, a fórum egyik moderátorának vagy adminisztrátorának a hatásköre.');
$faq[] = array('Mit nézzek meg elsõnek, ha nem tudok csatolni egy fájlt?','A fórum adminisztrátora beállíthatott egy maximális fájlméretet, elfogadott fájlkiterjesztéseket és más dolgokat a csatolmányokkal kapcsolatban. Egy moderátor vagy adminisztrátor megváltoztathatta a jogosultságokat vagy akadályozhatja a fórumba történõ csatolást. Általában a sikertelen csatolásról kapsz egy hibaüzenetet. Ha mégsem, akkor fordulj a moderátorokhoz vagy egy adminisztrátorhoz.');
$faq[] = array('Miért nem tudok törölni csatolmányt?','Elõfordulhat, hogy a csatolmány törlésének lehetõsége le van korlátozva pár felhasználóra, vagy csoportra. Amennyiben a csatolmányok törléséhez különleges jogokra van szükség, akkor annak a megállapítása, hogy számodra szükséges-e ez a funkció, a fórum egyik moderátorának vagy adminisztrátorának a hatásköre.');
$faq[] = array('Miért nem tudok megtekinteni/letölteni csatolmányt?','Elõfordulhat, hogy a csatolmány megtekintésének/letöltésének lehetõsége le van korlátozva pár felhasználóra, vagy csoportra. Amennyiben a csatolmányok megtekintéséhez/letöltéséhez különleges jogokra van szükség, akkor annak a megállapítása, hogy számodra szükséges-e ez a funkció, a fórum egyik moderátorának vagy adminisztrátorának a hatásköre.');
$faq[] = array('Kit értesítsek illegális vagy valószínûleg illegális csatolmányról?','Lépj kapcsolatba az oldal adminisztrátorával. Ha nem találod az elérhetõségét, akkor keress egy moderátort, aki továbbadja az üzeneted majd neki. Ha nem találsz semmilyen kapcsolati oldalt, és a domain tulajdonosa (whois) sem válaszol, vagy ha ez egy ingyenes szolgáltató (pl. yahoo, free.fr, f2s.com, stb.); próbáld a vezetõséget vagy az alkalmazottakat a szolgáltatáson keresztül elérni. Kérünk vedd figyelembe, hogy semmilyen lehetõségünk és szándékunk nincs korlátozni vagy elõírni a szoftverünk használatát. Abszolút felesleges a phpBB Csoportnak üzenned bármiféle tartalmi dologgal, akár téged, akár a jogot sértette meg. Nincsen semmiféle lehetõségünk a szoftvert vagy a tartalmat használat közben módosítani, illetve a szoftver használata a phpbb.com oldaltól mindig teljesen függetlenül valósul meg. Ha írsz egy emailt a phpBB Csoportnak egy harmadik személlyel kapcsolatban, akkor jobb esetben csak elhajtunk, rosszabb esetben nem is válaszolunk.');

$faq[] = array('--','Letöltések ADV');
$faq[] = array('Hol találom a letöltéseket?','A Letöltések linkje megtalálható a navigációs menüben, illetve a nyitóoldalról is vezet oda link. Közvetlen link: [<a href="downloads.php">Letöltések</a>]');
$faq[] = array('Mit jelent a <img border="0" src="' . $images['Dl_blue'] . '" alt="" title="" />?','Nem tudsz letölteni. Az oldal adminisztrátora valamilyen indokból méri a havi forgalmadat. Elérted az engedélyezett adatforgalmat ebben a hónapban.');
$faq[] = array('Mit jelent a <img border="0" src="' . $images['Dl_red'] . '" alt="" title="" />?','Nem tudsz letölteni. Az alábbi okok bármelyike lehet:<br />- Letiltotta a letöltéseket az adminisztrátor.<br />- A felhasználó nincs bejelentkezve, de a letölteni csak regisztrált felhasználók tudnak.<br />- A felhasználónak nem maradt elegendõ sávszélessége a fájl letöltéséhez.<br />- Az adminisztrátor meghatározott a letöltésekhez egy minimális hozzászólásszámot, és a felhasználó ezt még nem érte el.<br />- Az ehhez a fájlhoz megadott letöltési limit már el lett asználva.');
$faq[] = array('Mit jelent a <img border="0" src="' . $images['Dl_gray'] . '" alt="" title="" />?','Külsõ forrás. A letöltés egy külsõ szerverrõl fog történni. Használd úgy, mint a <img border="0" src="' . $images['Dl_green'] . '" alt="" title="" />-ot. A felhasználói és az összesített adatforgalomba nem számít bele a fájl letöltése.');
$faq[] = array('Mit jelent a <img border="0" src="' . $images['Dl_white'] . '" alt="" title="" />?','Ugyanúgy, mint a <img border="0" src="' . $images['Dl_green'] . '" alt="" title="" />-nál, itt sem számít bele a felhasználói forgalomba a letöltése., viszot csak bejelentkezett felhasználóknak engedélyezett a letöltése. Az összesített adatforgalomba beleszámít a letöltés.');
$faq[] = array('Mit jelent a <img border="0" src="' . $images['Dl_yellow'] . '" alt="" title="" />?','Letölthetõ bizonyos megszorításokkal. Letölteni csak regisztrált és bejelentkezett felhasználóknak engedélyezett, illetve a havi adatforgalmi korlátba és az összesített adatforgalomba beleszámít a fájl teljes mérete.');
$faq[] = array('Mit jelent a <img border="0" src="' . $images['Dl_green'] . '" alt="" title="" />?','Szabad letöltés. A letöltése nincs korlátozva. Ezt a fájlt vendégek is letölthetik, illetve a letöltéséhez nem szükséges bejelentkezni. Bár a felhasználói adatforgalomba nem számít bele a letöltése, az összesített adatforgalomba beleszámít.');
$faq[] = array('Miért nem tudok letölteni semmilyen fájlt?','Ennek több oka is lehet. Nézd meg a <img border="0" src="' . $images['Dl_blue'] . '" alt="" title="" /> és a <img border="0" src="' . $images['Dl_red'] . '" alt="" title="" /> magyarázatát.');
$faq[] = array('Hogyan és mikor tudok új forgalmi korlátot szerezni a felhasználómhoz?','Amikor elsõnek beléptél a weboldalra, kaptál egy idõbélyeget. Ez az idõpont jelenti neked a mért hónap elsõ napját. Minden hónapban, pont azon a napon újrakezdõdik a havi forgalom mérése. Ha szükséged van erre az idõpontra, akkor az adminisztrátor biztosan meg tudja neked adni.');
$faq[] = array('Mit tudok tenni, ha le szeretnék tölteni egy fájlt, de nem maradt több adatforgalmam?','A kéréseddel fordulj egy adminisztrátorhoz. Csak indokolt esetben engednek a havi forgalmi korlátnál többet letölteni, de ha vársz a hónap végéig, akkor automatikusan lenullázódik az adatforgalmad, és ismét tudsz letölteni.');
$faq[] = array('Hogyan tudom értékelni a letöltéseket?','Minden letöltési kategóriánál vagy részletes nézetnél van egy rész, ahol értékelni tudsz.<br />Kattints az "Értékel" gombra regisztrált felhasználóként, és egy 1-tõl (nagyon rossz) 10-ig (nagyon jó) skálán tudod kifejezni a letöltés minõségét. Minden letöltést egyszer tudsz csak értékelni.');

$faq[] = array('--','Kivonatok');
$faq[] = array('Mi az a kivonat?','Egy periodikusan elkészített és emailben elküldött tömör üzenet, ami a fórum legfrissebb eseményeit, hozzászólásait tartalmazza. Heti és napi kivonatokat tudunk biztosítani.');
$faq[] = array('Miért kéne nekem egy kivonat?','Éld könnyen az életed. Ha nem keresed állandóan az új hozzászólásokat, könnyen le tudsz maradni egy számodra érdekes témáról, viszont ha kapsz kivonatot, akkor azt átfutva láthatod, ha valami érdekes, és a levelezõkliensbõl egy kattintással a társalgás közepébe ugorhatsz. Ha mégsem tetszik, akkor még mindig le tudsz iratkozni bármikor.');
$faq[] = array('Milyen gyakran készül kivonat?','Napi vagy heti rendszerességgel. A heti kivonatokat vasárnap küldjük el.');
$faq[] = array('Mikor küldik a kivonatokat?','Te határozod meg azt az órát, amikor elküldésre kerül a kivonatod. Válaszd azt az idõpontot, amikor egyébként is a friss híreket, eseményeket szoktad olvasni.');
$faq[] = array('Milyen idõt ölel fel egy kivonat?','Vagy 24 órát, vagy 7 napot, attól függõen, hogy heti vagy napi kivonatokra jegyeztél elõ. Az ezen idõszaknál régebbi hozzászólásokat nem küldi el újra. Valamint szûkítheted az üzenetek számát a legutolsó ittjártadnál frissebb hozzászólásokra, illetve a saját hozzászólásaid is kiszûrheted a kivonatból.');
$faq[] = array('Nem szeretnék minden üzenetrõl összegzést kapni. Tudok kijelölni tartalmakat?','Igen. Meg tudod jelölni azokat a fórumokat, amelyek érdekelnek. Alapértelmezésben minden olyan fórumról kapsz összegzést, amelyet jogod van elolvasni.');
$faq[] = array('Az emailnek milyen formátuma van?','El tudjuk küldeni HTML és szöveges formátumban is. Ha a levelezõkliensed nem tudja, vagy nem helyesen kezeli a HTML üzeneteket, akkor kerüld a HTML formátumot. A szöveges üzeneteket minden levelezõkliens tudja kezelni, és mi nagyon szép, tiszta üzeneteket tudunk küldeni. Javasoljuk, használj te is tiszta, szöveges formátumú leveleket.');
$faq[] = array('Megkapom a teljes üzenetet kivonatban?','Alapértelmezésben a szövegek elsõ 150 karakterét kapod meg, amit megnövelhetsz akár addig, hogy válogatás nélkül az összes üzenet és téma teljes szövegét megkapod. Kiválaszthatod, hogy a kivonat az elsõ 50, 100, 150, 300 vagy 600 karaktert, vagy z üzenet teljes szövegét tartalmazza (egészen 32,000 karakterig). Minden, ami a beállításodnál hosszabb le lesz vágva. Azt tanácsoljuk, hogy az alapértelmezett beállításokat hagyd meg, különben a kivonat a mérete miatt könnyen használhatatlan lehet. Illetve egy nagyobb kivonatot a szolgáltató sokszor visszautasít, vagy egyszerûen a tárhelyed feltölti. Egy jó kivonat csak kevés információt tartalmaz. Miért? Mert minden hozzászólás végén találsz egy linket, ami az üzenet további részére mutat. Így könnyen tudod folytatni a számodra érdekes témát vagy hozzászólást.');
$faq[] = array('Hogyan kezdjem?','Kattints a kivonatok linkre a navigációs panelon, vagy közvetlenül erre a linkre: <a href="./digests.php">Kivonatok</a>.');
$faq[] = array('Le lehet iratkozni?','Természetesen! Menj vissza ugyanarra az oldalra, és válaszd ki a "Nincs"-et a "Kivonat kézbesítésének típusa" rovatnál. Ezután küldd el az ûrlapot. A feliratkozásod azonnal törlõdik.');
$faq[] = array('A kivonatok üzleti érdektõl mentesek?','Természetesen. Nem küldünk vele reklámot,  és nem szeretnénk vele eladni neked semmit sem.');
$faq[] = array('Az adataimat biztonságban vannak?','Igen, a kivonatodat csak neked küldjük el - arra az email címre, amit a profilodban megadtál, - és senki másnak. A kivonatot mi egy különleges, személyre szabható hírszolgálatnak szánjuk, és minden ettõl eltérõ dologtól mentesen szeretnénk megtartani.');


$faq[] = array('--','Információ az "Olvasatlan hozzászólások 2 adatbázisról" (UPI2DB)');
$faq[] = array('Mi a különbség az általános sütis rendszer és az UPI2DB rendszere között?','A sütis rendszer a phpBB2 fórumok alapértelmezése. Amikor elolvasol egy hozzászólást, akkor az arról szóló információk a számítógépeden sütiként tárolódik le. A legnagyobb hátránya ennek a rendszernek, hogy a böngészõt bezárva elveszted az olvasottnak és olvasatlannak megjelölt hozzászólásokról készített információkat. Az UPI2DB rendszere nem használ sütiket, hanem egy külön ere a célra tartott adatbázisban tárolja az információkat.');
$faq[] = array('Mi az elõnye és a hátránya a sütis rendszernek?','<strong>Elõny:</strong> Nagyobb fórumnál a sütis rendszer gyorsabb lapbetöltést eredményez, mert ezzel a rendszerrel nem kell állandóan betölteni az olvasott hozzászólások adatbázisából a szükséges információt. További elõny, hogy az adatok tárolva maradnak a gépen akár több hónapig is, amennyiben a felhasználó nem törli az adatait a gépérõl. Ez általában csak a 2 hónapnál ritkábban fórumozó felhasználóknál tud gondot okozni.<br /><strong>Hátrány:</strong> A legnagyobb hátrány, hogy ez a rendszer minden hozzászólást automatikusan olvasottnak jelöl a böngészõbõl való kilépéskor. További hátrány, hogy a szerkesztett hozzászólásokat szintén olvasatlanként jelöli meg, így mindenkit ismét értesít a hozzászólásról.');
$faq[] = array('Mi az elõnye és a hátránya az UPI2DB rendszernek?','<strong>Elõny:</strong> Az olvasatlan hozzászólások olvasatlanok maradnak attól függetlenül, hogy a böngészõt bezárták-e.  A hozzászólások megjelölhetõek olvasottnak, és ' . (!empty($unread_days) ? $unread_days : 0) . ' napig azok is maradnak az UPI2DB rendszerrel. A fórumokat nem kötelezõ meglátogatni az olvasott jelzõ érdekében, be lehet állítani egy "végleg olvasott" jelzõt, így olvasott marad hozzászólás vagy szerkesztés esetén is. A szerkesztett hozzászólások nem újként, hanem "Szerkesztett" jelzõvel jelennek meg., illetve más szín társítható hozzájuk, így kitûnnek az olvasatlan hozzászólásokból. Az új keresõ engedi az olvasatlan és szerkesztett hozzászólásokra szûkítést. Amikor az adminisztrátor szerkesztettként megjelöl egy hozzászólást, akkor az a témakör elején fog szerepelni.<br /><strong>Hátrány:</strong> Nagyobb fórumokban, sok felhasználóval illetve hozzászólással, nagyon meg tudja növelni a lap betöltési idejét. Az adatbázisban tárolt elolvasási idõket nem célszerû hosszú ideig megtartani, és bizonyos idõ után a rendszer sebessége miatt érdemes eldobni az olvasottsági jelzõket. Az alapértelmezett idõköz 30 nap, de ezt könnyen át tudja állítani az adminisztrátor.');
$faq[] = array('Nem találok semmilyen kapcsolót a profilomban, amivel a sütis és az UPI2DB rendszer között átkapcsolhatok','Ha nem látsz ilyen kapcsolót, akkor a rendszer adminisztrátora állandóra állítva ki vagy bekapcsolta az UPI2DB rendszerét. Csak akkor látható ilyen kapcsoló, ha az adminisztrátor engedélyezi a két rendszer közötti átkapcsolást.');
$faq[] = array('Milyen beállításokkal élhet az adminisztrátor?','Az alapértelmezett UPI2DB rendszer az adminisztrátornak megengedi, hogy meghatározzon egy minimális hozzászólásszámot vagy/és a regisztrációtól számított minimális idõtartamot, amelyek teljesülése elõtt nem lehet aktiválni a rendszert.');
$faq[] = array('Bármit teszek, nem tudok fontos közleményt vagy eseményt olvasottként megjelölni!','Fontos közleményt és eseményt nem lehet olvasottként megjelölni! Illetve nem lehet érvényes rajtuk a "Minden fórum és hozzászólás olvasottként megjelölése" vagy a "Mutasd az olvasatlan hozzászólásokat" funkciók!');
$faq[] = array((!empty($unread_days) ? $unread_days : 0) . ' naponként minden "végleg olvasottként" megjelölt közleményt újra meg kell jelölnöm!','Ezt sajnos nem tudod megváltoztatni, beállítani. Ennyi nap az elévülési ideje a megjelölt közleményeknek. Ha nem tisztogatná magát a rendszer automatikusan, akkor nagyon lelassulna az oldal.');
$faq[] = array('Hogyan tudok egy teljes fórumot "végleg olvasottként" megjelölni?','Kattints a fórum képére a fórum nyitólapján. A beállítást a fórum képének megváltozásán fogod látni.');
$faq[] = array('Hogyan tudok egy témát "végleg olvasottként" megjelölni?','Kattints a téma képére a fórumban. A beállítást a téma képének megváltozásán fogod látni, illetve a téma a fórum végére kerül. Egy másik lehetõség a "téma végleg olvasottként megjelölése" ikonra kattintani a téma fejlécén.');
$faq[] = array('Nem tudok fontos közleményt vagy eseményt "végleg olvasottként" megjelölni!','Fontos közleményt és eseményt nem lehet "végleg olvasottként" megjelölni, mert ezeket nagyon fontos információknak szánták!');
$faq[] = array('Megjelöltem egy fórumot "végleg olvasottként", de továbbra is van benne új hozzászólás!','A fontos közleményekre és az eseményekre nincsen hatással az ilyen megjelölés. Ezek nagyon fontos információt tartalmaznak, és szeretnék, hogy mindenképpen értesülj róluk!');
$faq[] = array('Ha megjelöltem egy közleményt, miért futok bele ismét?','Minden közleménynél találsz egy gombot a címsorban, amivel azt meg tudod jelölni. Amennyiben a közlemény régebbi, mint ' . (!empty($unread_days) ? $unread_days : 0) . ' nap, vagy a közleményt az elõtt írták, mielõtt regisztráltál volna az oldalra, akkor nem tudod megjelölni.');
$faq[] = array('Hogyan tudok egy már olvasott hozzászólást "olvasatlannak" megjelölni?','Minden hozzászólás fejlécében található egy link, amivel ezt elvégezheted. Ezzel a linkkel megjelölsz minden hozzászólást, akkor minden beküldött vagy szerkesztett hozzászólás meg lesz jelölve mint új vagy szerkesztett.');
$faq[] = array('Miért nem tudok néhány hozzászólást megjelölni?','Minden "végleg olvasott" fórum vagy témakrben lévõ hozzászólás szintén jelöltnek számít., illetve a regisztrálásod elõtti hozzászólások nem jelölhetõek meg. Azok a hozzászólások, amik ' . (!empty($unread_days) ? $unread_days : 0) . ' napnál régebbiek, számodra nem jelölhetõek meg.');
$faq[] = array('A jelölések végleg megmaradnak?','Nem. Minden beállítás automatikusan törlésre kerül a beállítástól számított ' . (!empty($unread_days) ? $unread_days : 0) . '-dik napon');
$faq[] = array('Mit jelent az OLV?','Az "Olvasott" rövidítése.');


$faq[] = array('--','phpBB 2 dolgok');
$faq[] = array('Ki írta ezt a faliújság típusú fórumot?','Ez a szoftver (módosítatlan formában) a <a href="http://www.phpbb.com/" target="_blank">phpBB Csoport</a> által elérhetõ, kiadott és jogvédett. Mindez a GNU General Public License keretei között, ami megengedi, hogy a kódot szabadon módosítsd és továbbadd; Kattints a linkre további részletekért');
$faq[] = array('Miért nincs X dolog?','Ezt a szoftvert a phpBB Csoport írta és adta ki. Ha egy bizonyos dolgot hiányolsz a programban, kérünk látogass el a phpbb.com weboldalra, és beszéld meg ezt a phpBB Csoporttal. Kérünk továbbá arra is, hogy új dolgot ne javasoljál a phpBB fórumokon, mert azokat a SourceForge keretei között kezeljük. A fórumokat olvasd el, illetve tájékozódj onnan, így megtudod, hogy milyen eljárás alapján tudsz egy új dolgot kérni.');
$faq[] = array('Kivel léphetek kapcsolatba, ha bármiféle jogi vagy /és személyes problémám van ezzel a weboldallal?','Lépj kapcsolatba az oldal adminisztrátorával. Ha nem találod az elérhetõségét, akkor keress egy moderátort, aki továbbadja az üzeneted majd neki. Ha nem találsz semmilyen kapcsolati oldalt, és a domain tulajdonosa (whois) sem válaszol, vagy ha ez egy ingyenes szolgáltató (pl. yahoo, free.fr, f2s.com, stb.); próbáld a vezetõséget vagy az alkalmazottakat a szolgáltatáson keresztül elérni. Kérünk vedd figyelembe, hogy semmilyen lehetõségünk és szándékunk nincs korlátozni vagy elõírni a szoftverünk használatát. Abszolút felesleges a phpBB Csoportnak üzenned bármiféle tartalmi dologgal, akár téged, akár a jogot sértette meg. Nincsen semmiféle lehetõségünk a szoftvert vagy a tartalmat használat közben módosítani, illetve a szoftver használata a phpbb.com oldaltól mindig teljesen függetlenül valósul meg. Ha írsz egy emailt a phpBB Csoportnak egy harmadik személlyel kapcsolatban, akkor jobb esetben csak elhajtunk, rosszabb esetben nem is válaszolunk.');
$faq[] = array('--','Az Icy Phoenix-rõl');
$faq[] = array('Mi az Icy Phoenix?','Az Icy Phoenix egy CMS (Content Management System - Tartalomkezelõ Rendszer); amivel a felhasználók könnyen tudnak dinamikus tartalmakat megosztani egymással, illetve sok beépített funkcióval is rendelkezik: fórum, portál, átszabható lapok és blokkok, letöltések, fotógaléria és még sok más.');
$faq[] = array('Ki írta ezt a szoftvert?','Ez a szoftver a GNU General Public License keretei között kiadott phpBB, így az Icy Phoenix is ugyanezen licenc hatálya alá tartozik, ezért módosíthatod és sokszorosíthatod is bármely részét, vagy egészét. A phpBB központi részét képzõ fájlokon kívül programozást vagy a fájlok módosításait Mighty Gorgon és az <a href="http://www.icyphoenix.com/" target="_blank">Icy Phoenix Staff</a> végezte. Egy nem biztos, hogy teljes lista a résztvevõkrõl itt található: <a href="http://www.icyphoenix.com/credits.php" target="_blank">Icy Phoenix Credits</a>.');
$faq[] = array('Kivel léphetek kapcsolatba, ha bármiféle jogi vagy /és személyes problémám van ezzel a weboldallal?','Lépj kapcsolatba az oldal adminisztrátorával. Ha nem találod az elérhetõségét, akkor keress egy moderátort, aki továbbadja az üzeneted majd neki. Ha nem találsz semmilyen kapcsolati oldalt, és a domain tulajdonosa (whois) sem válaszol, vagy ha ez egy ingyenes szolgáltató (pl. yahoo, free.fr, f2s.com, stb.), próbáld a vezetõséget vagy az alkalmazottakat a szolgáltatáson keresztül elérni. Kérünk vedd figyelembe, hogy semmilyen lehetõségünk és szándékunk nincs korlátozni vagy elõírni a szoftverünk használatát. Abszolút felesleges a Icy Phoenix-nek üzenned bármiféle tartalmi dologgal, akár téged, akár a jogot sértette meg. Nincsen semmiféle lehetõségünk a szoftvert vagy a tartalmat használat közben módosítani, illetve a szoftver használata a icypoenix.com oldaltól mindig teljesen függetlenül valósul meg. Ha írsz egy emailt az Icy Phoenix-nek egy harmadik személlyel kapcsolatban, akkor jobb esetben csak elhajtunk, rosszabb esetben nem is válaszolunk.');


?>