<?php
/**
*
* @package Icy Phoenix
* @version $Id$
* @copyright (c) 2008 Icy Phoenix
* @license http://opensource.org/licenses/gpl-license.php GNU Public License
*
*/

//
// To add an entry to your FAQ simply add a line to this file in this format:
// $faq[] = array("question", "answer");
// If you want to separate a section enter $faq[] = array("--","Block heading goes here if wanted");
// Links will be created automatically
//
// DO NOT forget the ; at the end of the line.
// Do NOT put double quotes (") in your FAQ entries, if you absolutely must then escape them ie. \"something\"
//
// The FAQ items will appear on the FAQ page in the same order they are listed in this file
//

$faq[] = array("--", "Login e Registrazione");
$faq[] = array("Perch&eacute; non riesco ad entrare?", "Ti sei registrato? Devi registrarti per poter entrare. Sei stato disabilitato dal forum (se &egrave; cos&igrave; ti viene mostrato un messaggio)? Se &egrave; cos&igrave; devi contattare il webmaster o l'amministratore del forum per capire perch&eacute;. Se ti sei registrato e non sei stato disabilitato e ancora non riesci ad entrare allora controlla e ricontrolla username e password. Di solito il problema &egrave; questo, altrimenti contatta l'amministratore del forum, potrebbe esserci una configurazione non corretta.");
$faq[] = array("Perch&eacute; devo registrarmi?", "Potresti non averne bisogno, dipende dall'amministratore del forum se &egrave; necessario registrarsi per inviare messaggi. Comunque, la registrazione ti dar&agrave; accesso ad altre funzioni che non sono disponibili per gli utenti ospiti come l'utilizzo di un'immagine avatar definibile, messaggistica privata, possibilit&agrave; di inviare email direttamente dal forum, iscrizione a gruppi di utenti, ecc. Ti bastano pochi minuti per registrarti e quindi ti raccomandiamo di farlo.");
$faq[] = array("Perch&eacute; vengo disconnesso automaticamente dal forum?", "Se non selezioni <i>Entra automaticamente</i>, il forum ti terr&agrave; connesso per un periodo prestabilito. Questo serve ad evitare che qualcuno utilizzi il tuo account. Per rimanere connesso, seleziona l'opzione quando entri, ma ricorda che questo non &egrave; consigliato se ti colleghi da un computer utilizzato da altri, es. biblioteca, internet caf&egrave;, universit&agrave;, ecc.");
$faq[] = array("Come posso evitare di apparire nella lista degli utenti in linea?", "Nel tuo profilo trovi l'opzione <i>Non mostrare se sei on-line</i>: se la attivi, apparirai solo all'amministratore del forum e a te stesso. Verrai contato come utente nascosto.");
$faq[] = array("Ho perso la mia password!", "Niente panico! La tua password non pu&ograve; essere recuperata, ma pu&ograve; essere re-impostata. Per far questo vai nella pagina del login e clicca su <u>Ho dimenticato la mia password</u>, segui le istruzioni e tornerai in linea in poco tempo.");
$faq[] = array("Mi sono registrato ma non riesco ad entrare!", "Innanzitutto controlla di aver inserito lo username e la password corretti. Se sono giusti, allora possono esser successe un paio di cose: se il supporto COPPA &egrave; abilitato e hai cliccato su <u>Ho meno di 13 anni</u> mentre ti stavi registrando, allora devi seguire le istruzioni che hai ricevuto. Se questo non &egrave; il tuo caso, magari devi attivare il tuo account. Alcuni forum richiedono che tutte le nuove registrazioni vengano attivate, o dall'utente stesso o dall'amministratore, prima di poter entrare. Quando ti registri ti verr&agrave; detto che tipo di attivazione &egrave; richiesta. Se ti &egrave; stata inviata un'e-mail, allora segui le istruzioni; se non hai ricevuto nessuna e-mail... sei sicuro che il tuo indirizzo e-mail sia valido? (L'attivazione via e-mail serve a ridurre la possibilit&agrave; di avere utenti anonimi che <i>abusano</i> del forum). Se sei sicuro che l'indirizzo e-mail che hai usato sia giusto, allora prova a contattare l'amministratore del forum.");
$faq[] = array("Mi sono registrato tempo fa, ma non riesco pi&ugrave; ad entrare!", "Le ragioni pi&ugrave; probabili sono: hai inserito uno username o una password sbagliati (verifica l'e-mail che ti &egrave; stata mandata la prima volta che ti sei registrato), oppure l'amministratore ha cancellato il tuo account per qualche ragione. Se il motivo &egrave; quest'ultimo allora forse non hai mai inviato un messaggio. Di solito i forum rimuovono periodicamente gli utenti che non hanno mai inviato un messaggio per ridurre la grandezza del database. Prova a registrarti di nuovo e farti coinvolgere dalle discussioni.");


$faq[] = array("--", "Impostazioni e Preferenze");
$faq[] = array("Come cambio le mie impostazioni?", "Tutte le tue impostazioni (se sei registrato) sono conservate nel database. Per modificarle clicca il link <u>Profilo</u> (generalmente sta in cima ad ogni pagina, ma questo potrebbe non essere il caso). Questo ti permetter&agrave; di cambiare tutte le tue impostazioni.");
$faq[] = array("L'ora non &egrave; corretta!", "L'ora &egrave; quasi sicuramente corretta, comunque l'ora che stai vedendo potrebbe essere quella di un fuso orario differente dal tuo. Se cos&igrave; fosse, devi cambiare le impostazioni del tuo profilo per il fuso orario e farlo coincidere con la tua area, es. London, Paris, New York, Sydney, ecc. Nota che solo gli utenti registrati possono cambiare il fuso orario e molte impostazioni.");
$faq[] = array("Ho cambiato il fuso orario ma l'ora &egrave; ancora sbagliata!", "Se sei sicuro di aver impostato il fuso orario corretto e l'ora &egrave; ancora sbagliata, il motivo pu&ograve; essere l'ora legale. Il forum non &egrave; programmato per calcolare le differenze di orario tra ora legale e ora solare quindi durante il periodo dell'ora legale l'ora potrebbe essere diversa dall'ora locale.");
$faq[] = array("La mia lingua non &egrave; nella lista!", "L'amministratore potrebbe non aver installato la tua lingua nel forum oppure nessuno ha tradotto il forum nella tua lingua. Prova a chiedere all'amministratore se &egrave; possibile installare la tua lingua nel forum. Se non esiste puoi fare tu una nuova traduzione. Puoi trovare altre informazioni nel sito Icy Phoenix (trovi il link in fondo alle pagine).");
$faq[] = array("Come posso mostrare un'immagine sotto il mio username?", "Ci possono essere due immagini sotto uno username quando si guardano i messaggi. La prima &egrave; l'immagine associata al tuo grado, generalmente ha la forma di stelle o blocchi che indicano quanti messaggi hai scritto o il tuo stato nei forum. Sotto pu&ograve; esserci un'immgine pi&ugrave; larga nota come <u>Avatar</u>, che in genere &egrave; unica o personale per ogni utente. L'amministratore del forum decide se abilitare o meno gli avatar e decide anche il modo in cui gli avatar sono messi a disposizione. Se non ti &egrave; concesso l'uso degli avatar, allora &egrave; una decisione dell'amministratore, e devi chiedere a lui le ragioni.");
$faq[] = array("Come cambio il mio grado?", "In genere non puoi cambiare direttamente il nome del tuo grado (i gradi compaiono sotto al tuo username nei topic e nel tuo profilo, a seconda dello stile che stai usando). Molti forum utilizzano i gradi per indicare il numero di messaggi che hai scritto e per identificare certi utenti, ad es. moderatori e amministratori possono avere un livello specifico. Per favore non abusare del forum inviando messaggi non necessari solo per aumentare il tuo grado; se fai cos&igrave;, i moderatori o l'amministratore probabilmente abbasseranno il numero dei tuoi messaggi.");
$faq[] = array("Perch&eacute; quando clicco sul collegamento all'e-mail di un utente mi chiede di fare il login?", "Spiacente, ma solo gli utenti registrati possono inviare e-mail ad altri utenti utilizzando il modulo di invio e-mail interno (se l'amministratore ha abilitato la funzione). Questo serve a prevenire un uso scorretto e malizioso del sistema di e-mail da parte di utenti anonimi.");


$faq[] = array("--", "Invio Messaggi");
$faq[] = array("Come invio un topic in un forum?", "Facile, clicca sul bottone nelle pagine dei forum o dei topic. Potresti aver bisogno di registrarti prima di poter inviare un messaggio, le tue funzioni disponibili sono elencate in fondo alla pagina del forum o del topic (la lista <i>Puoi inviare nuovi topic, Puoi votare nei sondaggi</i>, ecc.).");
$faq[] = array("Come modifico o cancello un messaggio?", "Puoi solo modificare o cancellare i tuoi messaggi, a meno che tu non sia l'amministratore o un moderatore del forum. Puoi cancellare un messaggio cliccando sul bottone con la \"X\" nel messaggio che vuoi eliminare. Puoi modificare un messaggio (a volte solo per un limitato periodo di tempo dopo il suo inserimento) cliccando sul bottone <i>edit</i> nel messaggio in questione. Se qualcuno ha gi&agrave; risposto al tuo messaggio, quando effettui una modifica troverai del testo aggiunto in fondo al messaggio dove viene mostrato quante volte hai modificato il messaggio. Questo non apparir&agrave; solo se nessuno ha risposto o se un moderatore o l'amministratore modificano il messaggio (dovrebbero lasciare un messaggio che dice perch&eacute; e cosa hanno modificato). Un utente normale in genere non pu&ograve; cancellare un messaggio dopo che qualcuno ha risposto.");
$faq[] = array("Come aggiungo una firma ai miei messaggi?", "Per aggiungere una firma ad un messaggio devi prima crearne una, cosa che puoi fare modificando il tuo profilo. Una volta creata la firma, seleziona l'opzione <i>Aggiungi la firma</i> quando scrivi un messaggio per aggiungerla. Puoi anche decidere di aggiungere sempre la firma a tutti i tuoi messaggi selezionando l'apposita opzione <i>Aggiungi sempre la firma</i> nel tuo profilo (puoi sempre evitare di aggiungere la firma deselezionando l'opzione quando scrivi un messaggio).");
$faq[] = array("Come creo un sondaggio?", "Creare un sondaggio &egrave; facile: quando inizi un nuovo topic (o quando modifichi il primo messaggio di un topic, se ti &egrave; permesso) dovresti vedere, sotto lo spazio per l'inserimento del messaggio, un form dal titolo <i>Aggiungi un sondaggio</i> (se non lo vedi, probabilmente il tuo utente non ha il diritto di fare sondaggi). Basta inserire un titolo per il sondaggio e almeno due opzioni di risposta (per inserire un opzione di risposta, scrivila nell'apposito spazio e clicca su <i>Aggiungi opzione</i>). Puoi anche stabilire i giorni di durata del sondaggio (0 per non porre limiti). C'&egrave; un limite al numero di opzioni di risposta che puoi aggiungere, stabilito dall'amministratore.");
$faq[] = array("Come modifico o cancello un sondaggio?", "Come per i messaggi, i sondaggi possono essere modificati e cancellati solo dagli rispettivi autori, dai moderatori e dall'amministratore. Per modificare un sondaggio, clicca sul pulsante <i>edit</i> del primo messaggio (a cui &egrave; sempre associato il sondaggio). Se nessuno ha ancora votato, allora il sondaggio pu&ograve; essere modificato o cancellato, altrimenti solo i moderatori e l'amministratore possono farlo.");
$faq[] = array("Perch&eacute; non riesco ad accedere ad un forum?", "Alcuni forum potrebbero essere riservati a determinati utenti o gruppi. Per leggere, scrivere, rispondere, ecc., potresti aver bisogno di autorizzazioni speciali, che solo i moderatori e l'amministratore possono concedere.");
$faq[] = array("Perch&eacute; non posso votare nei sondaggi?", "Solo gli utenti registrati possono votare nei sondaggi (questo per evitare risultati fasulli). Se sei registrato e comunque non riesci a votare, probabilmente non hai i diritti d'accesso appropriati.");


$faq[] = array("--", "Formattazione e Tipi di Topic");
$faq[] = array("Cos'&egrave; il BBCode?", "Il BBCode &egrave; una speciale implementazione dell'HTML; il suo utilizzo &egrave; precluso dalla scelta dell'amministratore (puoi anche disabilitarlo di messaggio in messaggio tramite l'opzione nel form di invio messaggi). Il BBCode &egrave; simile all'HTML, i comandi sono racchiusi tra parentesi quadre [ e ] anzich&eacute; tra &lt; e &gt; e offre un controllo maggiore su cosa e come viene mostrato nei messaggi. Per maggiori informazioni sul BBCode leggi la guida, accessibile dalla pagina di invio messaggi (oppure cliccando <a href=\"faq.php?mode=bbcode\">qui</a>).");
$faq[] = array("Posso usare l'HTML?", "Dipende se l'amministratore ti permette di farlo. Se ti &egrave; permesso, ci sono alcuni comandi funzionano; questa &egrave; una misura di <i>sicurezza</i> per evitare che certe persone abusino del forum usando comandi che potrebbero rovinare l'impaginazione o causare altri problemi. Se l'HTML &egrave; abilitato, puoi sempre disattivarlo.");
$faq[] = array("Cosa sono gli Smileys?", "Gli Smileys, o Emoticons o \"faccine\", sono piccole immagini  che possono essere usate per esprimere una sensazione o un'emozione con pochi caratteri, ad es. :) significa felice, :( significa triste. Questo forum trasforma automaticamente queste serie di caratteri in immagini. La lista completa degli smileys &egrave; visibile nella pagina di invio messaggi. Cerca di non esagerare nell'uso degli smileys, possono facilmente rendere una messaggio illeggibile, e un moderatore potrebbe decidere di modificarlo o addirittura rimuoverlo.");
$faq[] = array("Posso inserire delle immagini?", "Puoi inserire delle immagini nei tuoi messaggi. Per agevolare l'inserimento delle immagini l'amministratore potrebbe aver abilitato la possibilit&agrave; di caricare immagini direttamente sul sito tramite l'<b>Album</b> o la funzionalit&agrave; di <b>Caricamento Immagini</b> mentre si invia un messaggio. Inserire immagini nell'album ha il vantaggio di poterle mostrare nelle gallerie e poter inserire sia miniature che immagini ridimensionate opportunamente all'interno dei messaggi tramite i BBCode. Inserire immagini direttamente quando si invia un messaggio tramite la funzionalit&agrave; di Caricamento Immagini ha il vantaggio di offrire un rapido strumento per quelle immagini che non si vuole inserire nelle gallerie. Nel caso in cui l'amministratore abbia disattivato entrambe queste funzioni sar&agrave; necessario fare un collegamento ad un'immagine contenuta in un server di pubblico accesso, ad es. http://www.indirizzo-del-sito.com/immagine.gif. Non puoi inserire immagini che hai sul tuo computer (a meno che non sia un server!) o immagini che si trovano dietro sistemi di autenticazione, come caselle di posta tipo yahoo o hotmail, siti protetti da password, ecc. Per inserire l'immagine, puoi usare sia il comando BBCode [img] che l'appropriato comando HTML (se consentito). Si rimanda alla guida dei BBCode per avere degli esempi da seguire su come inserire immagini.");
$faq[] = array("Cosa sono gli Annunci?", "Gli Annunci contengono spesso informazioni importanti e dovrebbero venir letti il prima possibile. Gli Annunci appaiono in cima ad ogni pagina del forum in cui sono stati scritti. L'amministratore pu&ograve; decidere se un utente pu&ograve; o non pu&ograve; scrivere annunci. Gli Annunci Globali sono degli speciali annunci che compaiono in cima ad ogni forum, quindi non solo in quello in cui sono stati scritti.");
$faq[] = array("Cosa sono i messaggi Importanti?", "I messaggi Importanti (noti anche come Sticky Topics) appaiono in cima alla prima pagina del forum in cui sono stati scritti (dopo eventuali Annunci). Come si intuisce dal nome stesso, contengono informazioni importanti e dovrebbero essere letti sempre. Come per gli annunci, l'amministratore pu&ograve; decidere se un utente pu&ograve; o non pu&ograve; scriverli.");
$faq[] = array("Cosa sono i topic Chiusi?", "I topic possono venire chiusi dai moderatori o dall'amministratore. Non &egrave; possibile rispondere ad un topic chiuso cos&igrave; come i sondaggi chiusi terminano automaticamente. Un topic pu&ograve; venire chiuso per varie ragioni, ad es. se contravviene alle Condizioni di adesione.");

$faq[] = array("--", "Gradi e Gruppi di Utenti");
$faq[] = array("Cosa sono gli Amministratori?", "Gli Amministratori sono gli utenti che hanno il pi&ugrave; alto grado di controllo sull'intero forum; possono controllare qualsiasi elemento, inclusi i permessi, il ban degli utenti, la creazione di moderatori e gruppi di utenti, ecc. Inoltre, possono moderare tutti i forum.");
$faq[] = array("Cosa sono i Moderatori?", "I Moderatori sono utenti (o gruppi di utenti) il cui compito &egrave; quello di tenere sotto controllo i forum giorno per giorno. Hanno il potere di modificare o cancellare qualsiasi messaggio e di chiudere, riaprire, spostare o rimuovere qualsiasi topic del forum da loro moderato. Generalmente il compito dei Moderatori &egrave; quello di evitare che gli utenti vadano <i>off-topic</i> (fuori tema) o che scrivano messaggi abusivi o offensivi.");
$faq[] = array("Cosa sono i Gruppi di Utenti?", "I Gruppi permettono agli amministratori di riunire gli utenti. Ogni utente pu&ograve; appartenere a pi&ugrave; gruppi (a differenza della maggior parte degli altri forum) e ad ogni gruppo possono venire assegnati diversi diritti d'accesso. Questo facilita all'amministratore le operazioni di creazione di moderatori per un forum, o di concessione di accessi per un forum privato, ecc.");
$faq[] = array("Come posso far parte di un Gruppo?", "Per unirti ad un gruppo, per prima cosa clicca sul link <u>Gruppi Utenti</u> che trovi in cima alla pagina (questo pu&ograve; variare a seconda del design del forum), e potrai accedere all'elenco dei Gruppi. Non tutti i gruppi sono ad <i>accesso aperto</i>. Alcuni sono chiusi e altri hanno l'elenco dei membri nascosto. Se il gruppo &egrave; Aperto, puoi chiedere l'ammissione cliccando sul pulsante apposito. Dovrai ottenere l'approvazione del moderatore del Gruppo, che potrebbe chiederti perch&eacute; vuoi unirti al gruppo. Se un moderatore di un gruppo non accetta la tua richiesta, sei pregato di non assillarlo; probabilmente ha le sue buone ragioni.");
$faq[] = array("Come divento Moderatore di un Gruppo?", "I Gruppi Utenti vengono creati dall'amministratore, il quale stabilisce anche il moderatore. Se desideri creare un Gruppo nuovo, contatta l'amministratore, via e-mail o con un messaggio privato.");


$faq[] = array("--", "Messaggi Privati");
$faq[] = array("Non riesco a mandare messaggi privati!", "Ci sono tre ragioni per cui questo pu&ograve; accadere: non sei registrato o non hai fatto il login, l'amministratore ha disabilitato i messaggi privati per tutto il forum, oppure li ha disabilitati solo a te. Se il tuo caso &egrave; l'ultimo, prova a chiedere il perch&eacute; all'amministratore.");
$faq[] = array("Continuano ad arrivarmi messaggi privati indesiderati!", "Se continui a ricevere messaggi indesiderati da qualcuno, prova ad informare l'amministratore, il quale pu&ograve; revocare l'uso dei messaggi privati ad un determinato utente.");
$faq[] = array("Ho ricevuto un'e-mail indesiderata o dello spamming da qualcuno in questo forum!", "Ci dispiace saperlo. Il sistema di invio di posta di questo forum include un sistema di protezione per risalire a chi manda queste e-mail. Dovresti mandare una copia dell'e-mail in questione all'amministratore, includendo anche l'intestazione, in modo che possa intervenire.");


$faq[] = array("--", "Avatar Generator");
$faq[] = array("Che cos'&egrave;?", "L' <strong>Avatar Generator</strong> &egrave; uno strumento per creare degli avatar.");
$faq[] = array("Dove si trova?", "Devi effettuare il Login per usare avatar generator. Il link si trova nel tuo profilo.");
$faq[] = array("Come faccio a salvare gli avatar che ho creato?", "Ci dovrebbe essere un link sotto l'avatar generato, il link dice <strong>Clicca QUI per aggiungerlo al tuo profilo</strong> una volta che lo clicchi ti dovrebbe apparire un messaggio che ti informa a riguardo dei cambiamenti.");


$faq[] = array("--","Album");
$faq[] = array("Come si accede all'Album?", "Basta utilizzare il link Album nel menu di navigazione. Verrai reindirizzato nella pagina principale dell'Album, dove potrai accedere alle categorie pubbliche e alle categorie personali (eventualmente anche a quelle private se ne hai il permesso).");
$faq[] = array("Come carico una immagine nell'Album?", "Per caricare un'immagine nell'Album &egrave; sufficiente accedere all'Album e poi cliccare sul pulsante \"Carica Immagine\" che si trova in cima ed a fondo pagina. Una volta cliccato, baster&agrave; compilare i campi richiesti e seguire le istruzioni.");
$faq[] = array("Quali sono le dimensioni massime (in termini di altezza, larghezza, dimensione del file) consentite per il caricamento delle immagini?", "I limiti vengono visualizzati durante il caricamento delle immagini. L'amministratore pu&ograve; aver impostato diversi limiti su dimensioni e tipo di immagini.");
$faq[] = array("Non riesco a caricare le immagini nell'Album!", "Prova di nuovo a caricarle dalla sezione \"Carica Immagine\", prestando particolare attenzione alle indicazioni presenti in quella pagina riguardo dimensioni, tipo di file e campi obbligatori. Se ancora non riesci, contatta l'amministratore del sito.");
$faq[] = array("Ho fatto un errore nella compilazione della descrizione/titolo dell'immagine, cosa posso fare?", "Se possiedi i permessi necessari puoi modificare le informazioni relative all'immagine direttamente dalla pagina di visualizzazione.");
$faq[] = array("Come elimino un'immagine caricata?", "Nella pagina di visualizzazione, se l'amministratore ti ha dato i permessi necessari, potrai utilizzare un apposito link per eliminare le immagini.");
$faq[] = array("Vorrei poter esprimere il mio giudizio su alcune immagini. Come posso fare?", "Se l'amministratore lo ha consentito, dalla pagina di visualizzazione delle immagini sar&agrave; possibile inserire valutazioni e commenti.");


$faq[] = array("--","Allegati");
$faq[] = array("Come si aggiunge un allegato?", "Potete inserire un nuovo allegato  quando inserite un nuovo messaggio. Dovreste vedere <i>Aggiungi un allegato</i> alla fine del box del messaggio. Quando cliccate<i>Sfoglia...</i> si aprir&agrave; la finestra di dialogo sfoglia del vostro computer. Cercate il file che volete allegare, selezionatelo e cliccate OK,. Se desiderate commentare il file compilare il campo <i>Descrizione file</i> ed il commento verr&agrave; linkato al file . Se non compilate il campo commento, verr&agrave; visualizzato il nome del file. Se il forum consente gli allegati multipli, potrete proseguire sino a raggiungere il massimo consentito.<br /><br />L'amministratore del forum ha settato un limite massimo per la dimensione massima del file, ha definito le estensioni consentite ed altre funzioni.<br /> E' vostra esclusiva responsabilit&agrave; per il contenuto del file inviato.<br /><br /> Qualora il vostro file non sia coerente con la policy del forum, pu&ograve; essere cancellato senza preavviso.");
$faq[] = array("Posso allegare un file dopo aver spedito il messaggio?", "Per aggiungere un allegato dopo aver spedito il messaggio dovete modificare il messaggio e seguire la procedura di inserimento messaggi sopra descritta. Il nuovo allegato verr&agrave; allegato quando cliccherete su <i>Invia</i> come per la modifica di un messaggio esistente.");
$faq[] = array("Come posso cancellare un allegato?", " Per cancellare un allegato e necessario modificare il messaggio e selezionare la funzione <i>Cancella Allegato</i> successivo all'allegato che volete cancellare nel box<i>Allegati spediti</i>. L'allegato verr&agrave; eliminato quando cliccherete il tasto <i>Invia</i> .");
$faq[] = array("Come posso aggiornare il commento del file?", "Per aggiornare il commento di un file, dovete modificare il vostro messaggio , modificare il testo indicato in <i>Descrizione file</i> e cliccare su  <i>Aggiorna descrizione file</i> successivo al commento del file che volete aggiornare nel box <i>Posted Attachments</i> . Il commento del file verr&agrave; aggiornato quando invierete il messaggio");
$faq[] = array("Perch&eacute; non &egrave; possibile vedere gli allegati inseriti?", " Probabilmente il file o l'estensione non sono pi&ugrave; permesse o un membro autorizzato del forum [moderatore, amministratore] hanno cancellato il file perch&eacute; in conflitto con le regole del forum.");
$faq[] = array("Perch&eacute; non riesco ad inserire gli allegati?", " In alcuni forum l'inserimento allegati &egrave; permesso solo a certi utenti o a certi gruppi. In questo caso &egrave; necessario un'autorizzazione particolare, che solo il forum master o l'amministratore del forum stesso possono attivare.");
$faq[] = array("Credo di avere i permessi ma non riesco ad aggiungere l'allegato?", "L'amministratore del forum ha inserito dei limiti massimi per dimensione e numero di files ed estensioni per gli allegati . Un moderatore o un amministratore possono modificare questi valori o proibire gli allegati in un forum specifico. Quando l'allegato collide con i permessi un messaggio di errore viene mostrato all'utente,in caso contrario contattate lo staff.");
$faq[] = array("Chi pu&ograve; cancellare l'allegato?", "In qualche forum l'opzione di cancellazione degli allegati, potrebbe essere limitata a certi utenti o gruppi. Per cancellare un allegato potrebbe essere quindi necessaria una speciale autorizzazione che solo i moderatori o gli amministratori del forum possono concedere..");
$faq[] = array("Chi pu&ograve; vedere/scaricare il file?", "In alcuni forum il download o la visione di allegati pu&ograve; essere limitata a certi utenti/gruppi. Potrebbe essere quindi necessaria una speciale autorizzazione che solo i moderatori o gli amministratori del forum possono concedere.. ");
$faq[] = array("Chi devo contattare se verifico che un messaggio contenga un file proibito?", "Dovete contattare l'amministrazione del forum o il moderatore, indicando il messaggio ed il motivo per cui il file non &egrave; permesso. Il gruppo di sviluppo phpBB non ha alcun controllo sui forum installati e non pu&ograve; in qualsiasi modo intervenire.");


$faq[] = array("--","Downloads ADV");
$faq[] = array("Dove posso trovare i download?", "I link alla sezione download sono presenti sia nel portale che nella barra di navigazione Il link diretto: [<a href=\"downloads.php\">Download</a>]");
$faq[] = array("Cosa rappresenta l'icona blu?", "<img border=\"0\" src=\"" . $images['Dl_blue'] . "\" alt=\"\" title=\"\" />: Nessun download possibile. Il limite di traffico per quel particolare download, impostato per il mese corrente, &egrave; stato superato.");
$faq[] = array("Cosa rappresenta l'icona rossa?", "<img border=\"0\" src=\"" . $images['Dl_red'] . "\" alt=\"\" title=\"\" />: Download non possibile. Pu&ograve; essere causato da:<br />- Download bloccato dall\"amministratore.<br />- L\"utente non &egrave; connesso ed il file &egrave; autorizzato solo per gli utenti registrati.<br />- L\"utente ha superato il limite di traffico a lui assegnato.<br />- L\"amministratore ha impostato un numero minimo di messaggi e l\"utente non ha raggiunto questo limite.<br />- Il limite di traffico assegnato al file &egrave; stato superato.");
$faq[] = array("Cosa rappresenta l'icona grigia?", "<img border=\"0\" src=\"" . $images['Dl_grey'] . "\" alt=\"\" title=\"\" />: File esterno. Il file da scaricare &egrave; collocato esternamente al server che ospita il forum. Questo tipo di download verr&agrave; considerato come <img border=\"0\" src=\"" . $images['Dl_green'] . "\" alt=\"\" title=\"\" />. Lo scaricamento di questo file non influir&agrave; su nessun tipo di traffico.");
$faq[] = array("Cosa rappresenta l'icona bianca?", "<img border=\"0\" src=\"" . $images['Dl_white'] . "\" alt=\"\" title=\"\" />: Come per l'icona <img border=\"0\" src=\"" . $images['Dl_green'] . "\" alt=\"\" title=\"\" /> il traffico non verr&agrave; scalato dal credito dell\"utente. Solo gli utenti registrati (e connessi) potranno scaricare questo file. Il valore del traffico utilizzato verr&grave; scalato.");
$faq[] = array("Cosa rappresenta l'icona verde?", "<img border=\"0\" src=\"" . $images['Dl_green'] . "\" alt=\"\" title=\"\" />: Download Libero. Non saranno applicate restrizioni al download di questo file. Questo file pu&ograve; essere scaricato anche da utenti non registrati. Non &egrave; necessario che tu ti connetta. Lo scaricamento di questo file non intaccher&agrave; il tuo limite di traffico mentre verr&agrave; conteggiato il traffico globale.");
$faq[] = array("Cosa rappresenta l'icona gialla?", "<img border=\"0\" src=\"" . $images['Dl_yellow'] . "\" alt=\"\" title=\"\" />: Download con restrizioni. Soltanto gli utenti registrati, e connessi, potranno scaricare questo file. La dimensione del file verr&agrave; sottratta dal tuo traffico ed inoltre lo stesso valore verr&agrave; sottratto dal traffico globale.");
$faq[] = array("Perch&egrave; non posso scaricare nessun file?", "Ci possono essere diversi motivi. Controlla su <img border=\"0\" src=\"" . $images['Dl_blue'] . "\" alt=\"\" title=\"\" /> e <img border=\"0\" src=\"" . $images['Dl_red'] . "\" alt=\"\" title=\"\" />.");
$faq[] = array("Quando verr&agrave; ripristinato il traffico relativo al mio account?", "Dopo il primo login l\"utente avr&agrave; assegnato un valore orario (timestamp). Ogni primo del mese in cui l\"utente effettuer&agrave; una connessione il valore del traffico da utilizzare per i download verr&agrave; ripristinato. Per ulteriori informazioni contatta l\"amministratore.");
$faq[] = array("Devo scaricare dei file ma non ho pi&ugrave; traffico", "In questo caso prova a chiedere all\"admin. Soltanto lui pu&ograve; decidere di assegnarti altro traffico prima che trascorra un mese e, di conseguenza, il traffico concesso per i download venga ripristinato.");
$faq[] = array("Come posso valutare i download?", "Ogni download ha una sezione per la valutazione <img border=\"0\" src=\"" . $images['Dl_rating_0'] . "\" alt=\"\" title=\"\" />.<br />Cliccando su \"Valuta\" un utente registrare potr&agrave; valutare assegnando al file da 1 punto (pessimo) a 10 punti (ottimo). Potrai valutare un download una sola volta.");


$faq[] = array("--","Digests");
$faq[] = array("Cosa sono i Digests?", "I Digests sono delle email che ti vengono inviate periodicamente con una sintesi dei messaggi inviati sul sito. I Digests sono disponibili con periodicit&agrave; giornaliera o settimanale.");
$faq[] = array("Perch&eacute; dovrei utilizzare i Digests?", "Perch&eacute; ti rendono la vita pi&ugrave; semplice!. Con i Digests non sei costretto a visitare il sito per consultare le discussioni, perch&eacute; ti vengono recapitate per email e puoi entrare nel sito solo quando trovi qualcosa di interessante. In ogni momento i Digests possono essere disattivati.");
$faq[] = array("Con quale frequenza vengono inviati i Digests?", "I Digests possono essere inviati giornalmente o settimanalmente. I Digests settimanali, vengono inviati di domenica.");
$faq[] = array("Quando vengono inviati i Digests?", "L'orario di invio pu&ograve; essere scelto nella pagina di configurazione dei Digests.");
$faq[] = array("Che intervallo temporale &egrave; coperto dai Digests?", "24 ore o 7 giorni, a seconda dell'opzione scelta. I messaggi pi&ugrave; vecchi di questo intervallo non verranno inviati. In aggiunga &egrave; possibile scegliere se debbano essere inviati soltanto i messaggi non letti dall'ultima visita effettuata sul sito. E' possibile anche scegliere se ricevere o meno i propri messaggi.");
$faq[] = array("E' possibile mettere dei filtri sui Digests?", "Si, dalla pagina di configurazione dei Digests &egrave; possibile scegliere soltanto le categorie dalle quali si vogliono ricevere i Digests.");
$faq[] = array("Che formati di email sono disponibili?", "E' possibile scegliere tra HTML o testo. E' consigliabile scegliere il formato HTML per avere un'impaginazione migliore e pi&ugrave; curata.");
$faq[] = array("I messaggi nei Digests vengono inclusi integralmente?", "L'opzione predefinita prevede che vengano ricevuti i primi 150 caratteri del messaggio, ma &egrave; possibile scegliere anche un numero superiore di caratteri oppure si pu&ograve; richiedere solo il link dei messaggi. Si consiglia di non aumentare troppo il numero di caratteri, per evitare che su siti molto trafficati i messaggi email crescano a dismisura.");
$faq[] = array("Dove si possono configurare i Digests?", "Dal link presente nella barra di navigazione del sito, o cliccando questo link: <a href=\"./digests.php\">DIGESTS</a>.");
$faq[] = array("Posso annullare la sottoscrizione dei Digests?", "Certamente, basta andare nella pagina di configurazione dei Digests e disabilitarli.");
$faq[] = array("I Digests contengono pubblicit&agrave;?", "No, i Digests non contengono annunci pubblicitari... soltanto i messaggi estratti dalle sezioni scelte.");
$faq[] = array("La mia Privacy &egrave; tutelata?", "Si, i Digests vengono inviati esclusivamente a te, ed il tuo indirizzo email non viene fornito a terzi.");


$faq[] = array("--","Memorizzazione Messaggi Non Letti Nel DB (UPI2DB)");
$faq[] = array("Qual'&egrave; la differenza tra il sistema predefinito basato su cookie ed il sistema UPI2DB?", "Il sistema basato su cookie &egrave; quello predefinito di phpBB2. Quando leggi un messaggio, le informazioni vengono memorizzate in un cookie nel PC che stai usando. Il problema principale di questo sistema &egrave; che vengono perse tutte le informazioni relative ai contrassegni di lettura se il browser viene chiuso. Il sistema UPI2DB invece memorizza le impostazioni nel database.");
$faq[] = array("Quali sono i vantaggi e gli svantaggi del sistema basato su cookie?", "<strong>Vantaggi</strong><br />In siti molto grandi, il sistema basato su cookie &egrave; molto pi&ugrave; veloce nel caricamento delle pagine rispetto al sistema UPI2DB, perch&eacute; debbono essere caricate dal database anche le informazioni sui contrassegni di lettura.<br />Un vantaggio ulteriore &egrave; legato al fatto che le informazioni restano memorizzate per diversi mesi, o almeno fino a quando non vengono eliminati i cookie dal PC. Questo &egrave; utile per gli utenti che visitano il sito raramente (ad esempio ogni 2 mesi).<br /><strong>Svantaggi</strong><br />Lo svantaggio pi&ugrave; evidente del sistema basato su cookie &egrave; che tutti i messaggi vengono automaticamente contrassegnati come letti nonappena viene chiuso il browser.<br />Un ulteriore svantaggio &egrave; che i messaggi modificati non vengono contrassegnati come da leggere.");
$faq[] = array("Quali sono i vantaggi e gli svantaggi del sistema UPI2DB?", "<strong>Vantaggi</strong><br />I messaggi non letti, restano come non letti anche quando il browser viene chiuso o quando viene effettuato il logout.<br />I messaggi possono anche restare contrassegnati come non letti per " . $unread_days . " con il sistema UPI2DB.<br />Inoltre, i forum che non sono ritenuti interessanti possono essere contrassegnati come permanentemente letti.<br />I messaggi modificati possono essere contrassegnati di nuovo come non letti e colorati diversamente.<br />La funzione di ricerca &egrave; potenziata per poter cercare soltanto tra i messaggi non letti o modificati.<br />Se l'amministratore abilita l'opzione sui messaggi modificati, gli argomenti con delle modifiche vengono spostati in cima alla lista, permettendo cos&igrave; di essere visionati di nuovo.<br /><strong>Svantaggi</strong><br />Su siti molto grandi, con tanti messaggi ed utenti, il caricamento delle pagine pu&ograve; risultare rallentato.<br />l'informazione sui contrassegni resta memorizzata solo per un periodo limitato di tempo (deciso dall'amministratore), superato il quale, tutti i messaggi vengono contrassegnati come letti (per liberare spazio nel DB).");
$faq[] = array("Nel mio profilo non posso scegliere tra sistema basato su cookie e sistema UPI2DB", "Se non trovi questa opzione nel tuo profilo &egrave; perch&eacute; l'amministratore del sito ha impedito agli utenti di personalizzare questa opzione.");
$faq[] = array("Quali condizioni l'amministratore pu&ograve; impostare?", "L'amministratore pu&ograve; decidere un numero minimo di messaggi inviati o di giorni di iscrizione per consentire agli utenti di utilizzare il sistema UPI2DB.");
$faq[] = array("Non riesco a contrassegnare annunci ed argomenti importanti come gi&agrave; letti o permanentemente letti!", "Annunci ed argomenti importanti debbono essere letti in ogni caso!");
$faq[] = array("Debbo selezionare ogni " . $unread_days . " giorni un argomento come permanentemente letto!", "Questa impostazione non pu&ograve; essere modificata, perch&eacute; &egrave; stato scelto un compromesso tra velocit&agrave; ed efficienza del sistema.");
$faq[] = array("Come posso contrassegnare un forum come permanentemente letto?", "E\' sufficiente cliccare sull'immagine associata al forum.");
$faq[] = array("Come posso contrassegnare un argomento come permanentemente letto?", "E\' sufficiente cliccare sull'immagine associata all'argomento. Alternativamente si pu&ograve; cliccare sul link presente a fondo pagina <b>argomento contrassegnato come permanentemente letto</b>");
$faq[] = array("Ho contrassegnato un forum come permanentemente letto, ma nuovi messaggi compaiono!", "Quando vengono inviati argomenti importanti o annunci, l'impostazione di permanentemente letto viene rimossa, per evitare che alcune informazioni importanti, non vengano lette!");
$faq[] = array("Come posso contrassegnare un messaggio in modo da poterlo ritrovare facilmente?", "Ogni messaggio ha un pulsante che pu&ograve; essere utilizzato per cotrassegnare il messaggio stesso. I messaggi pi&ugrave; vecchi di " . $unread_days . " giorni o messaggi scritti prima che tu ti registrassi, non possono essere contrassegnati.");
$faq[] = array("Come posso contrassegnare un messaggio gi&agrave; letto come un messaggio non letto?", "In ogni messaggio c'&egrave; un link che consente di impostare di nuovo il contrassegno di messaggio non letto o modificato al messaggio stesso ed ai successivi.");
$faq[] = array("Perch&eacute; non riesco a contrassegnare alcuni messaggi?", "Messaggi contrassegnati come permanentemente letti o messaggi inviati prima della tua registrazione, non possono essere contrassegnati di nuovo. Neanche i messaggi pi&ugrave; vecchi di " . $unread_days . " giorni, possono essere contrassegnati.");
$faq[] = array("I messaggi contrassegnati lo sono per sempre?", "No, tutti i contrassegni vengono eliminati automaticamente dopo " . $del_mark . " giorni.");
$faq[] = array("Cosa significa MAR?", "E\' l'abbreviazione di <b>Contrassegna tutti come letti</b>");


$faq[] = array("--", "Informazioni su phpBB 2");
$faq[] = array("Chi ha scritto questo programma?", "Questo software (nella sua forma originale) &egrave; prodotto e rilasciato da <a href=\"http://www.phpbb.com/\" target=\"_blank\">phpBB Group</a>, che ne possiede anche il copyright. E' reso disponibile sotto la GNU General Public Licence e pu&ograve; essere liberamente distribuito; clicca il link per maggiori informazioni.");
$faq[] = array("Perch&eacute; la caratteristica X non &egrave; disponibile?", "Questo software &egrave; stato scritto da phpBB Group. Se credi che ci sia bisogno di aggiungere una funzionalit&agrave;, visita il sito phpbb.com e guarda cosa il phpBB Group ha da dire a riguardo. Sei pregato di non fare richieste per nuove caratteristiche nel forum di phpbb.com, il Gruppo si appoggia a Sourceforge per la gestione di nuove funzionalit&agrave;. Leggi il forum e cerca di capire, se vengono spiegate, quali sono le nostre posizioni a proposito di quella caratteristica e segui la procedura data.");
$faq[] = array("Chi devo contattare in caso di problemi o abusi legali realativi a questo forum?", "Devi contattare l'amministratore di questo forum. Se non riesci a trovarlo, prova a contattare uno dei moderatori e chiedi a chi puoi rivolgerti. Se ancora non ottieni risposta, puoi contattare il proprietario del dominio (fai una ricerca con whois) oppure, se il forum &egrave; ospitato da un servizio gratuito (ad es. yahoo, free.fr, f2s.com, ecc.), l'amministratore di tale servizio. Nota che il phpBB Group non ha assolutamente alcun controllo e non pu&ograve; essere ritenuto responsabile di come, dove e da chi questo forum viene utilizzato. E' assolutamente inutile contattare il phpBB Group in relazione a qualsiasi questione legale non direttamente collegata al sito phpbb.com o al software phpBB stesso. Le e-mail inviate al phpBB Group riguardanti l'uso da parte di terzi di questo software non riceveranno nessuna risposta.");


$faq[] = array("--", "Informazioni su Icy Phoenix");
$faq[] = array("Cos'&egrave; Icy Phoenix?", "Icy Phoenix &egrave; un CMS (Content Management System) che consente in maniera molto rapida la creazione di siti web dinamici con diverse funzionalit&agrave; gi&agrave; incluse come: forum, portale, pagine e blocchi personalizzabili, downloads, galleria immagini, e tante altre.");
$faq[] = array("Chi ha scritto questo programma?", "Questo software &egrave; prodotto e rilasciato da <a href=\"http://www.icyphoenix.com/\" target=\"_blank\">Icy Phoenix</a>. La base di codice di Icy Phoenix &egrave; il phpBB che viene rilasciato sotto la GNU General Public Licence, per cui anche Icy Phoenix deve essere rilasciato con lo stesso tipo di licenza, il che vuol dire che &egrave; possibile distribuire e modificare questo software gratuitamente. La maggior parte del codice (phpBB a parte) ed integrazioni con il phpBB sono stati scritti da Mighty Gorgon e dallo <a href=\"http://www.icyphoenix.com/\" target=\"_blank\">Staff di Icy Phoenix</a>. Per una lista (non esaustiva) dei contributori al progetto si pu&ograve; consultare a questo indirizzo: <a href=\"http://www.icyphoenix.com/credits.php\" target=\"_blank\">Icy Phoenix - Riconoscimenti</a>.");
$faq[] = array("Chi devo contattare in caso di problemi o abusi legali realativi a questo sito?", "Devi contattare l'amministratore di questo sito. Se non riesci a trovarlo, prova a contattare uno dei moderatori e chiedi a chi puoi rivolgerti. Se ancora non ottieni risposta, puoi contattare il proprietario del dominio (fai una ricerca con whois) oppure, se il sito &egrave; ospitato da un servizio gratuito (ad es. yahoo, free.fr, f2s.com, ecc.), l'amministratore di tale servizio. Nota che Icy Phoenix non ha assolutamente alcun controllo e non pu&ograve; essere ritenuto responsabile di come, dove e da chi questo forum viene utilizzato. E' assolutamente inutile contattare Icy Phoenix in relazione a qualsiasi questione legale non direttamente collegata al sito icyphoenix.com o al software Icy Phoenix stesso. Le e-mail inviate ad Icy Phoenix riguardanti l'uso da parte di terzi di questo software non riceveranno nessuna risposta.");



?>