<?php
/**
*
* @package Icy Phoenix
* @version $Id$
* @copyright (c) 2008 Icy Phoenix
* @license http://opensource.org/licenses/gpl-license.php GNU Public License
*
*/

if (!defined('IN_ICYPHOENIX'))
{
	exit;
}

if (empty($lang) || !is_array($lang))
{
	$lang = array();
}

$lang['RandomQuote'] = 'La frase del momento';

//$randomquote[rand(0,count($randomquote)-1)]);

$randomquote = array(
// Aforismi
	'Signore, concedimi la serenit&agrave, per accettare le cose che non posso cambiare, il coraggio per cambiare quelle che posso, e la saggezza per vederne la differenza. (Reinold Nierbuhr)',
	'Non insegnare le discipline con la costrizione, ma come giocando, potrai cos&igrave, scoprire le tendenze individuali di ciascuno. (Platone, "De Repubblica")',
	'Non esistono il bene o il male, ma solo circostanze. (Honor&eacute, de Balzac)',
	'Se aggiungi poco al poco, ma lo farai di frequente, presto il poco diventer&agrave, molto. (Esiodo)',
	'Per prima cosa viene il concetto, poi l\'organizzazione di quel concetto in idee e progetti, quindi la trasformazione di quei piani in realt&agrave,. L\'inizio, come potete osservare, sta nella vostra immaginazione. (Napoleon Hill)',
	'Nessuno pu&ograve, darti autorit&agrave,. Ma se agisci come se l\'avessi, gli altri crederanno che tu l\'abbia. (Karin Ireland)',
	'Qualunque decisione tu abbia preso per il tuo futuro, sei autorizzato, e direi incoraggiato, a sottoporla ad un continuo esame, pronto a cambiarla, se non risponde pi&ugrave, ai tuoi desideri. (Rita Levi Montalcini, "Il tuo futuro")',
	'FAKE IT \'TIL YOU MAKE IT: Agisci nel modo in cui vorresti essere e presto sarai nel modo in cui agisci. (George W. Crane)',
	'Trattenere l\'ira &egrave, come afferrare un carbone ardente con l\'intenzione di tirarlo a qualcuno, sei tu quello che si sta scottando. (Buddha)',
	'Se fai ci&ograve, che hai sempre fatto, riceverai ci&ograve, che hai sempre ricevuto. (Anonimo)',
	'Molto &egrave, dato a pochi e poco &egrave, dato a molti. Nulla &egrave, distribuito equamente tranne il dolore. (Karl Marx)',
	'L\'intelligenza &egrave, forse l\'unica ricchezza ad essere stata distribuita equamente. Infatti, nessuno si lamenta di averne meno degli altri. (Proverbio Spagnolo)',
	'Quando il mio cavallo sta correndo bene, non mi fermo per dargli lo zuccherino. (William Faulkner)',
	'Quando un posto vi sta stretto e tutto va contro di voi, fino al punto che vi sembri sia cos&igrave, dura da non resistere nemmeno un minuto di pi&ugrave,, non mollate mai, perch&eacute, quello &egrave, giusto il momento e il luogo in cui la marea cambia direzione. (Harriet Beecher Stowe)',
	'Questo momento. Ogni secondo &egrave, di valore infinito. (Johann Wolfgang von Goethe, Poeta e Filosofo)',
	'AZIONE - La visione senza azione &egrave, puramente sognare. L\'azione senza visione &egrave, solo trascorrere il tempo. La visione con l\'azione pu&ograve, cambiare il mondo. (Joel Barker)',
	'Religione: La mia religione &egrave, semplice, la mia religione &egrave, la gentilezza. (Dalai Lama)',
	'Se ti accetto come sei, ti render&ograve, peggiore, comunque, se ti tratto come se tu fossi ci&ograve, che sei capace di essere, ti aiuter&ograve, a diventarlo. (Johann Wolfgang von Goethe, Poeta e Filosofo)',
	'Se poni una questione di sostanza, senza dare troppa importanza alla forma, ti fottono nella sostanza e nella forma. (Calogero Falcone - Magistrato)',
	'Alcuni vivono solo prima della loro morte, altri anche dopo, la maggior parte invece, n&eacute, prima n&egrave, dopo: si lasciano spingere tranquillamente nel mondo e fuori da esso. (Johann Gottfried Seume)',
	'CAMBIAMENTO - Dovunque noi siamo, &egrave, una tappa nel nostro viaggio verso qualche altro posto, e qualsiasi cosa facciamo, &egrave, solo in preparazione al fare qualcos\'altro che sar&agrave, diverso. (Robert Louis Stevenson)',
	'"Quando decisi di lasciare Claudia Schiffer non le dissi niente, non una parola, non una lettera. Io sono fatto cos&igrave,, anche quando ci fidanzammo non glielo feci sapere!" (Anonimo)',
	'Diventa un possibilista. Non importa quanto buie sembrino essere le cose o quanto lo siano davvero, eleva la tua visione fino a vedere le possibilit&agrave, - guardale sempre, dato che sono sempre presenti. (Norman Vincent Peale)',
	'"Cercavo disperatamente la vita. Poi mi accorsi che in questa affannosa ricerca si celava lei medesima." (Lisandro)',
	'Il tiro peggiore che la sorte possa giocare ad un uomo intelligente &egrave, metterlo alle dipendenze di uno sciocco. (Casanova Giacomo)',
	'I cretini sono sempre pi&ugrave, ingegnosi delle precauzioni che si prendono per impedire loro di nuocere. (8° corollario alla Legge di Murphy)',
	'Per quanto possa ricordare, non vi &egrave, una sola parola nei Vangeli in lode dell\'intelligenza. (Bertrand Russell)',
	'Non esiste nessuna adeguata difesa, eccetto la stupidit&agrave,, contro l\'impatto di una nuova idea. (P. W. Bridgman)',
	'Due cose sono infinite: l\'universo e la stupidit&agrave, umana, ma riguardo l\'universo ho ancora dei dubbi. (A. Einstein)',
	'L\'intelligenza &egrave, una delle poche cose che finora non sono state tassate. Non ne varr&agrave, la pena. (Heinz Ruhman)',
	'Che meraviglia la vita! Vivi pensando al dopo illudendoti che sia migliore del prima. (Lisandro)',
	'Non c\'&egrave, niente di pi&ugrave, pericoloso di un cretino che ha ragione per caso. (Anonimo)',
	'"Noi non abbiamo ereditato il mondo dai nostri padri, ma lo abbiamo in prestito dai nostri figli e a loro dobbiamo restituirlo migliore di come lo abbiamo trovato." (Anonimo)',
	'Una vita senza sogni &egrave, banale sopravvivere, tacita resa agli eventi, lento volgere all\'imbrunire. (Lisandro)',
	'Ci sono scemenze ben presentate come ci sono scemi ben vestiti. (Nicolas de Chamfort)',
	'Intelligenza - Gli uomini con talento trovano delle soluzioni, i geni scoprono i problemi. (Hans Krailsheimer)',
	'"L\'esperienza &egrave, il professore pi&ugrave, difficile : prima ti fa l\'esame e poi ti spiega la lezione." (Anonimo)',
	'"Ciascun giorno perdiamo qualche cosa, cio&egrave, perisce, o scema qualche illusione, che sono l\'unico nostro avere. L\'esperienza e la verit&agrave, ci spogliano alla giornata di qualche parte dei nostri possedimenti. Non si vive se non perdendo." (G. Leopardi - Zibaldone (636))',
	'Si riconosce molto presto l\'intelligenza di un interlocutore: i suoi punti di vista rassomigliano ai nostri. (Robert Lembke)',
	'Non credo nell\'intuizione. Ma quando hai quei flash improvvisi di percezione, &egrave, solo il tuo cervello che lavora pi&ugrave, rapidamente del solito. Ma tu eri preparato a conoscerlo da lungo tempo, e quando arriva, senti che lo avevi sempre saputo. (Katherine Anne Porter)',
	'Leggere, dopo una certa et&agrave,, allontana troppo la mente dalla sua ricerca creativa. Qualunque individuo che legge troppo ed usa il suo proprio cervello troppo poco, cade in oziosi abitudini di pensiero. (Albert Einstein)',
	'"Meglio tacere e far finta di essere stupidi, piuttosto che parlare e togliere ogni dubbio!" (Confucio)',
	'Se negli ultimi anni non avete abbandonato un\'opinione importante o non ne avete acquisita una nuova, controllate il vostro polso. Potreste essere morti. (Gelett Burgess)',
	'Quando tendi alle stelle puoi anche non raggiungerle, ma certamente non resti con un pugno di fango. (Leo Burnett)',
	'"Del paradiso preferisco il clima, dell\'inferno la compagnia." (Anonimo)',
	'Per capire il cuore e la mente di una persona, non guardare a quello che ha gi&agrave, raggiunto, ma a ci&ograve, a cui aspira. (Kahlil Gibran)',
	'Noi dobbiamo, in qualsiasi momento, essere preparati a sacrificare ci&ograve, che siamo per ci&ograve, che siamo capaci di diventare. (Charles Dubois)',
	'Abbi cura del tuo corpo con risoluta fedelt&agrave,. L\'anima deve vedere attraverso questi soli occhi, e se sono appannati, l\'intero mondo &egrave, annebbiato. (Johann Wolfgang von Goethe, Poeta e Filosofo)',
	'Uno sciocco trova sempre uno pi&ugrave, sciocco che l\'ammira. (Boileau)',
	'Se metti gli scemi in una comunit&agrave,, non ne guarisce uno. La follia pu&ograve, essere passeggera, la stupidit&agrave, &eacute, per sempre. (Puccio de Lollis)',
	'"La vita &egrave, quello che succede mentre tu stai facendo altri progetti." (Anonimo)',
	'La vera gloria &egrave, venire messo in ginocchio e riuscire a riprendersi. Questa &egrave, vera gloria. (Vince Lombardi)',
	'Una persona di successo &egrave, quella che riesce a stabilire basi solide con i mattoni che le vengono tirati addosso. (David Brinkley)',
	'Scrittore Inglese. Volevo cambiare il mondo. Ma ho scoperto che la sola cosa che si pu&ograve, essere sicuri di cambiare &egrave, se stessi. (Aldous Leopard Huxley)',
	'La vita non &egrave, sempre come uno vorrebbe che fosse, ma viverla al meglio, cos&igrave, com\'&egrave,, &egrave, l\'unico modo di essere felici. (Jennie Jerome Churchill)',
	'"La mancanza di qualcosa che si desidera &egrave, una parte fondamentale di felicit&agrave," (Anonimo)',
	'Le persone tenaci iniziano il loro successo dove gli altri terminano col loro fallimento. (Edward Eggleston)',
	'Noi siamo ci&ograve, che pensiamo. Tutto quello che siamo nasce dai nostri pensieri. Con i nostri pensieri, creiamo il nostro mondo. (Buddha)',
	'Guardatevi dal dissipare la vostra energia, cercate invece di concentrarla. Il genio crede di poter fare qualunque cosa fatta dagli altri, ma &egrave, certo che si pentir&agrave, di ogni malaccorta spesa. (Johann Wolfgang Goethe)',
	'Tutti i grandi propositi e i grandi pensieri hanno un\'origine ridicola. Grandi realizzazioni sono germinate in un angolo di strada o tra le porte girevoli di un ristorante. (Albert Camus, Scrittore, Premio Nobel, Filosofo)',
	'Vedete, nella vita un sacco di gente sa cosa fare, ma pochi in realt&agrave, fanno ci&ograve, che sanno. La conoscenza non &egrave, sufficiente! Dovete agire. (Anthony Robbins)',
	'C\'&egrave, gente che vive in un mondo fatto di sogni, e c\'&egrave, gente che affronta la realt&agrave,, e poi ci sono quelli che tramutano una cosa nell\'altra. (Douglas Everett)',
	'"Quelli che arrivano al vertice sono straordinari nel chiedere aiuto." Il CEO della Coca-Cola (quando gli venne una volta chiesta la differenza tra quelli che arrivano al vertice partendo dal basso, e quelli che non ci riescono) (Ceo Coca Cola)',
	'"Felicit&agrave, non &egrave, avere tutto ci&ograve, che si desidera, ma desiderare tutto ci&ograve, che si ha." (Anonimo)',
	'Non &egrave, necessario sperare per intraprendere, n&eacute, ottenere successi per perseverare. (Guglielmo I d\'Orange-Nassau, detto il Taciturno)',
	'Se credi di potercela fare, probabilmente ce la farai. Se credi di non riuscirci, stai sicuro che non ci riuscirai. Le convinzioni sono la chiavetta d\'accensione che ti fa staccare dalla rampa di lancio. (Denis Waitley)',
	'Una persona con una convinzione equivale ad una forza di novantanove altre con dei semplici interessi. (John Stuard Mill)',
	'Vi &egrave, una cosa buffa nella vita: se rifiuti di accettare altro che non sia il meglio, molto spesso lo ottieni! (Somerset Maugham)',
	'Per mezzo di tre metodi noi apprendiamo la saggezza: Primo, con la riflessione, che &egrave, il pi&ugrave, nobile, secondo, con l\'imitazione, che &egrave, il pi&ugrave, facile, e terzo, con l\'esperienza, che &egrave, il pi&ugrave, amaro. (Confucio)',
	'I principii coi quali vivi creano il mondo in cui vivi, se cambi i principii con cui vivi, tu potrai cambiare il tuo mondo. (Blain Lee)',
	'Se fai il meglio che ti &egrave, possibile, scoprirai, nove volte su dieci, che hai fatto tanto quanto, o forse meglio di, chiunque altro. (William Feather)',
	'Puoi avere tutto ci&ograve, che vuoi - se lo vuoi davvero intensamente. Puoi essere qualunque cosa tu decida di essere, fare qualsiasi cosa tu decida di realizzare, se ti aggrappi a quel desiderio con singolarit&agrave, di intenti. (Abram Lincoln)',
	'La pi&ugrave, grande scoperta della mia generazione &egrave, che l\'uomo pu&ograve, cambiare la sua vita semplicemente modificando la sua attitudine mentale. (William James)',
	'La resistenza a una nuova idea &egrave, proporzionale al quadrato della sua importanza. (Bertrand Russell (1872 - 1970))',
	'Se ci avessi pensato su, non avrei fatto l\'esperimento. Vi &egrave, un mare di esempi documentati che dicono che non si pu&ograve, fare. (Silver, l\'inventore dei bigliettini Post-it)',
	'Al mondo non ci sono che due modi di fare carriera, o grazie alla propria ingegnosit&agrave, o grazie all\'imbecillit&agrave, altrui. (De La Bruyere)',
	'Agli esami gli sciocchi fanno spesso domande a cui i saggi non sanno rispondere. (Oscar Wilde)',
	'Anche la pi&ugrave, lunga marcia comincia sempre da un singolo passo. (Mao Tse Tung)',
	'C\'&egrave, un angolo sciocco nel cervello dell\'uomo pi&ugrave, saggio. (Aristotele)',
	'Passare per idiota agli occhi di un imbecille &egrave, una volutt&agrave, da fine gourmet. (Georges Courteline)',
	'Ci&ograve, che ami fare &egrave, ci&ograve, che sei nato per fare. (Susan Taylor)',
	'L\'azione non sempre pu&ograve, condurre alla felicit&agrave,, ma non c\'&egrave, felicit&agrave, senza azione. (Benjamin Disraeli)',
	'Aristotele era famoso per la sua conoscenza di ogni cosa. Egli insegn&ograve, che il cervello esiste meramente per raffreddare il sangue e non era coinvolto nel processo del pensiero. Questo &egrave, vero solo per certe persone. (Will Cuppy)',
	'Due verit&agrave, che gli uomini generalmente non crederanno mai: l\'una di non saper nulla, l\'altra di non esser nulla. Aggiungi la terza, che ha molta dipendenza dalla seconda: di non aver nulla a sperare dopo la morte. (Giacomo Leopardi "Zibaldone")',
	'Il vero potere non consiste nel tentare di controllare gli altri, ma nell\'essere in controllo di se stessi. Quando reclami su di te questo potere, puoi scegliere il tipo di vita che vuoi condurre. (Gary Barnes)',
	'La visione senza azione &egrave, semplice sognare. L\'azione senza visione &egrave, un incubo. (Proverbio Giapponese)',
	'Ci vuole meno tempo a fare le cose nel modo giusto che a spiegare perch&eacute, le hai fatte nel modo sbagliato. (Henry Wadsworth Longfellow)',
	'Mi alzo e mi corico tardi, perch&eacute, non credo che Dio aiuti chi si alza presto. Vedete le galline che, nonostante si alzino con l\'alba, invecchiano facendo uova perch&eacute, gliele mangino gli altri e finiscono col morire in pentola. (E. Jardiel Poncela)',
	'La legge &egrave, uguale per tutti: proibisce tanto ai poveri quanto ai ricchi di rubare pane e di dormire sotto i ponti. (Anatole France)',
	'Alcuni vecchi vantano il passato in modo scortese per coloro che vivono nel presente. Con ci&ograve, dimostrando che, nel passato che essi lodano, di sciocchi ce n\'erano per lo meno quanti oggi. (A. Karr)',
	'Dubitare di se stessi &egrave, il primo segno dell\'intelligenza. (Ugo Ojetti)',
	'Ragione, intelletto, sentimento, passione, ma state attento, non escludete la pazzia. (Wolgfang Goethe)',
	'S&igrave,, amici miei, lo so: tutti i grandi uomini sono stati in un primo tempo misconosciuti. Ma siccome io non sono un grand\'uomo ci terrei ad essere conosciuto subito. (J. Renard)',
	'Noi siamo soli nella sofferenza. Questo &egrave, un fatto deprimente se siamo proprio noi la persona che soffre, ma questo fatto rende possibile la felicit&agrave, al resto del mondo. (A. Huxley)',
	'Preferisco i mascalzoni agli imbecilli, perch&eacute, a volte si concedono una pausa. (Alexander Dumas figlio)',
	'Pi&ugrave, uno &egrave, intelligente, pi&ugrave, sono le persone che uno trova originali: la gente ordinaria non vede differenza tra gli uomini. (Blaise Pascal)',
	'Il test di primo grado dell\'intelligenza &egrave, l\'abilit&agrave, di mantenere due idee opposte nella mente contemporaneamente, e conservarne tuttavia la capacit&agrave, di funzionamento. Uno dovrebbe, per esempio, essere capace di vedere che una certa situazione &egrave, senza speranza e tuttavia essere determinato a fare che sia altrimenti. (F.Scott Fitzgerard)',
	'Nella nostra societ&agrave, quelli che sono in realt&agrave, superiori in intelligenza possono venire accettati dai loro simili solo se pretendono di non esserlo. (Marya Mannes)',
	'Potrai avere qualunque cosa tu desideri nella vita se solo aiuterai un numero sufficiente di altre persone ad ottenere ci&ograve, che vogliono. (Zig Ziglar)',
	'Il problema dell\'umanit&agrave, &egrave, che gli stupidi sono strasicuri, mentre gli intelligenti sono pieni di dubbi. (Bertrand Russel)',
	'Non ci crederete, ma esistono stati sociali dove i governanti sono i pi&ugrave, intelligenti. Per esempio tra i babbuini. (Konrad Lorenz)',
	'Colui il quale non riesce pi&ugrave, a meravigliarsi e a restare rapito dalla meraviglia, &egrave, come se fosse morto, i suoi occhi sono chiusi. (Albert Einstein)',
	'Se A &egrave, il successo nella vita, allora A &egrave, uguale a X pi&ugrave, Y pi&ugrave, Z. Il lavoro &egrave, X, Y &egrave, il gioco, e Z &egrave, tenere la propria bocca chiusa. (Albert Einstein)',
	'Usa il talento di cui sei in possesso: i boschi sarebbero molto silenziosi se nessun uccello cantasse eccetto quelli che sanno cantare bene. (Henry Van Dyke)',
	'Non pensare mai alle conseguenze del fallimento, penserai sempre a risultati negativi. Pensa solo concetti positivi e la tua mente graviter&agrave, attorno a questi pensieri! (Michael Jordan)',
	'Il successo non &egrave, niente pi&ugrave, che poche semplici discipline, praticate ogni giorno, mentre il fallimento consiste semplicemente in alcuni errori di giudizio, ripetuti ogni giorno. E\' il peso cumulativo delle nostre discipline e dei nostri giudizi che ci conduce al successo oppure al fallimento. (Jim Rohn)',
	'La gente spesso dice che questa o quella persona non ha ancora trovato se stessa. Ma "se stessi" non &egrave, qualcosa che si trova, &egrave, qualcosa che uno si crea. (Thomas S. Szasz)',
	'Il mio ufficio? La mia mente &egrave, il mio ufficio. Niccol&ograve, Machiavelli (1469-1527)... e sono tanto semplici li uomini, e tanto obediscano alle necessit&agrave, presenti, che colui che inganna trover&agrave, sempre chi silascer&agrave, ingannare. (Albert Einstein)',
	'A questo mondo, o ci imponiamo una regola, o accettiamo che sia la vita ad imporcela. (Richard Campbell)',
	'Gli uomini che hanno cambiato l\'universo non sono mai arrivati a quel punto influenzando i sovrani, bens&igrave, facendo leva sulle masse. Influenzare i sovrani &egrave, il metodo dell\'intrigo e porta unicamente a risultati di secondaria importanza. Influenzare le masse, invece, &egrave, il colpo di genio che cambia la faccia del mondo. (Napoleone Bonaparte)',
	'Il vento &egrave, sempre favorevole per chi sa dove vuole andare',

// Leggi di Murphy
	'La tragica verit&agrave, &egrave, che il mondo &egrave, contro di noi',
	'Se qualcosa pu&ograve, andare male, lo far&agrave,',
	'Se c\'&egrave, una possibilit&agrave, che varie cose vadano male, quella che causa il danno  maggiore sar&agrave, la prima a farlo',
	'Lasciate pure a se stesse le cose, esse tendono ad andare di male in peggio',
	'Quando non pu&ograve, andare peggio di cos&igrave,, lo far&agrave,',
	'Quando le cose sembrano andare meglio c\'&egrave, qualcosa di cui non stiamo tenendo conto',
	'Se si spiegano le cose in maniera tale che nessuno possa non capire, qualcuno non capir&agrave,',
	'Qualsiasi cosa vada male, avr&agrave, probabilmente l\'aria di andare benissimo',
	'Quando si trova e si corregge un errore, si vedr&agrave, che andava meglio prima',
	'Quando si capisce che la correzione &egrave, sbagliata, sar&agrave, troppo tardi per tornare indietro',
	'Prima o poi la peggiore combinazione possibile di circostanze &egrave, destinata a prodursi',
	'Chi ha detto che le cose andranno meglio?',
	'Dopo aver assemblato un qualsiasi strumento ci si render&agrave, conto che due o pi&ugrave, sue parti sono rimaste sul banco da lavoro',
	'In quasiasi calcolo ogni errore che potr&agrave, intrufolarsi lo far&agrave,',
	'Se il proprio treno &egrave, in ritardo, la coincidenza partir&agrave, in perfetto orario',
	'Qualsiasi cosa si butti, servir&agrave, non appena non sar&agrave, pi&ugrave, disponibile',
	'Ogni programma si espander&agrave, fino ad occupare tutta la memoria disponibile',
	'Un oggetto cadr&agrave, sempre in modo da produrre il maggior danno possibile',
	'Nessuno sa veramente mai quel che succede in un qualsiasi punto dell\'organizzazione',
	'La gente &egrave, sempre disponibile per i lavori gi&agrave, fatti',
	'Ogni ordine che pu&ograve, essere frainteso &egrave, stato frainteso',
	'Colui che sorride quando le cose vanno male ha pensato a qualcuno a cui dare la colpa',
	'Ogni idea semplice sar&agrave, espressa nella maniera pi&ugrave, complicata',
	'Quando qualcuno che si ammira e si rispetta in sommo grado sembra essere immerso in profondi pensieri, probabilmente sta pensando alla cena',
	'Nulla &egrave, impossibile per colui che non deve farlo',
	'Uomini e nazioni agiranno razionalmente soltanto dopo aver esaurito ogni altra possibilit&agrave,',
	'Tutto &egrave, in uno stato di disordine assoluto',
	'A volte un uomo inciampa nella verit&agrave, ma nella maggior parte dei casi si rialzer&agrave, e proseguir&agrave, per la sua strada',
	'Se fate una sola copia del programma che pi&ugrave, vi interessa, non funzioner&agrave,',

// I pi&ugrave,
	'La pi&ugrave, triste ragazza statunitense: Judy Chord',
	'Il ministro delle poste statunitense: Frank Ball',
	'La pi&ugrave, grande prostituta statunitense: Calamy Jeans',
	'Il pi&ugrave, gran macellaio inglese: Paul Laster',
	'Il pi&ugrave, grande gommista inglese: Cooper Tony',
	'Il pi&ugrave, grande petroliere inglese: Sir Batoio... la figlia del suddetto: Miss Shela',
	'Il pi&ugrave, gran ciclista inglese: Sir Cion',
	'Il guardiano dello zoo di Londra: Sir Pent',
	'La pi&ugrave, grande prostituta inglese: July Slip',
	'Il pi&ugrave, grande tuffatore spagnolo: Pico de Panza... la moglie del suddetto: Dolores de Panza',
	'La pi&ugrave, gran freddolosa spagnola: Amalia de Lana',
	'La pi&ugrave, grande tuffatrice spagnola: Maria Che Spansada',
	'Il pi&ugrave, gran fuggiasco romeno: Chaoescu',
	'Il pi&ugrave, gran commissario romeno: Selupescu',
	'Il pi&ugrave, gran speleologo romeno: Emo Comescu',
	'Il portiere della squadra femminile rumena: Sara Cinescu',
	'Il pi&ugrave, gran dottore italiano: Benvenuto Mezzasalma (esistente)',
	'La pi&ugrave, gran prostituta italiana: Lisa Dall`Uso',
	'Il pi&ugrave, gran automobilista italiano: Guido Maluccio',
	'Il pi&ugrave, gran canottiere italiano: Remo Labarca',
	'La pi&ugrave, grande igienista italiana: Melalavo Domenica in Piazza',
	'La pi&ugrave, gran sessuologa italiana: Virginia Celeste',
	'Il pi&ugrave, grande giudice italiano: Massimo della Pena',
	'Il pi&ugrave, grande vescovo italiano: Amodio d&egrave, Pretis',
	'Il pi&ugrave, gran vulcanologo giapponese: Sarifuma Kef&ograve,',
	'Il pi&ugrave, gran scampato dalla bomba di Hiroshima: Erohito Akaka',
	'Il pi&ugrave, gran sarto giapponese: Tayato Sumisura',
	'Il pi&ugrave, gran dentista giapponese: Tekuro Lakarie',
	'Il pi&ugrave, gran equilibrista giapponese: Secaio Moio',
	'Il pi&ugrave, gran dietologo giapponese: Kala Kili',
	'Il pi&ugrave, gran stitico giapponese: Kakapoco Kifapocomoto',
	'Il pi&ugrave, grande archeologo giapponese: Kiruma Kataosi... il figlio del suddetto: Ikato Ankami',
	'Il ministro della giustizia giapponese: Takeo Takanarama',
	'Il pi&ugrave, grande frocio giapponese: Lano Mifuma',
	'La pi&ugrave, grande prostituta giapponese: Sudo Magodo',
	'Il ministro della sanit&agrave, giapponese: Urino Suimuri',
	'La riserva nella squadra giapponese: Iocopoco Majoco',
	'Il pi&ugrave, gran professore universitario giapponese: Sotuto Manontanto... l\'assistente del suddetto: Misi Kes&ograve,',
	'Il pi&ugrave, gran tuffatore giapponese: Sesoki Marus&agrave,... l\'allenatore del suddetto: Torusam&igrave,',
	'Il pi&ugrave, grande Motociclista giapponese: Haio Fuso Lamoto... il rivale del suddetto: Lofusa Yo',
	'Il pi&ugrave, gran freddoloso greco: Fafres Ketto',
	'La pi&ugrave, grande prostituta greca: Michela Dogratis (o Manola Dogratis)',
	'Il pi&ugrave, gran defecatore greco: Aristerco di Arrea',
	'Il pi&ugrave, grande attaccante polacco: Bostik (nome: Lion)',
	'La pi&ugrave, grande prostituta polacca: Vagina Seminova',
	'La pi&ugrave, grande ballerina polacca: Cholanca Sbilenca',
	'Il pi&ugrave, grande stitico arabo: Unn&egrave, Hammedda',
	'Il pi&ugrave, grande bevitore arabo: Nabir Albar',
	'Il pi&ugrave, gran segaiolo arabo: In Man Lah',
	'Il pi&ugrave, gran chiavatore arabo: Allah Ben Dur',
	'Il pi&ugrave, gran kamikaze irakeno: Saddam Mori',
	'Il pi&ugrave, grande saltatore in lungo arabo: Dala Ali',
	'Il pi&ugrave, gran pentito tra gli estremisti islamici: Ahmed Ispiash',
	'Il ministro dell\'agricoltura russo: Kar Ciof',
	'Il pi&ugrave, grande ecologista russo: Andrej Peribosky',
	'La pi&ugrave, grande cuoca russa: Tocotto Ottova',
	'Il pi&ugrave, grande frocio russo: Andrej Koimasky',
	'Il piu grande lanciatore di coltelli coreano: Ndo Cojo Cojo',
	'Il pi&ugrave, grande tuffatore coreano: Man Tra J&ograve,... l\'allenatore del suddetto: Sun St&agrave, M&igrave,',
	'Il pi&ugrave, gran saltatore a ostacoli cinese: Cin Chan Pai',
	'Il ministro delle finanze cinese: Teng Cing Lir',
	'Il pi&ugrave, gran falegname cinese: Chaun Chio Din',
	'Il pi&ugrave, grande campione di poker cinese: Chon Full',
	'Il pi&ugrave, grande pugile cinese: Sohito Steso',
	'Il pi&ugrave, grande Sciatore cinese: Scindu Cianki Cianki',
	'Il pi&ugrave, grande lanciatore di coltelli cinese: Ki Ciapo Ciapo... la moglie del suddetto: Sontuta Untai... il figlio dei suddetti: Cerotin',
	'Il ministro trasporti cinese: Fur Gon Cin... il figlio del suddetto: Choun Chao',
	'Il pi&ugrave, gran sciatore cinese: Ocio Al Pin',
	'Il pi&ugrave, gran ciclista cinese: In Cho Da',
	'Il pi&ugrave, gran freddoloso austriaco: Otto Maje',
	'Il pi&ugrave, gran fannullone tedesco: Von Kazzen',
	'Il pi&ugrave, grande nuotatore tedesco: Otto Vaske',
	'Il pi&ugrave, grande maniaco nigeriano: Tazanno Nazinna... il fratello indeciso: Chezinna Tazanno',
	'Il pi&ugrave, gran terrorista nigeriano: Mobuto Nabomba',
	'La pi&ugrave, grande puzzona egiziana: Theodora Tutankalavaten',
	'Il povero faraone egiziano morto in un incidente stradale: Sutankamion',

// Colmi
	'Colmo per una disoccupata: chiamarsi Assunta.',
	'Colmo per una dattilografa: ridere ad ogni battuta.',
	'Colmo per un viaggiatore: perdere il treno per essere andato al bar a prendere un espresso.',
	'Colmo per un venditore di camicie: sudarne 7 per venderne una.',
	'Colmo per un subacqueo: avere la testa fra le nuvole.',
	'Colmo per un sordo: non sentire ragioni.',
	'Colmo per un socialista: morire per arresto cardiaco.',
	'Colmo per un sacerdote: inchinarsi davanti ad un punto ... cardinale.',
	'Colmo per un marziano: avere l\'ernia al disco.',
	'Colmo per un innamorato:  donarle il cuore e sentirsi rispondere picche.',
	'Colmo per un generale: sentire freddo ... malgrado i gradi.',
	'Colmo per un esquimese: prendere delle decisioni a caldo.',
	'Colmo per un elettricista: mettere alla luce un figlio.',
	'Colmo per un elettricista: essere isolato.',
	'Colmo per un dentista: essere incisivo.',
	'Colmo per un contadino: piantare tutto e non ritornare pi&ugrave,.',
	'Colmo per un contadino: non capire un cavolo.',
	'Colmo per un cieco: andare al cinema a vedere un film muto.',
	'Colmo per un cane: avere una bella gatta da pelare.',
	'Colmo per un avvocato: accusare la stanchezza dopo un lungo processo.',
	'Colmo per un avvocato: stare seduto a leggere ... Diritto.',
	'Colmo per il Premier Britannico: farsi prendere dall\' IRA.',
	'Colmo di uno scozzese: andare in villeggiatura a Pago Pago.',
	'Colmo di una maestra: non aver classe.',
	'Colmo di una giostra: essere presa in giro.',
	'Colmo di una balena innamorata: innamorarsi in un baleno.',
	'Colmo di un veterinario: avere in ambulatorio 4 gatti da curare.',
	'Colmo di un santo: lamentarsi di avere un cerchio alla testa.',
	'Colmo di un ricettatore: doversi sbarazzare di una partita di frigoriferi che scottano.',
	'Colmo di un pilota di Formula 1: avere un figlio turbolento.',
	'Colmo di un pesce: perdersi in un bicchiere d\'acqua.',
	'Colmo di un negro: chiamarsi Bruno!',
	'Colmo di un matematico: vivere in una frazione.',
	'Colmo di un intellettuale di sinistra: farsi pagare in nero.',
	'Colmo di un graduato dell\'esercito: avere un fratello minore Maggiore',
	'Colmo di un fruttivendolo: avere un figlio finocchio, non poterlo vendere.',
	'Colmo di un ape maschio: non poter entrare in casa perch&eacute, la moglie ha dato la cera.',
	'Colmo di un altoparlante: sentirsi male.',
	'Colmo dello stitico: nascere a Chicago.',
	'Colmo dello sciatore: diventare rosso di vergogna per essere rimasto al verde dopo una settimana bianca.',
	'Colmo della tartaruga miope: sposare un elmetto tedesco.',
	'Colmo della suora: prendere un cappuccino a letto.',
	'Colmo della siccit&agrave,: un albero che corre dietro a un cane.',
	'Colmo della sarta: perdere il filo del discorso.',
	'Colmo della regina: essere bassa e farsi chiamare altezza.',
	'Colmo della maschera del cinema: fare luce in un film giallo.',
	'Colmo della gallina: covare un ovino.',
	'Colmo della cattiveria: portare un cieco a vedere un film muto.',
	'Colmo della biologa: essere una provetta lavoratrice.',
	'Colmo dell\'orologiaio: avere la figlia sveglia.',
	'Colmo dell\'ignoranza: non lo so.',
	'Colmo dell\'idraulico: non capirci un tubo.',
	'Colmo dell\'idraulico: avere il naso che gocciola.',
	'Colmo dell\'avarizia: usare i coriandoli come carta igienica... da tutte e due i lati.',
	'Colmo dell\'automobilista: fare il pieno con un assegno a vuoto.',
	'Colmo dell\'autista: spegnere il motore soffiando sulle candele.',
	'Colmo dell\'attore: essere nato a Camerino.',
	'Colmo dell\'astronauta: essere un uomo terra-terra.',
	'Colmo dell\'astronauta: avere gli occhi fuori delle orbite.',
	'Colmo dell\'arbitro: prendere il volo perch&eacute, si sono cacciate fuori le ali.',
	'Colmo dell\'anitra: avere la pelle d\'oca.',
	'Colmo del tipografo: essere un uomo di vecchio stampo.',
	'Colmo del socialista: vendere il didietro per comprare l\'Avanti.',
	'Colmo del sindaco: avere un\'intelligenza fuori del comune.',
	'Colmo del pugile: andare fino alla stazione per prendere un diretto.',
	'Colmo del prete: non poter mostrare la potenza del proprio organo.',
	'Colmo del postino: perdere la posta in gioco.',
	'Colmo del pizzaiolo: avere una moglie di Napoli che si chiama Margherita che ogni 4 stagioni fa la capricciosa.',
	'Colmo del pilota e della hostess: capirsi al volo.',
	'Colmo del pescatore: avere una moglie sarda che si chiama Alice.',
	'Colmo del pescatore: odiare il gusto della pesca.',
	'Colmo del pasticciere: avere fra i suoi clienti la crema della societ&agrave,.',
	'Colmo del paracadutista: cadere dalle nuvole.',
	'Colmo del paracadutista: giurare di non cascarci pi&ugrave,.',
	'Colmo del musicista: farsi accompagnare al piano dal ragazzo dell\'ascensore.',
	'Colmo del muratore: firmare le sue opere in calce.',
	'Colmo del miliardario: esprimersi in parole povere.',
	'Colmo del marinaio: salpare con il morale a terra.',
	'Colmo del Marchese De Sade: prendere una donna a mezzo sevizio.',
	'Colmo del macellaio: rinunciare ai piaceri della carne.',
	'Colmo del macellaio: avere la moglie vacca.',
	'Colmo del ladro: rubare del formaggio gi&agrave, grattato.',
	'Colmo del grassone: nascere sotto il segno della bilancia.',
	'Colmo del fumatore: girare tutta Firenze per trovare un toscano.',
	'Colmo del frate: fare il pollo alla diavola.',
	'Colmo del fotografo: avere un figlio poco sviluppato.',
	'Colmo del fotografo: mettere a fuoco un ghiacciaio.',
	'Colmo del fante: avere il padre fantino.',
	'Colmo del falegname: portare a teatro la moglie scollata.',
	'Colmo del fabbro: saldare una fattura con la fiamma ossidrica.',
	'Colmo del dispettoso: non te lo dico!',
	'Colmo del cuoco: mettere la cravatta all\'uovo in camicia.',
	'Colmo del cuoco: fare discorsi senza sugo.',
	'Colmo del criminale: indossare abiti ricercati.',
	'Colmo del cimitero: essere chiuso per lutto.',
	'Colmo del chirurgo: difendere il proprio operato.',
	'Colmo del cantante: non avere motivi validi.',
	'Colmo del cantante: essere brasiliano ed avere la voce... argentina. ',
	'Colmo del canguro: avere le borse sotto gli occhi.',
	'Colmo del calzolaio: trovare un concorrente che gli faccia le scarpe.',
	'Colmo del calciatore: fare il portiere di notte.',
	'Colmo del boia: non riuscire ad ammazzare il tempo.',
	'Colmo del barista: ritirarsi per fare il cappuccino.',
	'Colmo del barbiere: camminare radendo i muri.',
	'Colmo del bambino sporco: prendere una lavata di capo perch&eacute, ha i piedi sporchi.',
	'Colmo dei pompieri: spegnere una camera ardente con le pompe funebri.',
	'Colmo per un meccanico: farsi una motosega.',
	'Colmo per un genovese: usare la carta igienica da un solo lato.',
	'Colmo della velocit&agrave,: Cangrande della Scala inseguito da Castruccio dei Castracani.',
);

?>