<?php
/**
*
* @package Icy Phoenix
* @version $Id: lang_faq.php 97 2009-05-01 17:18:07Z Mighty Gorgon $
* @copyright (c) 2008 Icy Phoenix
* @license http://opensource.org/licenses/gpl-license.php GNU Public License
*
*/

/**
*
* @Icy Phoenix is based on phpBB
* @copyright (c) 2008 phpBB Group
*
*/

/**
*
* @Extra credits for this file
* Lopalong
*
*/

if (!defined('IN_ICYPHOENIX'))
{
	exit;
}

//
// To add an entry to your FAQ simply add a line to this file in this format:
// $faq[] = array("question", "answer");
// If you want to separate a section enter $faq[] = array("--","Block heading goes here if wanted");
// Links will be created automatically
//
// DO NOT forget the ; at the end of the line.
// Do NOT put double quotes (") in your FAQ entries, if you absolutely must then escape them ie. \"something\"
// The FAQ items will appear on the FAQ page in the same order they are listed in this file


$faq[] = array("--","Registratie- en inlogproblemen");
$faq[] = array("Waarom kan ik me niet inloggen?", "Heb je je geregistreerd? Je moet jezelf eerst registreren, voordat je je kunt inloggen. Ben je geband van dit forum (in dat geval wordt er een bericht weergegeven)? Wanneer dat zo is, zul je contact op moeten nemen met de beheerder, om uit te vinden, waarom.  Als je jezelf hebt geregistreerd en je bent niet geband en je nog altijd niet kunt inloggen, dan moet je je gebruikersnaam en wachtwoord goed controleren op fouten. Meestal ligt het daaraan, als dat niet zo is, neem dan contact op met de beheerder, het kan zijn dat het ligt aan een foutieve forumconfiguratie.");
$faq[] = array("Waarom moet ik mijzelf registreren?", "Het kan ook zijn, dat dat dat niet hoeft, dat is de beslissing van de beheerder. In elk geval houdt het registreren in dat je meer functies tot je beschikking hebt, die gasten niet hebben, b.v. avatar, privéberichten, deelnemen aan gebruikersgroepen, etc. Het registreren kost een paar minuten. Je kunt het ook gelijk doen.");
$faq[] = array("Waarom wordt ik automatisch uitgelogd?", "Als je de functie <i>Automatisch inloggen</i> bij het inloggen niet geactiveerd hebt, blijf je alleen voor een bepaalde tijd ingelogd. Daardoor wordt het misbruik van jouw gebruikersaccount voorkomen. Om ingelogd te blijven, kies dan de bijbehorende optie bij het inloggen. Deze wordt niet aangeraden, wanneer je in een vreemde omgeving zit, b.v. in een bibliotheek of universiteit, in internetcafé etc.");
$faq[] = array("Hoe kan ik voorkomen, dat mijn naam in de 'Wie is online?'-lijst voorkomt?", "In jouw profiel vind je de optie <i>Onlinestatus verbergen</i>, en wanneer je die activeert, wordt je naam alleen nog voor jezelf en de beheerders in die lijst weergegeven. Je wordt dan als een verborgen gebruiker geteld.");
$faq[] = array("Ik ben mijn wachtwoord vergeten!", "Geen probleem! Je kan een nieuwe wachtwoord aanvragen. Klik daarvoor op de loginpagina op de <u>Ik ben mijn wachtwoord vergeten</u> link. Volg de aanwijzingen en je zult weer snel kunnen inloggen.");
$faq[] = array("Ik heb mezelf geregistreerd, maar ik kan mijzelf niet inloggen!", "Controleer eerst, of je de juiste gebruikersnaam en/of wachtwoord ingegeven hebt. Als dit allemaal goed is, heb je twee mogelijkheden, wat er aan de hand kan zijn: Wanneer de COPPA ondersteuning geactiveerd is en je de optie <u> Ik ben jonger dan 13 jaar</u> bij het registreren gekozen hebt, moet je de ontvangen instructies volgen. Als dit niet het geval is, dan moet je account waarschijnlijk geactiveerd worden. Op sommige forums moet een registratie eerst geactiveerd worden, voordat je kunt inloggen - soms door jezelf en anders door een beheerder. Bij de registratie wordt je gezegd, of een activering nodig is of niet. Als de e-mail is aangekomen, volg dan de ontvangen instructies; heb je de e-mail niet ontvangen, wees er dan van overtuigt dat je e-mailadres klopt. Een reden voor het gebruik van accountsactiveringen is om misbruik op dit forum te voorkomen. Wanneer je zeker weet, dat de aangegeven e-mailadres de juiste is, neem dan contact op met de beheerder.");
$faq[] = array("Ik heb mijzelf enige tijd geleden geregistreerd, maar ik kan mijzelf niet meer inloggen!", "De reden daarvoor is op zijn minst, dat je een verkeerd gebruikersnaam of een verkeerd wachtwoord ingegeven hebt (controleer de e-mail, die je van het forum gekregen hebt) of dat de beheerder jouw account heeft verwijderd. Als het laatste het geval is, heb je misschien op jouw account geen berichten geplaatst? Dan is het mogelijk, dat de beheerder regelmatig gebruikers verwijderd, die geen berichten geplaatst hebben, om de grootte van de database te verkleinen. Probeer je opnieuw te registreren en je bent weer in de wereld van de discussies.");


$faq[] = array("--","Gebruikersvoorkeuren en instellingen");
$faq[] = array("Hoe verander ik mijn instellingen?", "Jouw instellingen (als je bent geregistreerd) zijn opgeslagen in de database. Klik op de <u>Profiel</u>-link, om deze te veranderen (wordt standaard in de bovenste navigatiebalk weergegeven, hangt van de stijl af). Daarmee kun je jouw instellingen veranderen.");
$faq[] = array("De tijden zijn niet goed!", "De tijden zijn hoogstwaarschijnlijk niet correct, vermoedelijk heb je de tijdzone niet goed ingesteld. Als dat het geval is, kun je de instellingen in jouw profiel controleren, om de tijdzone, die met jouw situatie overeenkomt, uit te kiezen. Hou rekening mee, dat je de tijdzone alleen kunt veranderen, wanneer je een geregistreerde gebruiker bent. Voor het geval dat je je nog niet geregistreerd hebt, is dit misschien een goede reden om het te doen.");
$faq[] = array("Ik heb de tijdzone veranderd maar de tijden zijn nog altijd niet goed!", "Wanneer je er zeker van bent dat je de juiste tijdzone uitgekozen hebt en de tijden nog steeds niet goed staan, kan het eraan liggen, dat het systeem op zomertijd staat. Het forum kan niet worden ingesteld, dat er wordt veranderd tussen zomer- en wintertijd, daarom kan het in de zomer een verschil van 1 uur zijn tussen jouw gekozen tijdzone en die van het forum.");
$faq[] = array("Mijn taal is niet beschikbaar!", "De waarschijnlijke reden daarvoor is, dat de beheerder de taal niet heeft geinstalleerd of dat het forum nog wordt omgezet naar jouw taal. Verzoek, de beheerder te overtuigen, jouw taal te installeren, lukt het niet, kan je ook zelf een vertaling maken. Meer informatie is beschikbaar via de phpBB Group website (de link onderaan elke pagina).");
$faq[] = array("Hoe kan ik een afbeelding onder mijn gebruikersnaam weergeven?", "Er kunnen zich twee afbeeldingen onder de gebruikersnaam bevinden. Het eerst behoort tot je rang, b.v. punten of sterren, die weergeven, hoeveel berichten je geplaatst hebt of welke status je op het forum hebt. Daaronder bevindt zich meestal een grotere afbeelding, avatar genaamd. Dit is een uniek en persoonlijk plaatje wat aan de gebruiker is verbonden. Het is aan de beheerder om de avatars in te schakelen en ze hebben de keuze op welke manier de avatars beschikbaar komen. Wanneer je geen avatar kunt gebruiken, is dit een beslissing van de beheerder. Je kunt hem/haar naar de reden vragen (we zijn er zeker van dat die meestal een goede reden hebben om het uit te schakelen!");
$faq[] = array("Hoe kan ik mijn rang veranderen?", "In de meeste gevallen kun je niet direct de rang veranderen (rangen worden weergegeven onder je gebruiksnaam in onderwerpen en in je profiel, afhankelijk van de gebruikte stijl). Meeste forums gebruiken rangen om aan te geven hoeveel berichten je geplaatst hebt of welke status je op het forum hebt. Bijvoorbeeld, moderators en beheerders hebben een speciale rang. Belast alstublieft het forum niet met onnuttige berichten (spam), alleen om je rang te verhogen, je wordt dan door de beheerder of moderator lager gezet in de rang (berichtenaantal verlagen).");
$faq[] = array("Wanneer ik op een e-maillink klik van een gebruiker, wordt mij gevraagd in te loggen.", "Alleen geregistreerde gebruikers kunnen op het forum e-mail versturen (als de beheerder de functie heeft ingeschakeld). Dit is om de voorkomen dat er misbruik wordt gemaakt van het systeem door anonieme gebruikers.");

$faq[] = array("--","Bericht plaatsen");
$faq[] = array("Hoe plaats ik een onderwerp in een forum?", "Heel eenvoudig, klik eenmaal op de bijbehorende knop op de forum of berichtenpagina. Het kan zijn dat je je eerst geregistreerd moet zijn, voordat je een nieuw onderwerp kan plaatsen op een forum - jouw uitvoerbare acties worden aan het einde van de pagina opgesomd (zoals <i>Je kan nieuwe onderwerpen openen, je kan aan peilingen deelnemen, etc.</i>-lijst)");
$faq[] = array("Hoe kan ik een bericht bewerken of verwijderen?", "Zolang je geen beheerder of moderator bent kun je alleen je eigen berichten bewerken of verwijderen. Je kan een bericht bewerken (mogelijk alleen voor een bepaalde tijd nadat je het geplaatst hebt) door op de <i>bewerk</i>knop te klikken van het betreffende bericht. Als iemand al op jouw bericht heeft gereageerd, wordt er een tekst aan het bericht toegevoegd onderaan het bericht van het aantal keer dat het bericht is bewerkt. Dit wordt alleen weergegeven als er iemand erop heeft gereageerd; het wordt niet weergegeven als een moderator of beheerder het bericht bewerkt (zij zullen een bericht achterlaten waarom het bewerkt is). Let op, normale gebruikers kunnen geen berichten verwijderen, waarop iemand al heeft gereageerd.");
$faq[] = array("Hoe voeg ik een onderschrift toe aan mijn berichten?", "Om een onderschrift toe te voegen aan een bericht, moet je er eerst een onderschrift in het profiel aanwezig zijn. Wanneer je een onderschrift hebt gemaakt, activeer je de <i>onderschrift toevoegen</i> functie, zodat je onderschrift wordt toegevoegd aan je berichten. Je kan ook standaard bij ieder bericht een onderschrift toevoegen, dit doe je door in het profiel de bijbehorende optie in te schakelen. Je kan het toevoegen van een onderschrift dan altijd nog verhinderen door bij het plaatsen van een bericht de optie uit te schakelen.");
$faq[] = array("Hoe maak ik een peiling aan?", "Een peiling aanmaken is eenvoudig: wanneer je een nieuw onderwerp maakt (of de eerste bericht van een onderwerp bewerkt, als je daar de rechten voor hebt), zul je de <i>Peiling toevoeg</i>-optie onderaan het scherm te zien krijgen (als je de optie niet te zien krijgt, heb je waarschijnlijk niet de juiste rechten).  Je kunt daar een titel voor jouw peiling toevoegen met minstens twee antwoordmogelijkheden (om een antwoord in te geven, klik je op de <i>Antwoord toevoegen</i> knop. Je kan ook een tijdlimiet voor de peiling instellen, 0 is voor een oneindig durende peiling. Er zit een grens voor het aantal antwoordopties, deze legt de beheerder vast.");
$faq[] = array("Hoe bewerk of verwijder ik een peiling?", "Hetzelfde als bij berichten kunnen peilingen alleen door de auteur, moderator of beheerder bewerkt of verwijderd worden. Om een peiling te veranderen, bewerk dan het eerste bericht van het onderwerp (de peiling is daarmee altijd verbonden). Wanneer nog niemand aan de peiling heeft deelgenomen, kan de gebruiker de peiling bewerken of verwijderen: in het geval dat er al iemand heeft gestemd op je peiling, kunnen alleen moderators en beheerders het alleen nog bewerken of verwijderen. Daarmee wordt voorkomen, dat gebruikers je peiling beïnvloeden, door de antwoorden te veranderen");
$faq[] = array("Waarom kan ik een forum niet bezoeken?", "Sommige forums kunnen alleen door bevoegde bezoekers of groepen worden bezocht. Om daar berichten te bekijken, plaatsen etc. kun je een speciale bevoegdheid krijgen. Alleen moderators en de beheerders kunnen je toegangsrechten daarvoor geven, je zult hen om toegang moeten vragen, als je daar een goede reden voor hebt.");
$faq[] = array("Waarom kan ik niet in peilingen stemmen?", "Alleen geregistreerde gebruikers kunnen op peilingen stemmen om te voorkomen dat de resultaten worden beïnvloed. In het geval dat je je geregistreerd hebt en nog altijd niet kunt stemmen, heb je vermoedelijk niet de juiste rechten daarvoor.");

$faq[] = array("--","Wat kan men doen in en met berichten?");
$faq[] = array("Wat is BBCode?", "BBCode is een speciaal soort van HTML. Om de BBCode te mogen gebruiken is bepaald door de beheerder. Je kan het ook per bericht uitschakelen. BBCode op zich is gelijk aan HTML, tags zijn ingesloten in rechte haken [ en ] inplaats van &lt; en &gt; en het geeft een betere controle over wat en hoe iets wordt weergeven. Voor meer informatie over BBCode bekijk de BBCode Help op het berichtformulier.");
$faq[] = array("Kan ik HTML gebruiken?", "Dat hangt er vanaf, als het door de beheerder toegestaan wordt. In het geval dat HTML is toegestaan zullen maar een paar tags werken. Dit is een <i>veiligheid</i>maatregel om het forum te beschermen zodat sommige de layout niet kunnen veranderen of andere problemen kunnen veroorzaken. Als HTML is ingeschakeld kun je het op het berichtformulier uitschakelen.");
$faq[] = array("Wat zijn smilies?", "Smilies zijn kleine afbeeldingen, die gebruikt kunnen worden, om een gevoel uit te drukken. Daar zijn alleen korte codes voor nodig, b.v. :) betekent blij en :( betekent verdrietig. De complete lijst van de smilies kan op de berichtformulier worden bekeken. Overdrijf niet met smilies, het kan snel gebeuren, dat een bericht daardoor niet overzichtelijk wordt. Een moderator kan daardoor een bericht bewerken of zelfs compleet verwijderen zonder waarschuwing.");
$faq[] = array("Kan ik afbeeldingen plaatsen?", "Afbeeldingen kunnen inderdaad worden weergegeven in je berichten. In elk geval is er nog geen mogelijkheid om afbeeldingen direct op het forum te uploaden. Daarom moet je het betreffende afbeelding uploaden op een andere server. Daarna kun je naar het betreffende afbeelding linken, welke zich op een openbare toegankelijke server bevindt. bijv. http://www.mijnhomepagina.nl/mijnafbeelding.gif.  Je kan niet linken naar afbeeldingen, die zich bevinden op je eigen computer (behalve als de gebruiker toegang heeft tot die server) noch afbeeldingen opslaan bij bijv. Hotmail of Yahoo mailboxen, sites met wachtwoordbeveiliging enz. Om een afbeelding in je bericht te plaatsen, gebruik dan de BBCode tag [img] of gebruik HMTL (als het is toegestaan).");
$faq[] = array("Wat zijn mededelingen?", "Mededelingen bevatten meestal belangrijke informatie en je wordt aangeraden om het zo snel mogelijk te lezen. Mededelingen verschijnen altijd bovenaan op iedere pagina in het forum waarin deze is geplaatst. Of je een mededeling kan plaatsen of niet hangt af, wat voor bevoegdheid daarvoor nodig is. Deze legt de beheerder vast.");
$faq[] = array("Wat zijn vastgepinde onderwerpen?", "Vastgepinde onderwerpen verschijnen onder de mededelingen in het forumoverzicht. Deze bevatten meestal ook belangrijke informatie, die je gelezen moet hebben. Hetzelfde als bij mededelingen is het ook bij de vastegepinde onderwerpen zo, dat de beheerder bepaald wie ze kan plaatsen.");
$faq[] = array("Wat zijn gesloten onderwerpen?", "Onderwerpen welke door de moderator of beheerder zijn gesloten. Men kan op een gesloten bericht niet meer reageren. In geval dat er een peiling is toegevoegd, wordt deze daarmee ook gesloten. Er zijn verschillende redenen, waarom een onderwerp gesloten wordt.");

$faq[] = array("--","Gebruikersniveaus en groepen");
$faq[] = array("Wat zijn beheerders?", "Beheerders zijn mensen met de hoogste niveau en configuratiemogelijkheden op het gehele forum. Zij hebben het recht om elke forumactie te ondernemen en speciale acties door te voeren, zoals het geven van bevoegdheden, bannen van gebruikers, gebruikersgroepen instellen, moderators aannemen etc. Ze hebben bovendien op elk forum de volledige moderatorrechten.");
$faq[] = array("Wat zijn moderators?", "Moderators zijn personen (of groepen), die dagelijks een forumgedeelte in de gaten houden. Ze hebben de mogelijkheid, berichten te bewerken en te verwijderen, onderwerpen te sluiten, te openen, te verplaatsen en te verwijderen. Moderators hebben de opdracht, gebruikers daarvan te weerhouden, ongepaste onderwerpen in een bericht of andere off-topic (spam) in het forum te plaatsen.");
$faq[] = array("Wat zijn gebruikersgroepen?", "In gebruikersgroepen worden enkele gebruikers door de beheerder samen in een groep gezet. Iedere gebruiker kan in meerdere groepen zitten en iedere groep kan speciale rechten hebben. Zo is het voor de beheerder eenvoudiger, meerdere gebruikers als moderators te hebben, hun rechten te geven voor een privéforum en zo verder.");
$faq[] = array("Hoe kan ik een gebruikersgroep betreden?", "Om een gebruikersgroep te betreden, klik je op de gebruikersgroepen link in het menu. Je krijgt dan een overzicht van alle gebruikersgroepen die aanwezig zijn. Niet alle groepen hebben <i>open toegang</i>, sommige zijn gesloten of andere zijn verborgen. In het geval dat een groep, een groepslid nodig hebben, kun je om toelating vragen, door op de toegangsknop te klikken. De groepsmoderator moet zijn toestemming dan nog wel geven; eventeel krijg je een aantal vragen, waarom je de groep wilt betreden. Leg je neer bij het besluit van een groepsmoderator, indien deze je aanvraag afkeurt, dit doen ze om verschillende redenen.");
$faq[] = array("Hoe kan ik een gebruikersgroep moderator worden?", "Gebruikersgroepen zijn aangemaakt door de beheerder, de beheerder kiest dan ook een groepsmoderator. Indien je interesse hebt in het maken van een gebruikersgroep moet je eerst contact opnemen met de beheerder, stuur de beheerder dan een privébericht.");

$faq[] = array("--","Privéberichten");
$faq[] = array("Ik kan geen privéberichten versturen!", "Er zijn drie mogelijke redenen: je bent niet geregistreerd of ingelogd, de beheerder heeft het privéberichtensysteem van het gehele forum uitgeschakeld of de beheerder heeft het versturen van privéberichten voor jouw uitgeschakeld. In het laatste geval, zul je de beheerder moeten vragen welke redenen daarvoor zijn.");
$faq[] = array("Ik ontvang steeds ongewenste privéberichten!", "In de toekomst komt er een lijst met ongewenste mails in het privéberichtensysteem. Als je momenteel steeds ongewenst privéberichten ontvangt neem dan contact op met de beheerder, zij hebben de mogelijkheid om voor de gebruiker het onmogelijk te maken om een privébericht te kunnen versturen.");
$faq[] = array("Ik heb spam of beledigende e-mail gekregen van iemand van dit forum!", "We vinden het spijtig dit te horen. Het e-mailformulier van dit forum heeft een beveiliging om zulke gebruikers op te sporen. Stuur een e-mail naar de beheerder met een volledige kopie van de e-mail die je hebt ontvangen, het is heel belangrijk dat deze ook de \"headers\" bevat (deze geven details van de gebruiker die de e-mail heeft gezonden). Dan kunnen de beheerders actie ondernemen, waar nodig.");

$faq[] = array("--","Avatar Generator");
$faq[] = array("Wat is dit?", "De <strong>Avatar Generator</strong> kan door gebruikers van het forum gebruikt worden, om een eigen avatar te maken.");
$faq[] = array("Waar kan ik deze MOD vinden?", "Je moet ingelogd zijn om gebruik te kunnen maken van de Avatar Generator. Het is te vinden in je avatarsectie binnenin je profiel.");
$faq[] = array("Hoe sla ik mijn gemaakte avatar op?", "Onder de gemaakte avatar zou een link met de opschrift <strong>Klik hier om jouw avatar in profiel in te voegen</strong> moeten zijn. Wanneer je op deze link klikt, komt er een bericht, die je over de volgende actie informeert.");

$faq[] = array("--","Fotoalbum");
$faq[] = array("Hoe kan ik het fotoalbum bekijken?", "Eenvoudig door de link 'Fotoalbum' in de navigatiemenu te gebruiken. Daardoor kom je in het hoofdalbumoverzicht uit, waar alle openbare categorieën weergegeven worden. Je kan ook de persoonlijke gallerijen van de gebruikers bekijken door op de link 'persoonlijke gallerij van gebruikers' onder de openbare categorieën te klikken.");
$faq[] = array("Hoe upload ik een afbeelding in een fotoalbum?", "Wanneer je op de hoofdalbumoverzicht bent, selecteer je een 'openbare album' of 'jouw persoonlijke gallerij' uit. Nu zul je een knop 'afbeelding uploaden' boven en onder aan de pagina te zien krijgen. Klik op deze knop en volg de verdere instructies.");
$faq[] = array("Wat is het maximale toegestane bestandsgrootte, afbeeldingsbreedte en afbeeldingshoogte?", "Deze gegevens kun je op de pagina 'afbeelding uploaden' te zien krijgen. De beheerder legt de maximale bestandsgrootte, mogelijke bestandenrestricties en andere voor afbeeldingen vast die nog geupload worden.");
$faq[] = array("In welk formaat moeten mijn afbeeldingen zijn?", "Deze gegevens kun je op de pagina 'afbeeldingen uploaden' te zien krijgen. De beheerder legt de maximale bestandsgrootte, mogelijke bestandenrestricties en andere voor afbeeldingen vast die nog geupload worden.");
$faq[] = array("Ik kan mijn afbeelding nog altijd niet uploaden en krijg altijd een foutmelding!", "Ga terug naar het uploadformulier en verzeker je ervan, dat alle aanwijzingen goed opgevolgd hebt. De afbeelding kan groter zijn dan de toegestaande maximum grootte, misschien heb je een afbeelding die een te grootte hoogte of breedte heeft, of heb je een afbeeldingsformaat die niet wordt toegestaan of je hebt een aantal verplichte velden vergeten in te vullen.");
$faq[] = array("Ik heb een fout gemaakt in de titel en/of de beschrijving. Wat kan ik doen?", "Wanneer je een afbeelding bezoekt, heb je meerdere keuzeopties om te kiezen. Wanneer de beheerder het toestaat, wordt de link 'bewerken' onder elke thumbnail weergegeven. Deze staat daar, om op elk gewenste tijd de informatie te kunnen veranderen.");
$faq[] = array("How kan ik een afbeelding verwijderen?", "Wanneer je een album bezoekt, heb je meerdere keuzeopties om te kiezen. Wanneer de beheerder het toestaat, wordt de link 'verwijderen' onder elke thumbnail weergegeven. Deze staat daar, om op elk gewenste tijd een afbeelding te kunnen verwijderen.");
$faq[] = array("Ik wil graag iemand meedelen, wat ik van de afbeelding vind. Waar kan ik dat doen?", "Wanneer je een album bezoekt, heb je meerdere keuzeopties om te kiezen. Wanneer de beheerder het toestaat, wordt de link 'beoordelingen' en 'opmerkingen' onder elke thumbnail weergegeven. Deze staat daar, om op elk gewenste tijd een afbeelding te beoordelen en opmerkingen te kunnen plaatsen.");

$faq[] = array("--","Bijlagen");
$faq[] = array("Hoe kan ik een bijlage toevoegen?", "Je kan bijlagen toevoegen, wanneer je een nieuw bericht wilt plaatsen. Je zult een <i>Bijlage toevoegen</i> formulier on het eigenlijke berichtenformulier te zien krijgen Wanneer je op <i>Bladeren</i> knop klikt opent de standaard \"bestand selecteren...\" dialoogvenster op het scherm. Zoek naar een bestand, die je graag wilt toevoegen, selecteer deze en klik op OK, open of dubbelklik op het bestand naar uw persoonlijke voorkeuren en procedure van het systeem. Wanneer je een beschrijving bij je bijlage in het veld <i>Beschrijving</i> toevoegt, dan wordt jouw opmerking als link bij het toegevoegde bestand gebruikt, anders wordt de bestandsnaam als link gebruikt. Als de beheerder het plaatsen van meerdere bijlagen in een bericht heeft toegestaan, dan kan je de bovenstaande procedure herhalen totdat de maximum aantal toegestaande bijlagen per bericht bereikt is.<br/><br/>De beheerder kan een maximaal toegestane bestandsgrootte opgeven, verboden bestandenextensies definiëren en bestanden voor bijlagen in het forum vastleggen. Wees ervan bewust dat het je eigen veranwoordelijkheid is dat je bijlagen niet in strijd zijn met regels van het forum en dat bijlagen zonder waarschuwing kunnen worden verwijderd.<br/><br/>Verder neemt de eigenaar van het forum, de webmaster, de beheerder noch de moderators enige verantwoording voor verlies van gegevens en bijlagen.");
$faq[] = array("Hoe voeg ik een bijlage toe nadat ik een bericht heb geplaatst?", "Om na het plaatsen van een bericht nog een bijlage in het bericht te plaatsen, kun je het bericht bewerken en de bovenstaande procedure volgen. De nieuwe bijlage wordt toegevoegd op het moment dat je op <i>OK</i> klikt om het bericht te plaatsen.");
$faq[] = array("Hoe kan ik een bijlage verwijderen?", "Om een bijlagen te verwijderen, moet je het bericht bewerken en klikken op <i>Bijlage verwijderen</i>, naast de bijlage die je wilt verwijderen. De bijlage wordt verwijderd nadat je op de <i>Bevestig</i> knop hebt geklikt om het bericht te plaatsen.");
$faq[] = array("Hoe verander ik de bestandsbeschrijving?", "Om de bestandsbeschrijving aan te passen moet je het bericht bewerken, de tekst in het <i>Bestandsbeschrijving</i> veld veranderen en op de <i>Beschrijving bijwerken</i> knop klikken naast het bestand waarvan je de beschrijving wilt veranderen. De bestandsbeschrijving wordt aangepast als je op <i>OK</i> klikt om het bericht te plaatsen.");
$faq[] = array("Waarom is mijn bijlage niet zichtbaar in het bericht?", "Waarschijnlijk is het bestand of het bestandstype niet meer toegestaan op het forum. De bijlage kan ook verwijderd zijn door een moderator of beheerder omdat het in strijd is met de regels die op het forum gelden.");
$faq[] = array("Waarom kan ik geen bijlagen plaatsen?", "Op sommige forums is het plaatsen van bijlagen alleen toegestaan voor bepaalde gebruikers of groepen. Om bijlagen toe te voegen heb je wellicht speciale rechten nodig, die alleen de beheerder je kan geven, hierover kun je contact met de beheerder opnemen.");
$faq[] = array("Ik heb de benodigde rechten, waarom kan ik geen bijlagen plaatsen?", "De beheerder heeft een limiet gesteld aan de totale bestandsgrootte van de bijlagen op het forum en er zijn verboden extensies en bestandstypen ingesteld. Een moderator of beheerder kan je rechten aangepast hebben, of het plaatsen van bijlagen op een forum hebben uitgeschakeld. Als je een bijlage probeert te plaatsen, zou je daarover uitleg moeten krijgen door middel van een foutmelding, als dit niet het geval is, kan je contact opnemen met de beheerder.");
$faq[] = array("Waarom kan ik geen bijlagen verwijderen?", "Op sommige forums is het verwijderen van bijlagen alleen toegestaan voor bepaalde gebruikers of groepen. Om bijlagen te verwijderen heb je wellicht speciale rechten nodig, die alleen de beheerder je kan geven, hierover kun je contact met de beheerder opnemen.");
$faq[] = array("Waarom kan ik geen bijlagen downloaden/bekijken?", "Op sommige forums is het downloaden/bekijken van bijlagen alleen toegestaan voor bepaalde gebruikers of groepen. Om bijlagen te downloaden/bekijken heb je wellicht speciale rechten nodig, die alleen de beheerder je kan geven, hierover kun je contact met de beheerder opnemen.");
$faq[] = array("Met wie kan ik contact opnemen over (mogelijk) illegale bijlagen?", "Je zou hierover contact op moeten nemen met de beheerder van dit forum. Als je niet kan vinden wie dit is, kun je dit eerst aan een van de moderators vragen. Als je ook daar geen antwoord krijgt kun je de eigenaar van het domein (doe een whois opdracht) benaderen of, als dit forum bij een gratis provider is ondergebracht (bijv. yahoo, lycos, f2s.com, etc.), het managementafdeling van deze provider. De phpBB Group heeft absoluut geen controle op en kan op geen enkele manier aansprakelijk gehouden worden voor hoe, waar of door wie deze forumsoftware gebruikt wordt. Het is totaal zinloos om de phpBB Group te benaderen in relatie tot enige juridische kwestie die niet direct gerelateerd is aan de phpbb.com website of de software van phpBB zelf. Als je de phpBB Group toch benaderd over een derde partij die haar software gebruikt, dan moet je geen antwoord verwachten.");

$faq[] = array("--","Downloads ADV");
$faq[] = array("Waar kan ik de downloads vinden?", "De link naar de downloadpagina is te vinden bovenaan iedere pagina in de navigatie. Directe link: [<a href=\"downloads.php\">Downloads</a>]");
$faq[] = array("Wat betekent <img border=\"0\" src=\"" . $images['Dl_blue'] . "\" alt=\"\" title=\"\" />?", "Geen download mogelijk. Het totale verkeer dat is ingesteld door de beheerder voor de download, of voor de weergegeven categorie is verbruikt voor deze maand.");
$faq[] = array("Wat betekent <img border=\"0\" src=\"" . $images['Dl_red'] . "\" alt=\"\" title=\"\" />?", "Geen download mogelijk. Dit kan betekenen dat:<br />- De download is geblokkeerd door een beheerder.<br />- De gebruiker is niet ingelogd, maar downloaden is alleen toegestaan voor geregistreerde gebruikers.<br />- De gebruiker heeft niet genoeg dataverkeer om dit bestand te downloaden.<br />- De beheerder vereist een minimum aantal berichten, die de gebruiker niet heeft.<br />- Het dataverkeer voor dit bestand is compleet verbruikt.");
$faq[] = array("Wat betekent <img border=\"0\" src=\"" . $images['Dl_grey'] . "\" alt=\"\" title=\"\" />?", "Externe bron. De download wordt gestart vanaf een externe server. Dit zal worden behandeld als <img border=\"0\" src=\"" . $images['Dl_green'] . "\" alt=\"\" title=\"\" />. Deze download gaat niet ten koste van het gebruikersverkeer en het totale dataverkeer.");
$faq[] = array("Wat betekent <img border=\"0\" src=\"" . $images['Dl_white'] . "\" alt=\"\" title=\"\" />?", "Net als bij <img border=\"0\" src=\"" . $images['Dl_green'] . "\" alt=\"\" title=\"\" /> het gebruikersverkeer zal niet worden verlaagd, maar alleen geregistreerde gebruikers kunnen dit bestand downloaden. Het totale verkeer zal wel verlaagd worden.");
$faq[] = array("Wat betekent <img border=\"0\" src=\"" . $images['Dl_yellow'] . "\" alt=\"\" title=\"\" />?", "Download mogelijk met beperkingen. Deze download is alleen mogelijk voor geregistreerde gebruikers. De bestandsgrootte zal worden afgetrokken van het gebruikersaccount en van het totale dataverkeer.");
$faq[] = array("Wat betekent <img border=\"0\" src=\"" . $images['Dl_green'] . "\" alt=\"\" title=\"\" />?", "Vrije download. Iedereen kan dit bestand downloaden, inclusief gasten. Alleen het totale dataverkeer zal dalen.");
$faq[] = array("Waarom kan ik geen bestanden downloaden?", "Dit kan meerdere redenen hebben. Kijk bij <img border=\"0\" src=\"" . $images['Dl_blue'] . "\" alt=\"\" title=\"\" /> en <img border=\"0\" src=\"" . $images['Dl_red'] . "\" alt=\"\" title=\"\" />.");
$faq[] = array("Hoe en wanneer krijg ik nieuw dataverkeer voor mijn account?", "Na de eerste keer inloggen heeft de gebruiker een tijdvertraging voor het verkrijgen van dataverkeer. Elke eerste dag van de maand wordt het dataverkeer vernieuwd. Vraag de beheerder voor de hoeveelheid dataverkeer dat jij krijgt.");
$faq[] = array("Ik wil graag een bestand downloaden, maar ik heb geen dataverkeer meer?", "In dit geval kun je contact opnemen met de beheerder. Alleen hij kan het dataverkeer verhogen voordat het account automatisch nieuw dataverkeer krijgt aan het begin van de maand.");
$faq[] = array("Hoe kan ik downloads waarderen?", "Achter elke download in een categorie of in de details vind je een knop om een download te waarderen.<br />Door te klikken op \"Waardeer\" kan een geregistreerde gebruiker de download waarderen van 1 punt (zeer slecht) tot 10 punten (uitstekend). Een download kan slechts eenmalig gewaardeerd worden per gebruiker");

$faq[] = array("--","Digests");
$faq[] = array("Wat zijn Digests?", "Digests zijn e-mailberichten met een samenvatting van nieuwe berichten in de forums welke regelmatig toegezonden kan worden. Wekelijkse of dagelijkse Digests zijn mogelijk.");
$faq[] = array("Waarom wil je Digests hebben?", "Het maakt het bezoeken van het forum eenvoudiger. Je hoeft dan niet onbeperkt de website te bezoeken om mee te doen aan onderwerpen die op dit moment worden besproken. Je leest eenvoudig de Digest en je weet waar over wordt gesproken, welke je interesseert, klik je aan en dan kun je deelnemen aan de discussie. Je kan de Digest op elk gewenst moment weer deactiveren.");
$faq[] = array("Hoe vaak worden Digests verzonden?", "Je ken een keuze maken tussen wekelijks of dagelijks verzenden van Digests. Wekelijkse Digests worden op zondag verstuurd.");
$faq[] = array("Wanneer worden Digests verzonden?", "Je kan vastleggen, om welke uur je de Digests wilt hebben. Maakt niet uit welke tijd je kiest je wordt altijd op de hoogte gehouden van het laatste nieuws wanneer je het maar uitkomt.");
$faq[] = array("Welke tijdsruimte word in de Digests vermeld?", "Elke 24 uur of 7 dagen, afhankelijk of je gekozen hebt voor een dagelijkse of een wekelijkse verzending. Oudere berichten worden niet meer verzonden. Je kan ook ervoor kiezen om alleen berichten erin te laten opnemen wat je nog niet hebt bezocht, als je het forum regelmatig bezoekt. Je kan ook je eigen berichten eruit filteren.");
$faq[] = array("Ik wil niet meer samenvattingen van elke bericht op dit forum. Kan ik ook forums uitsluiten?", "Ja, je kan ook een forum uitsluiten waar je niet in geinteresseerd bent. Normaal worden alle berichten van elk forum waar je toegang tot hebt naar je in de Digest verzonden.");
$faq[] = array("Welke e-mailformaat is beschikbaar?", "We kunnen je HTML- of Tekst- e-mails versturen. Kan je e-mailprogramma niet met HTML-berichten omgaan (wat tegenwoordig ongewoon is) kan je het e-mail ook in tekstvorm ontvangen. We adviseren om het in HTML te laten versturen (als je e-mailprogramma er geen problemen heeft), omdat Digests in tekstvorm onoverzichtelijk is.");
$faq[] = array("Krijg ik volledige teksten uit berichten in de Digests?", "Normaal krijg je de eerste 150 tekens van de berichten verstuurd. Maar je kan ook een keuze maken uit een aantal opties. Zo kan je ook geen berichttekst ontvangen maar alleen de onderwerptitels, of je kiest tussen 50, 100, 150, 300 of 600 tekens, of voor het complete berichttekst (tot zo\'n 32.000 tekens). Iedere langer bericht wordt dan automatisch afgebroken. Wij adviseren om de standaard berichtlengte aan te houden, omdat anders de Digests mogelijk te groot en onoverzichtelijk wordt. Bovendien kunnen zeer grote Digests de limiet van je provider overschrijden en afgewezen worden. Waarom? Omdat elk bericht een link heeft, die je direct naar het onderwerp brengt.");
$faq[] = array("Waar kan ik het vinden?", "Klik eenvoudig op de Digests link in de navigatieblok of klik hier: <a href=\"./digests.php\">Digests</a>.");
$faq[] = array("Kan je je weer afmelden?", "Ja, natuurlijk! Ga naar de Digest Pagina en kies \"geen\" voor \"Type van de gewenste Digest\" en bevestig het formulier. Je abonnement wordt dan direct beëindigd.");
$faq[] = array("Zijn Digests reclamevrij?", "Ja, er zit geen reclame of banner in de Digests.");
$faq[] = array("Is mijn privacy gewaarborgd?", "Ja, je Digest wordt alleen naar jouw verzonden en niet naar iemand anders, naar het e-mailadres die is opgegeven in jouw profiel. Een Digest is een \"Speciale Editie\" en alleen voor jouw. Iemand anders krijgt een andere Digest.");


$faq[] = array('--','Unread Post Information 2 Database (UPI2DB)');
$faq[] = array('Wat is het verschil tussen de standaard cookiemethode en het UPI2DB Systeem?', 'Het cookiesysteem is de standaard manier voor phpBB2 forums. Als je een bericht gelezen hebt, wordt deze informatie opgeslagen in een cookie op je PC, met daarin de informatie dat je het bericht gelezen hebt. Het grote nadeel van dit systeem is, dat je de informatie kwijtraakt op het moment dat je je internetbrowser afsluit. Het UPI2DB systeem slaat de informatie niet in een cookie, maar in de database zelf op, waardoor de informatie blijft bestaan, zelfs als je achter een andere computer zit of nadat je de internetbrowser weer opnieuw opent.'); 
$faq[] = array('Wat zijn de voor- en nadelen van het cookiesysteem??', '<strong>Voordeel:</strong> Bij grotere forums werkt het normale cookiesysteem sneller en zal de pagina sneller laden, dan wanneer het UPI2DB systeem gebruikt wordt, omdat UPI2DB de informatie uit de database moet halen. Een ander voordeel is, dat de informatie maanden bewaard kan blijven, als je de gegevens tenminste niet van je PC verwijderd. Dit is interessant voor gebruikers die slechts af en toe (bijv. elke 2 maand) op het forum komen.<br /><strong>Nadeel:</strong> Het grootste nadeel van het systeem is dat automatisch alle berichten als gelezen markeert wordt op het moment dat je de internetbrowser afsluit. Daarnaast worden bewerkte berichten niet als ongelezen gemarkeerd, terwijl ze dat in feite wel zijn, hierdoor worden bewerkte berichten vaak gemist.'); 
$faq[] = array('Wat zijn de voor- en nadelen van het UPI2DB systeem?', '<strong>Voordeel:</strong> Ongelezen berichten blijven als ongelezen staan, ook al sluit je de internetbrowser, je hoeft dus nooit alle ongelezen berichten in 1x te lezen. Berichten kunnen ook worden gemarkeerd als gelezen voor een periode van ' . (!empty($unread_days) ? $unread_days : 0) . ' met het UPI2DB systeem. Forums die niet interessant voor je zijn, kun je markeren als "permanent gelezen", tot je deze optie weer aanpast. Bewerkte berichten worden automatisch weer gemarkeerd als ongelezen met een notitie "bewerkt" en zullen een andere kleur hebben dan normale ongelezen berichten. Een nieuwe zoekmogelijkheid geeft je de mogeljkheid om te zoeken op alleen ongelezen of bewerkte berichten. Als de beheerders de weergave van bewerkte berichten bovenaan ieder onderwerp heeft aangezet, worden bewerkte berichten weergegeven als eerste bericht van het onderwerp.<br /><strong>Nadeel:</strong> Bij grotere forums met veel berichten en gebruikers kan het enige tijd duren om een onderwerp te laden, omdat alle informatie uit de database gehaald moet worden. De informatie of een bericht gelezen is of niet, zal na een bepaalde tijd uit de database gehaald worden, om tijd en ruimte te sparen, na deze periode zijn die berichten als gelezen gemarkeerd. De standaardperiode hiervoor is 30 dagen. Dit kan echter door de beheerders zijn aangepast. Bij twijfel kun je het de beheerder altijd vragen.'); 
$faq[] = array('Ik zie geen mogelijkheid in mijn profiel, waar ik het UPI2DB systeem aan en uit kan zetten', 'Als je deze mogeljkheid niet ziet, dan is het UPI2DB systeem door de beheerders van dit forum permanent uitgeschakeld. Dan is het niet mogelijk om van dit systeem gebruik te maken.'); 
$faq[] = array('Wat zijn de voorwaarden die een beheerder kan instellen?', 'Standaard geeft het UPI2DB systeem de mogelijkheid aan de beheerders om het aantal berichten dat een gebruiker moet hebben en/of hoe lang een gebruiker geregistreerd moet zijn, voordat het systeem geactiveerd wordt.'); 
$faq[] = array('Wat ik ook probeer, het lukt me niet om belangrijke onderwerpen of mededelingen als gelezen te markeren!', 'Belangrijke onderwerpen en mededelingen moeten worden gelezen! Daarom is het niet mogelijk zulke berichten als gelezen te markeren.!');
$faq[] = array('Wat ik ook probeer, het lukt me niet om belangrijke onderwerpen of mededelingen als permanent gelezen te markeren!', 'Belangrijke onderwerpen en mededelingen moeten worden gelezen! Daarom is het niet mogelijk deze berichten als permanent gelezen te markeren.!');
$faq[] = array('Ik moet na ieder ' . (!empty($unread_days) ? $unread_days : 0) . ' dagen een onderwerp opnieuw als "permanent ongelezen" markeren!', 'Dat klopt. We hebben een beveiliging in het systeem moeten zetten om het het systeem niet te vertragen. Alle gemarkeerde berichten na ' . (!empty($unread_days) ? $unread_days : 0) . ' dagen verwijderd uit de \'permanent ongelezen\' berichtenlijst.'); 
$faq[] = array('Hoe kan ik een forum markeren als "permanent gelezen"?', 'Klik op het plaatje voor de forumnaam, als je dat gedaan hebt, zal het plaatje veranderen.'); 
$faq[] = array('Hoe kan ik een onderwerp markeren als "permanent gelezen"?', 'Klik op het plaatje voor het onderwerp, als je dat gedaan hebt, zal het plaatje veranderen en het onderwerp zal verplaatst worden en onderaan de lijst van het betreffende forum komen te staan. Tevens is het mogelijk om onderaan het de pagina op de tekst "onderwerp permanent als gelezen markeren" te klikken.'); 
$faq[] = array('Ik heb een forum als permanent gelezen gemarkeerd, maar er verschijnt opeens een nieuw bericht!', 'Als iemand een belangrijke onderwerp of mededeling plaatst in een "permanent gelezen" forum, dan worden de instellingen hiervoor gereset. Dit gebeurt, omdat je zo dan geen belangrijke onderwerpen of mededelingen kunt missen.!');
$faq[] = array('Hoe kan ik een bericht markeren, zodat ik het later eenvoudig kan terugvinden?', 'Bij ieder bericht vind je een knop in de knoppenbalk, hiermee kun je een bericht markeren. Berichten ouder dan '. (!empty($unread_days) ? $unread_days : 0) .' dagen of berichten van voor je eigen registratiedatum, kunnen niet worden gemarkeerd.');
$faq[] = array('Hoe kan ik een reeds gelezen bericht weer als "ongelezen" markeren?', 'Bij ieder bericht vind je naast de titel een knopppenbalk, met een knop, om alle berichten die na dit bericht worden toegevoegd of gewijzigd, als ongelezen te markeren.'); 
$faq[] = array('Waarom kan ik sommige berichten niet markeren?', 'Berichten, die als permanent gelezen zijn gemarkeerd of die zijn geplaatst voor je eigen registratiedatum, kunnen niet worden gemarkeerd. ook is het niet mogelijk om berichten ouder dan ' . (!empty($unread_days) ? $unread_days : 0) . ' dagen te markeren.');
$faq[] = array('Blijven gemarkeerde berichten voor altijd gemarkeerd?', 'Nee, alle gemarkeerde berichten, worden automatisch verwijderd na ' . $del_mark .'  dagen.');
$faq[] = array('Wat betekent MAG?', 'Dit is de afkorting voor "Markeer alles als gelezen"');


$faq[] = array("--","phpBB 2");
$faq[] = array("Wie heeft phpBB gemaakt?", "Dit software (in ongewijzigde vorm) is geproduceerd, vrijgegeven en eigendom  van <a href=\"http://www.phpbb.com/\" onclick=\"window.open(this.href,'_blank');return false;\">phpBB Group</a>. Het is vrijgegeven onder de GNU General Public License en mag vrij gedistribueerd worden; bekijk de link voor meer informatie.");
$faq[] = array("Waarom is X onderdeel niet verkrijgbaar?", "Deze software is geschreven door en met vergunning van de phpBB Groep. Indien je van mening bent dat een bepaalde functionaliteit moet toegevoegd worden bezoek dan de www.phpbb.com website en kijk wat de phpBB Groep te zeggen heeft. Stuur alstublieft geen aanvragen naar de mensen op phpbb.com, de Groep gebruikt sourceforge.net om nieuwe ideeën te ontwikkelen. Lees in de forums en kijk of er misschien reeds een module in bewerking is en volg dan de uitgelegde procedure aldaar.");
$faq[] = array("Wie moet ik raadplegen i.v.m. misbruik en/of legale zaken op dit forum?", "Je kan de beheerder van dit forum raadplegen. Indien je niet weet wie dat is kan je eerst de forum moderators vragen wie je moet raadplegen. Krijg je nog steeds geen antwoord neem dan contact op met de eigenaar van de domeinnaam (doe een whois lookup) of, als dit een gratis service is (bijvoorbeeld. yahoo, free.fr, f2s.com, enz.), de management of misbruik beheer van deze service. Let op: De phpBB Groep heeft absoluut geen controle over individuele forums en is niet verantwoordelijk voor wie, waar en waarom dit forum is gebruikt. Het is onnodig de phpBB Groep te raadplegen i.v.m. met elke (ophouden, verantwoordelijkheid, enz.) zaak niet rechtstreeks verbonden aan de www.phpbb.com website of de software van phpBB zelf. Indien je een e-mail stuurt naar de phpBB Groep over een derde partij die deze software gebruikt kan je kort of helemaal geen antwoord verwachten.");


$faq[] = array("--", "Over Icy Phoenix");
$faq[] = array("Wat is Icy Phoenix?", "Icy Phoenix is een CMS (Content Management System) wat gebruikers toestaat om gemakkelijk een dynamische website te creëren met verschillende ingebakken functies: forum, portaal, aanpasbare pagina\'s en blokken, downloads, fotogallerij en nog veel meer.");
$faq[] = array("Wie heeft dit software geschreven", "Dit software is gebaseerd op phpBB wat is uitgebracht onder de GNU General Public License, doordaar is Icy Phoenix ok uitgebracht onder dezelfde licentie, en dat betekent dat je vrij bent in het aanpassen en het verspreiden van dit software. phpBB basisbestanden apart, meeste van de bestanden zijn direct gecodeerd of aangepast door Mighty Gorgon en het <a href=\"http://www.icyphoenix.com/\" target=\"_blank\">Icy Phoenix Team</a>. Een niet volledige lijst van de ontwikkelaars van dit project is te vinden via <a href=\"http://www.icyphoenix.com/credits.php\" target=\"_blank\">Icy Phoenix Credits</a>.");
$faq[] = array("Wie moet ik raadplegen i.v.m. misbruik en/of legale zaken op dit forum?", "Je kan de beheerder van dit forum raadplegen. Indien je niet weet wie dat is kan je eerst de forum moderators vragen wie je moet raadplegen. Krijg je nog steeds geen antwoord neem dan contact op met de eigenaar van de domeinnaam (doe een whois lookup) of, als dit een gratis service is (bijvoorbeeld. yahoo, free.fr, f2s.com, enz.), de management of misbruik beheer van deze service. Let op: De Icy Phoenix heeft absoluut geen controle over individuele forums en is niet verantwoordelijk voor wie, waar en waarom dit forum is gebruikt. Het is onnodig Icy Phoenix te raadplegen i.v.m. met elke (ophouden, verantwoordelijkheid, enz.) zaak niet rechtstreeks verbonden aan de icyphoenix.com website of de software van Icy Phoenix zelf. Indien je een e-mail stuurt naar de Icy Phoenix over een derde partij die deze software gebruikt kan je kort of helemaal geen antwoord verwachten.");


?>